In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#pip install pandas numpy matplotlib seaborn openpyxl statsmodels plotly

# 1.Load dataset

In [ ]:
# Load the Accessories sheet from the Excel file
accessories_data = pd.read_excel('/content/EIU case study - Sample data - Accessories.xlsx')

# Display the first few rows to inspect the data
accessories_data.head()

,Customer Name,Reporting Business Type,Collective Class,Series No,Item SKU,Item Description,Colors,Series Color,Item Grouping,AFI Sales Category,Import/Domestic Code,Market Introduced At,Parent Style Description,Warehouse,Order Quantity,FiscalMonthLastDate,Status
0,Customer-1,Others,ACCESSORIES,A2000550,A2000550,VASE (3/CS),Black,Black,Table Top,Sig. Ashley Accessories,I,QTR 1 2022,Casual,1,1,2023-05-27,Invoiced
1,Customer-2,eCommerce,ACCESSORIES,A4000107,A4000107,CONSOLE SOFA TABLE,Antique White/Brown,Antique White/Brown,Accent Furniture,Sig. Ashley Accessories,I,Las Vegas January 2018,Casual,17,1,2024-08-24,Invoiced
2,Customer-3,Others,ACCESSORIES,A3000301,A3000301,UPHOLSTERED ACCENT BENCH,Charcoal/Brown,Charcoal/Brown,Accent Seating,Sig. Ashley Accessories,I,High Point October 2020,Casual,1,1,2023-01-28,Invoiced
3,Customer-4,Others,ACCESSORIES,A3000271,A3000271,ACCENT CHAIR,Ivory/Brown,Ivory/Brown,Accent Seating,Sig. Ashley Accessories,I,High Point October 2020,Casual,5,3,2023-04-01,Invoiced
4,Customer-5,Others,ACCESSORIES,A2C00203,A2C00203,ACCESSORY SET (5/CN),Multi,Multi,Table Top,Sig. Ashley Accessories,I,QTR 2 2022,Casual,15,1,2023-04-29,Invoiced

# 2.Convert to wide format & Cleaning

In [ ]:
import pandas as pd

# -------------------------------
# Step 0: Data Preparation and Cleaning
# -------------------------------
# Giả sử accessories_data đã được load, ví dụ:
# accessories_data = pd.read_excel("YourFile.xlsx", sheet_name="Outdoor")
df = accessories_data[[
    "FiscalMonthLastDate", "Warehouse", "Series No", "Item SKU", "Order Quantity"
]].copy().dropna()

# Đổi tên cột: thay khoảng trắng bằng dấu "-" để dễ xử lý
df.columns = [col.replace(" ", "-") for col in df.columns]

# Chuyển FiscalMonthLastDate sang kiểu datetime
df["FiscalMonthLastDate"] = pd.to_datetime(df["FiscalMonthLastDate"])

# -------------------------------
# Step 1: Aggregate Data at the Series Level
# -------------------------------
# Chúng ta chỉ quan tâm đến cột "Series No". Mỗi hàng sẽ được gộp theo FiscalMonthLastDate và Series-No.
df_agg = df.groupby(["FiscalMonthLastDate", "Series-No"])["Order-Quantity"].sum().reset_index()

# -------------------------------
# Step 2: Convert to Wide Format for Forecasting
# -------------------------------
# Pivot table: index = FiscalMonthLastDate, các cột là các giá trị của "Series-No"
df_wide = df_agg.pivot_table(
    index="FiscalMonthLastDate",
    columns="Series-No",
    values="Order-Quantity",
    fill_value=0
)

# -------------------------------
# Step 3: Compute Hierarchical Aggregations (2-level: Total and Series)
# -------------------------------
# 3.1: Total (Overall Sum): tổng của tất cả các Series
df_total = df_wide.sum(axis=1).to_frame(name=("Total",))

# 3.2: Series-level: giữ lại dữ liệu của các Series, đặt tên cột thành MultiIndex (1 cấp)
df_series = df_wide.copy()
df_series.columns = pd.MultiIndex.from_tuples([(col,) for col in df_series.columns])

# -------------------------------
# Step 4: Merge Total and Series-level Data
# -------------------------------
df_hierarchical = pd.concat([df_total, df_series], axis=1)

# -------------------------------
# Step 5: Sort Columns Hierarchically
# -------------------------------
# Sắp xếp sao cho cột "Total" đứng đầu, sau đó các Series được sắp xếp theo tên (alphabet)
ordered_columns = sorted(
    df_hierarchical.columns,
    key=lambda x: (0 if x[0] == "Total" else 1, x[0])
)
df_hierarchical = df_hierarchical[ordered_columns]

# -------------------------------
# Step 6: Flatten MultiIndex Columns
# -------------------------------
# Vì các cột Series đã có MultiIndex 1 cấp, ta chỉ lấy phần tử đầu tiên của mỗi tuple
df_hierarchical.columns = [col[0] for col in df_hierarchical.columns]

# -------------------------------
# (Optional) Replace specific dates in the index if needed
# -------------------------------
df_hierarchical.index = df_hierarchical.index.to_series().replace({
    pd.Timestamp("2023-04-01"): pd.Timestamp("2023-03-25"),
    pd.Timestamp("2023-07-01"): pd.Timestamp("2023-06-24")
})

df_hierarchical

,Total,36206,36207,36208,36229,36230,36232,53302,53303,A1000954,...,T505-106,T505-560,T505-562,T505-662,T505-742,T505-762,T505-962,T800,T800-111,T800-124
FiscalMonthLastDate,,,,,,,,,,,,,,,,,,,,,
2022-01-22,94220.0,272.0,370.0,442.0,120.0,145.0,135.0,18.0,158.0,15.0,...,92.0,243.0,109.0,122.0,99.0,286.0,80.0,184.0,339.0,193.0
2022-02-19,105423.0,272.0,479.0,590.0,122.0,173.0,282.0,37.0,213.0,6.0,...,119.0,227.0,97.0,125.0,128.0,262.0,120.0,183.0,327.0,179.0
2022-03-26,131285.0,277.0,562.0,573.0,267.0,274.0,343.0,15.0,226.0,19.0,...,109.0,234.0,151.0,87.0,117.0,314.0,115.0,275.0,369.0,740.0
2022-04-23,72222.0,165.0,198.0,320.0,104.0,98.0,143.0,27.0,120.0,1.0,...,117.0,160.0,90.0,149.0,77.0,223.0,83.0,171.0,312.0,326.0
2022-05-21,75760.0,157.0,201.0,231.0,162.0,144.0,144.0,16.0,140.0,2.0,...,76.0,144.0,76.0,194.0,79.0,164.0,81.0,155.0,253.0,127.0
2022-06-25,85249.0,153.0,213.0,351.0,181.0,168.0,200.0,11.0,144.0,4.0,...,96.0,177.0,84.0,69.0,68.0,342.0,71.0,250.0,454.0,473.0
2022-07-23,71975.0,111.0,175.0,201.0,115.0,177.0,179.0,20.0,157.0,6.0,...,78.0,164.0,50.0,58.0,90.0,488.0,43.0,144.0,87.0,77.0
2022-08-20,77834.0,120.0,255.0,370.0,109.0,70.0,169.0,3.0,165.0,1.0,...,71.0,275.0,99.0,228.0,95.0,335.0,113.0,116.0,112.0,52.0
2022-09-24,107000.0,232.0,222.0,368.0,166.0,192.0,246.0,6.0,283.0,1.0,...,834.0,277.0,151.0,134.0,178.0,707.0,141.0,197.0,452.0,100.0
2022-10-22,82227.0,105.0,147.0,216.0,116.0,125.0,131.0,0.0,240.0,2.0,...,68.0,265.0,114.0,167.0,181.0,230.0,114.0,181.0,145.0,163.0
2022-11-19,83406.0,118.0,178.0,291.0,132.0,126.0,151.0,0.0,171.0,0.0,...,109.0,295.0,131.0,106.0,176.0,246.0,132.0,250.0,176.0,203.0
2022-12-31,104874.0,89.0,197.0,244.0,120.0,139.0,186.0,5.0,217.0,0.0,...,118.0,369.0,133.0,94.0,146.0,266.0,163.0,299.0,295.0,237.0
2023-01-28,77042.0,132.0,165.0,217.0,95.0,105.0,135.0,0.0,182.0,1.0,...,86.0,223.0,143.0,73.0,87.0,177.0,80.0,195.0,113.0,127.0
2023-02-25,90268.0,96.0,165.0,244.0,80.0,78.0,140.0,0.0,233.0,4.0,...,101.0,180.0,68.0,85.0,140.0,177.0,86.0,181.0,157.0,118.0
2023-03-25,90481.0,143.0,225.0,334.0,116.0,81.0,130.0,0.0,211.0,1.0,...,125.0,305.0,62.0,94.0,176.0,267.0,147.0,211.0,238.0,229.0
2023-04-29,65787.0,103.0,122.0,225.0,73.0,59.0,70.0,0.0,67.0,0.0,...,82.0,227.0,54.0,51.0,98.0,162.0,72.0,228.0,122.0,147.0
2023-05-27,63781.0,110.0,33.0,251.0,68.0,77.0,131.0,0.0,52.0,0.0,...,79.0,151.0,60.0,85.0,82.0,215.0,66.0,144.0,152.0,148.0
2023-06-24,81701.0,105.0,5.0,185.0,91.0,86.0,128.0,0.0,5.0,0.0,...,145.0,210.0,75.0,104.0,47.0,242.0,78.0,89.0,164.0,197.0
2023-07-29,65017.0,27.0,1.0,205.0,76.0,147.0,125.0,0.0,1.0,0.0,...,129.0,153.0,48.0,53.0,0.0,337.0,86.0,83.0,89.0,113.0
2023-08-26,76636.0,3.0,0.0,7.0,94.0,75.0,91.0,0.0,0.0,0.0,...,141.0,210.0,41.0,57.0,0.0,189.0,25.0,93.0,146.0,122.0
2023-09-30,124436.0,1.0,0.0,0.0,90.0,111.0,138.0,0.0,0.0,0.0,...,111.0,250.0,48.0,112.0,0.0,734.0,29.0,155.0,252.0,210.0
2023-10-28,81081.0,0.0,0.0,0.0,93.0,52.0,90.0,0.0,0.0,0.0,...,23.0,145.0,42.0,45.0,0.0,127.0,6.0,203.0,160.0,112.0
2023-11-25,84540.0,0.0,0.0,0.0,34.0,87.0,109.0,0.0,0.0,0.0,...,2.0,158.0,39.0,11.0,0.0,222.0,3.0,223.0,129.0,193.0
2023-12-30,86118.0,0.0,0.0,0.0,14.0,102.0,155.0,0.0,0.0,0.0,...,0.0,197.0,19.0,3.0,0.0,235.0,0.0,179.0,219.0,239.0
2024-01-27,94279.0,0.0,0.0,0.0,21.0,53.0,44.0,0.0,0.0,0.0,...,0.0,144.0,4.0,0.0,0.0,170.0,0.0,96.0,105.0,146.0
2024-02-24,129682.0,0.0,0.0,0.0,0.0,4.0,40.0,0.0,0.0,0.0,...,1.0,170.0,1.0,0.0,0.0,195.0,0.0,115.0,120.0,111.0
2024-03-30,97583.0,468.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,...,0.0,170.0,0.0,0.0,0.0,220.0,0.0,180.0,218.0,179.0
2024-04-27,67502.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,140.0,0.0,0.0,0.0,157.0,0.0,136.0,118.0,151.0
2024-05-25,72660.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,121.0,0.0,0.0,0.0,172.0,0.0,113.0,170.0,100.0
2024-06-29,95487.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,194.0,0.0,0.0,0.0,289.0,0.0,139.0,125.0,124.0
2024-07-27,80108.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,134.0,0.0,0.0,0.0,149.0,0.0,104.0,51.0,132.0
2024-08-24,70821.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,146.0,0.0,0.0,0.0,196.0,0.0,150.0,0.0,125.0
2024-09-28,91821.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,202.0,0.0,0.0,0.0,193.0,0.0,146.0,0.0,12.0
2024-10-26,73938.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,133.0,0.0,0.0,0.0,139.0,0.0,58.0,0.0,0.0
2024-11-23,87498.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,189.0,0.0,0.0,0.0,168.0,0.0,4.0,0.0,0.0
2024-12-28,115614.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,199.0,0.0,0.0,0.0,248.0,0.0,1.0,0.0,0.0

# 3.Classify the Series into groups a, b, c and x, y, z according to sales

In [ ]:
# -------------------------------
# Phần 2: Phân loại các Series thành nhóm a, b, c theo doanh số
# -------------------------------
series_cols = [col for col in df_hierarchical.columns if col != "Total"]

# Tính tổng doanh số cho mỗi Series
series_totals = df_hierarchical[series_cols].sum(axis=0).reset_index()
series_totals.columns = ['Series-No', 'Total_Sales']
overall_total = series_totals['Total_Sales'].sum()
n_total = len(series_totals)

# Sắp xếp giảm dần theo Total_Sales
series_totals = series_totals.sort_values(by='Total_Sales', ascending=False).reset_index(drop=True)

# Nhóm a: chọn các series theo thứ tự giảm dần cho đến khi tích lũy ≥80% overall sales,
#         nhưng số lượng không vượt quá 20% tổng số series.
max_count_a = int(0.2 * n_total)
cumulative_sales_a = 0
group_a = []
for idx, row in series_totals.iterrows():
    group_a.append(row['Series-No'])
    cumulative_sales_a += row['Total_Sales']
    if (cumulative_sales_a / overall_total >= 0.80) or (len(group_a) >= max_count_a):
        break

# Nhóm b: từ các series còn lại, chọn đến khi tích lũy ≥15% overall sales,
#         nhưng số lượng không vượt quá 30% số series còn lại.
remaining_df = series_totals[~series_totals['Series-No'].isin(group_a)].copy()
n_remaining = len(remaining_df)
max_count_b = int(0.3 * n_remaining)
cumulative_sales_b = 0
group_b = []
for idx, row in remaining_df.iterrows():
    group_b.append(row['Series-No'])
    cumulative_sales_b += row['Total_Sales']
    if (cumulative_sales_b / overall_total >= 0.15) or (len(group_b) >= max_count_b):
        break

# Nhóm c: các series còn lại
group_c = remaining_df[~remaining_df['Series-No'].isin(group_b)]['Series-No'].tolist()

series_totals['Group'] = series_totals['Series-No'].apply(
    lambda x: 'a' if x in group_a else ('b' if x in group_b else 'c')
)

print("\nPhân nhóm doanh số (a, b, c):")
print("Tổng số Series:", n_total)
print("Nhóm a: {} Series, chiếm {:.2%} doanh số".format(len(group_a), cumulative_sales_a / overall_total))
print("Nhóm b: {} Series, chiếm {:.2%} doanh số".format(len(group_b), cumulative_sales_b / overall_total))
remaining_sales = overall_total - cumulative_sales_a - cumulative_sales_b
print("Nhóm c: {} Series, chiếm {:.2%} doanh số".format(len(group_c), remaining_sales / overall_total))






# -------------------------------
# Phần 3: Phân nhóm bổ sung x, y, z trong mỗi nhóm a, b, c theo hệ số biến động (CV)
# -------------------------------
# Tính CV từ dữ liệu 12 tháng cuối của wide format
last_12 = df_hierarchical.iloc[-12:]
def compute_cv(series_data):
    mean_val = series_data.mean()
    return np.nan if mean_val == 0 else series_data.std() / mean_val

# Tính CV cho tất cả các series
cv_dict = {series: compute_cv(last_12[series]) for series in series_cols}

# Áp dụng ngưỡng phân loại CV: X: CV < 0.34, Y: 0.34 ≤ CV < 0.84, Z: CV ≥ 0.84.
subgroup_dict = {}
for series, cv_val in cv_dict.items():
    if pd.isna(cv_val):
        subgroup = 'unknown'
    elif cv_val < 0.34:
        subgroup = 'x'
    elif cv_val < 0.84:
        subgroup = 'y'
    else:
        subgroup = 'z'
    subgroup_dict[series] = subgroup

# In bảng tóm tắt số lượng các nhóm phụ
from collections import Counter
subgroup_counts = Counter(subgroup_dict.values())
print("\nPhân loại phụ theo CV:")
for key in ['x', 'y', 'z', 'unknown']:
    print(f"Nhóm {key}: {subgroup_counts.get(key, 0)} series")

# -------------------------------
# Phần 4: Gán nhãn kết hợp vào tên cột wide format
# -------------------------------
# Tạo mapping cuối: tên cột sẽ có định dạng <Series-No>_<Group (a,b,c)>_<Subgroup (x,y,z,unknown)>
final_mapping = {}
for series in series_cols:
    # Lấy nhãn nhóm a,b,c từ series_totals
    group_label = series_totals.loc[series_totals['Series-No'] == series, 'Group'].values[0]
    subgroup_label = subgroup_dict.get(series, '')
    final_mapping[series] = f"{series}_{group_label}_{subgroup_label}"

# Cập nhật tên cột trong df_hierarchical (cột Total giữ nguyên)
new_columns = {}
for col in df_hierarchical.columns:
    if col == "Total":
        new_columns[col] = col
    else:
        new_columns[col] = final_mapping.get(col, col)

df_final = df_hierarchical.rename(columns=new_columns)

print("\nWide Format DataFrame sau khi gán nhãn a,b,c và x,y,z:")

df_final

Phân nhóm doanh số (a, b, c):
Tổng số Series: 1836
Nhóm a: 367 Series, chiếm 66.63% doanh số
Nhóm b: 254 Series, chiếm 15.00% doanh số
Nhóm c: 1215 Series, chiếm 18.37% doanh số

Phân loại phụ theo CV:
Nhóm x: 124 series
Nhóm y: 442 series
Nhóm z: 974 series
Nhóm unknown: 296 series

Wide Format DataFrame sau khi gán nhãn a,b,c và x,y,z:

,Total,36206_a_z,36207_a_unknown,36208_a_unknown,36229_a_z,36230_a_z,36232_a_z,53302_c_unknown,53303_a_unknown,A1000954_c_unknown,...,T505-106_a_z,T505-560_a_x,T505-562_b_z,T505-662_b_unknown,T505-742_b_unknown,T505-762_a_x,T505-962_b_unknown,T800_a_y,T800-111_a_z,T800-124_a_y
FiscalMonthLastDate,,,,,,,,,,,,,,,,,,,,,
2022-01-22,94220.0,272.0,370.0,442.0,120.0,145.0,135.0,18.0,158.0,15.0,...,92.0,243.0,109.0,122.0,99.0,286.0,80.0,184.0,339.0,193.0
2022-02-19,105423.0,272.0,479.0,590.0,122.0,173.0,282.0,37.0,213.0,6.0,...,119.0,227.0,97.0,125.0,128.0,262.0,120.0,183.0,327.0,179.0
2022-03-26,131285.0,277.0,562.0,573.0,267.0,274.0,343.0,15.0,226.0,19.0,...,109.0,234.0,151.0,87.0,117.0,314.0,115.0,275.0,369.0,740.0
2022-04-23,72222.0,165.0,198.0,320.0,104.0,98.0,143.0,27.0,120.0,1.0,...,117.0,160.0,90.0,149.0,77.0,223.0,83.0,171.0,312.0,326.0
2022-05-21,75760.0,157.0,201.0,231.0,162.0,144.0,144.0,16.0,140.0,2.0,...,76.0,144.0,76.0,194.0,79.0,164.0,81.0,155.0,253.0,127.0
2022-06-25,85249.0,153.0,213.0,351.0,181.0,168.0,200.0,11.0,144.0,4.0,...,96.0,177.0,84.0,69.0,68.0,342.0,71.0,250.0,454.0,473.0
2022-07-23,71975.0,111.0,175.0,201.0,115.0,177.0,179.0,20.0,157.0,6.0,...,78.0,164.0,50.0,58.0,90.0,488.0,43.0,144.0,87.0,77.0
2022-08-20,77834.0,120.0,255.0,370.0,109.0,70.0,169.0,3.0,165.0,1.0,...,71.0,275.0,99.0,228.0,95.0,335.0,113.0,116.0,112.0,52.0
2022-09-24,107000.0,232.0,222.0,368.0,166.0,192.0,246.0,6.0,283.0,1.0,...,834.0,277.0,151.0,134.0,178.0,707.0,141.0,197.0,452.0,100.0
2022-10-22,82227.0,105.0,147.0,216.0,116.0,125.0,131.0,0.0,240.0,2.0,...,68.0,265.0,114.0,167.0,181.0,230.0,114.0,181.0,145.0,163.0
2022-11-19,83406.0,118.0,178.0,291.0,132.0,126.0,151.0,0.0,171.0,0.0,...,109.0,295.0,131.0,106.0,176.0,246.0,132.0,250.0,176.0,203.0
2022-12-31,104874.0,89.0,197.0,244.0,120.0,139.0,186.0,5.0,217.0,0.0,...,118.0,369.0,133.0,94.0,146.0,266.0,163.0,299.0,295.0,237.0
2023-01-28,77042.0,132.0,165.0,217.0,95.0,105.0,135.0,0.0,182.0,1.0,...,86.0,223.0,143.0,73.0,87.0,177.0,80.0,195.0,113.0,127.0
2023-02-25,90268.0,96.0,165.0,244.0,80.0,78.0,140.0,0.0,233.0,4.0,...,101.0,180.0,68.0,85.0,140.0,177.0,86.0,181.0,157.0,118.0
2023-03-25,90481.0,143.0,225.0,334.0,116.0,81.0,130.0,0.0,211.0,1.0,...,125.0,305.0,62.0,94.0,176.0,267.0,147.0,211.0,238.0,229.0
2023-04-29,65787.0,103.0,122.0,225.0,73.0,59.0,70.0,0.0,67.0,0.0,...,82.0,227.0,54.0,51.0,98.0,162.0,72.0,228.0,122.0,147.0
2023-05-27,63781.0,110.0,33.0,251.0,68.0,77.0,131.0,0.0,52.0,0.0,...,79.0,151.0,60.0,85.0,82.0,215.0,66.0,144.0,152.0,148.0
2023-06-24,81701.0,105.0,5.0,185.0,91.0,86.0,128.0,0.0,5.0,0.0,...,145.0,210.0,75.0,104.0,47.0,242.0,78.0,89.0,164.0,197.0
2023-07-29,65017.0,27.0,1.0,205.0,76.0,147.0,125.0,0.0,1.0,0.0,...,129.0,153.0,48.0,53.0,0.0,337.0,86.0,83.0,89.0,113.0
2023-08-26,76636.0,3.0,0.0,7.0,94.0,75.0,91.0,0.0,0.0,0.0,...,141.0,210.0,41.0,57.0,0.0,189.0,25.0,93.0,146.0,122.0
2023-09-30,124436.0,1.0,0.0,0.0,90.0,111.0,138.0,0.0,0.0,0.0,...,111.0,250.0,48.0,112.0,0.0,734.0,29.0,155.0,252.0,210.0
2023-10-28,81081.0,0.0,0.0,0.0,93.0,52.0,90.0,0.0,0.0,0.0,...,23.0,145.0,42.0,45.0,0.0,127.0,6.0,203.0,160.0,112.0
2023-11-25,84540.0,0.0,0.0,0.0,34.0,87.0,109.0,0.0,0.0,0.0,...,2.0,158.0,39.0,11.0,0.0,222.0,3.0,223.0,129.0,193.0
2023-12-30,86118.0,0.0,0.0,0.0,14.0,102.0,155.0,0.0,0.0,0.0,...,0.0,197.0,19.0,3.0,0.0,235.0,0.0,179.0,219.0,239.0
2024-01-27,94279.0,0.0,0.0,0.0,21.0,53.0,44.0,0.0,0.0,0.0,...,0.0,144.0,4.0,0.0,0.0,170.0,0.0,96.0,105.0,146.0
2024-02-24,129682.0,0.0,0.0,0.0,0.0,4.0,40.0,0.0,0.0,0.0,...,1.0,170.0,1.0,0.0,0.0,195.0,0.0,115.0,120.0,111.0
2024-03-30,97583.0,468.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,...,0.0,170.0,0.0,0.0,0.0,220.0,0.0,180.0,218.0,179.0
2024-04-27,67502.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,140.0,0.0,0.0,0.0,157.0,0.0,136.0,118.0,151.0
2024-05-25,72660.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,121.0,0.0,0.0,0.0,172.0,0.0,113.0,170.0,100.0
2024-06-29,95487.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,194.0,0.0,0.0,0.0,289.0,0.0,139.0,125.0,124.0
2024-07-27,80108.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,134.0,0.0,0.0,0.0,149.0,0.0,104.0,51.0,132.0
2024-08-24,70821.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,146.0,0.0,0.0,0.0,196.0,0.0,150.0,0.0,125.0
2024-09-28,91821.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,202.0,0.0,0.0,0.0,193.0,0.0,146.0,0.0,12.0
2024-10-26,73938.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,133.0,0.0,0.0,0.0,139.0,0.0,58.0,0.0,0.0
2024-11-23,87498.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,189.0,0.0,0.0,0.0,168.0,0.0,4.0,0.0,0.0
2024-12-28,115614.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,199.0,0.0,0.0,0.0,248.0,0.0,1.0,0.0,0.0

# 4.Identify Stop Produced Series and Valid Series

In [ ]:
# -------------------------------
# Phần 5: Tách Stop Produced Series và Valid Series
# -------------------------------
# Lấy dữ liệu 12 tháng cuối
last_12 = df_final.iloc[-12:]

# Xác định các cột mà toàn bộ 12 giá trị cuối cùng đều bằng 0
stop_columns = [col for col in df_final.columns if (last_12[col] == 0).all()]

# Tạo DataFrame chứa các stop produced series và valid series
df_zero = df_final[stop_columns]
df_valid = df_final.drop(columns=stop_columns)

# In ra số lượng các series từng loại
print("Số lượng stop produced series:", len(stop_columns))
print("Số lượng valid series:", len(df_valid.columns) - (1 if 'Total' in df_valid.columns else 0)-1)

# -------------------------------
# Lưu kết quả thành 2 file CSV
# -------------------------------
df_zero.to_csv("Stopped_Series_Hierarchical.csv", index=True)
df_valid.to_csv("Series_Hierarchical.csv", index=True)

Số lượng stop produced series: 296
Số lượng valid series: 1539

#5.Use the Exponential Smoothing for Series x

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.holtwinters import ExponentialSmoothing
import warnings
warnings.filterwarnings("ignore")

# --- Bước 1: Load dữ liệu ---
df_final = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df_final.index = pd.to_datetime(df_final.index)

# --- Bước 2: Phân loại các series hợp lệ ---
# Loại bỏ cột "Total" và chỉ xét các cột chứa dữ liệu series
valid_series_cols = [col for col in df_final.columns if col != 'Total']

# Giả sử các cột đã được gán nhãn theo định dạng: <Series-No>_<group a,b,c>_<subgroup: x, y, z, unknown>
valid_x = [col for col in valid_series_cols if col.endswith('_x')]
valid_y = [col for col in valid_series_cols if col.endswith('_y')]
valid_z = [col for col in valid_series_cols if col.endswith('_z')]

print("Tổng số series hợp lệ:")
print("Nhóm x:", len(valid_x))
print("Nhóm y:", len(valid_y))
print("Nhóm z:", len(valid_z))

# --- Bước 3: Xây dựng hàm dự báo cho 1 series ---
def forecast_series(series, forecast_periods=6):
    """
    Chia dữ liệu thành train (all trừ forecast_periods cuối) và test (forecast_periods cuối),
    xây dựng mô hình Exponential Smoothing và trả về forecast cùng test set dưới dạng numpy array.
    Nếu không fit được mô hình, trả về None.
    """
    if len(series) < forecast_periods + 1:
        return None
    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]

    # Cố gắng fit mô hình với seasonality (chu kỳ 12 tháng) nếu có thể
    try:
        model = ExponentialSmoothing(train, trend='add', seasonal= None,
                                     seasonal_periods=12, damped_trend=True).fit()
    except Exception as e:
        try:
            model = ExponentialSmoothing(train, trend='add', seasonal=None,
                                         damped_trend=True).fit()
        except Exception as e2:
            return None
    forecast = model.forecast(forecast_periods)
    # Chuyển về mảng numpy để tránh lỗi căn chỉnh index
    return np.array(forecast), np.array(test)

# --- Bước 4: Hàm tính wMAPE cho 1 nhóm series ---
def compute_wmape(group, forecast_periods=6):
    total_abs_error = 0.0
    total_actual = 0.0
    valid_count = 0  # đếm số series có thể tính được wMAPE (không chia cho 0)
    for col in group:
        series = df_final[col]
        result = forecast_series(series, forecast_periods)
        if result is None:
            continue
        forecast_arr, test_arr = result
        # Nếu tổng giá trị thực của test = 0, bỏ qua series này để tránh chia cho 0
        if np.sum(test_arr) == 0:
            continue
        abs_err = np.abs(forecast_arr - test_arr)
        total_abs_error += np.sum(abs_err)
        total_actual += np.sum(test_arr)
        valid_count += 1
    if total_actual == 0:
        return np.nan, valid_count
    return total_abs_error / total_actual, valid_count

forecast_periods = 6
wmape_x, valid_count_x = compute_wmape(valid_x, forecast_periods)
wmape_y, valid_count_y = compute_wmape(valid_y, forecast_periods)
wmape_z, valid_count_z = compute_wmape(valid_z, forecast_periods)

# --- Bước 5: Tạo bảng tổng hợp kết quả ---
summary_data = {
    "Nhóm": ["x (CV < 0.34)", "y (0.34 ≤ CV < 0.84)", "z (CV ≥ 0.84)"],
    "Tổng số series hợp lệ": [len(valid_x), len(valid_y), len(valid_z)],
    "Số series tính được wMAPE": [valid_count_x, valid_count_y, valid_count_z],
    "wMAPE hiện tại": [
        f"{wmape_x:.2%}" if not np.isnan(wmape_x) else "NaN",
        f"{wmape_y:.2%}" if not np.isnan(wmape_y) else "NaN",
        f"{wmape_z:.2%}" if not np.isnan(wmape_z) else "NaN"
    ],
    "Yêu cầu wMAPE": ["< 25%", "< 30%", "< 35%"]
}

summary_df = pd.DataFrame(summary_data)
print("\nBảng tổng hợp:")
print(summary_df)

Tổng số series hợp lệ:
Nhóm x: 124
Nhóm y: 442
Nhóm z: 974

Bảng tổng hợp:
                   Nhóm  Tổng số series hợp lệ  Số series tính được wMAPE  \
0         x (CV < 0.34)                    124                        124
1  y (0.34 ≤ CV < 0.84)                    442                        442
2         z (CV ≥ 0.84)                    974                        853

  wMAPE hiện tại Yêu cầu wMAPE
0         29.47%         < 25%
1         60.26%         < 30%
2        116.84%         < 35%

In [ ]:
summary_df

,Nhóm,Tổng số series hợp lệ,Số series tính được wMAPE,wMAPE hiện tại,Yêu cầu wMAPE
0,x (CV < 0.34),124,124,29.47%,< 25%
1,y (0.34 ≤ CV < 0.84),442,442,60.26%,< 30%
2,z (CV ≥ 0.84),974,853,116.84%,< 35%

# 6.Use the ARIMA/SARIMA & Exponential Smoothing for Group X. => Choose the model that have the best wMape for each series

## Code Block 1: Forecast Model cho Nhóm X (CV < 0.34 – dữ liệu ổn định)

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
import warnings
warnings.filterwarnings("ignore")

# Load dữ liệu
df_final = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df_final.index = pd.to_datetime(df_final.index)

# Lọc các cột thuộc Group X (tên kết thúc bằng _x)
group_x_cols = [col for col in df_final.columns if col != 'Total' and col.endswith('_x')]
forecast_periods = 6
wmape_threshold = 0.25  # Yêu cầu: wMAPE < 25%

series_results = []
overall_total_abs_error = 0.0
overall_total_actual = 0.0

trend_threshold = 0.05  # Ngưỡng xác định xu hướng

# Các cấu hình ARIMA non-seasonal cần thử
non_seasonal_orders = [(1,1,0), (0,1,1), (1,1,1), (2,1,1)]
# Các cấu hình SARIMA cần thử (non-seasonal_order, seasonal_order)
seasonal_orders = [((1,1,0), (1,0,1,12)), ((0,1,1), (1,0,1,12))]

for col in group_x_cols:
    series = df_final[col]
    if len(series) < forecast_periods + 1:
        series_results.append({
            "Series": col,
            "Model": None,
            "wMAPE": None,
            "Status": "Invalid: Not enough data"
        })
        continue

    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]
    test_arr = np.array(test)

    # Tính xu hướng: so sánh giá trị đầu và cuối của train
    initial = train.iloc[0]
    final = train.iloc[-1]
    trend_ratio = abs(final - initial) / (abs(initial) + 1e-8)

    candidate_models = []

    # Thử các mô hình ES
    if trend_ratio > trend_threshold:
        try:
            model_add = ExponentialSmoothing(train, trend='add', seasonal=None, damped_trend=True).fit()
            forecast_add = model_add.forecast(forecast_periods)
            candidate_models.append(("Holt's Add", model_add, np.array(forecast_add)))
        except Exception as e:
            pass
        if (train > 0).all():
            try:
                model_mult = ExponentialSmoothing(train, trend='mul', seasonal=None, damped_trend=True).fit()
                forecast_mult = model_mult.forecast(forecast_periods)
                candidate_models.append(("Holt's Mul", model_mult, np.array(forecast_mult)))
            except Exception as e:
                pass
    else:
        try:
            model_simple = ExponentialSmoothing(train, trend=None, seasonal=None).fit()
            forecast_simple = model_simple.forecast(forecast_periods)
            candidate_models.append(("Simple ES", model_simple, np.array(forecast_simple)))
        except Exception as e:
            pass

    # Chọn mô hình ES tốt nhất dựa trên tổng lỗi
    best_model_name = None
    best_error = np.inf
    best_forecast = None
    for name, model, forecast_arr in candidate_models:
        if np.sum(test_arr) == 0:
            continue
        error = np.sum(np.abs(forecast_arr - test_arr))
        if error < best_error:
            best_error = error
            best_forecast = forecast_arr
            best_model_name = name
    current_wmape = best_error / np.sum(test_arr) if np.sum(test_arr) > 0 else np.inf

    # Nếu wMAPE từ ES >= threshold, thử ARIMA grid search
    if current_wmape >= wmape_threshold:
        # Thử ARIMA non-seasonal
        for order in non_seasonal_orders:
            try:
                model_arima = ARIMA(train, order=order).fit()
                forecast_arima = model_arima.forecast(forecast_periods)
                forecast_arima = np.array(forecast_arima)
                error_arima = np.sum(np.abs(forecast_arima - test_arr))
                wmape_arima = error_arima / np.sum(test_arr)
                if wmape_arima < current_wmape:
                    best_model_name = f"ARIMA{order}"
                    best_error = error_arima
                    best_forecast = forecast_arima
                    current_wmape = wmape_arima
            except Exception as e:
                continue
        # Thử SARIMA nếu độ dài train đủ (> seasonal_period)
        seasonal_period = 12
        if len(train) > seasonal_period:
            for non_seasonal_order, seasonal_order in seasonal_orders:
                try:
                    model_sarima = SARIMAX(train, order=non_seasonal_order, seasonal_order=seasonal_order).fit(disp=False)
                    forecast_sarima = model_sarima.forecast(forecast_periods)
                    forecast_sarima = np.array(forecast_sarima)
                    error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                    wmape_sarima = error_sarima / np.sum(test_arr)
                    if wmape_sarima < current_wmape:
                        best_model_name = f"SARIMA{non_seasonal_order, seasonal_order}"
                        best_error = error_sarima
                        best_forecast = forecast_sarima
                        current_wmape = wmape_sarima
                except Exception as e:
                    continue

    if np.sum(test_arr) == 0:
        series_results.append({
            "Series": col,
            "Model": best_model_name,
            "wMAPE": None,
            "Status": "Invalid: Test sum zero"
        })
        continue

    status = "Valid" if current_wmape < wmape_threshold else "Invalid: wMAPE too high"

    if status == "Valid":
        overall_total_abs_error += best_error
        overall_total_actual += np.sum(test_arr)

    series_results.append({
        "Series": col,
        "Model": best_model_name,
        "wMAPE": current_wmape,
        "Status": status
    })

overall_wmape = overall_total_abs_error / overall_total_actual if overall_total_actual != 0 else np.nan

df_results = pd.DataFrame(series_results)
df_results["wMAPE (%)"] = df_results["wMAPE"].apply(lambda x: f"{x:.2%}" if pd.notnull(x) else None)

summary = {
    "Group": "X (CV < 0.34)",
    "Total Series": len(group_x_cols),
    "Valid Series": df_results[df_results["Status"]=="Valid"].shape[0],
    "Invalid Series": df_results[df_results["Status"]!="Valid"].shape[0],
    "Overall wMAPE": f"{overall_wmape:.2%}" if pd.notnull(overall_wmape) else "NaN"
}
df_summary = pd.DataFrame([summary])

print("=== Group X - Individual Series Results (With Extended ARIMA/SARIMA Grid Search) ===")
print(df_results[["Series", "Model", "wMAPE (%)", "Status"]])
print("\n=== Group X - Summary (Valid series: wMAPE < 25%) ===")
df_summary

=== Group X - Individual Series Results (With Extended ARIMA/SARIMA Grid Search) ===
           Series                             Model wMAPE (%)  \
0    A2000108_a_x                    ARIMA(1, 1, 0)    22.78%
1    A2000223_a_x                        Holt's Add    23.17%
2    A2000255_a_x                        Holt's Add    28.40%
3    A2000381_a_x                        Holt's Add    13.96%
4    A2000412_a_x  SARIMA((1, 1, 0), (1, 0, 1, 12))    20.74%
..            ...                               ...       ...
119  A8010372_b_x  SARIMA((0, 1, 1), (1, 0, 1, 12))    21.71%
120  A8010374_b_x                    ARIMA(2, 1, 1)    24.69%
121  A8010378_b_x  SARIMA((1, 1, 0), (1, 0, 1, 12))    27.02%
122  T505-560_a_x                        Holt's Mul    15.09%
123  T505-762_a_x                    ARIMA(2, 1, 1)    26.23%

                      Status
0                      Valid
1                      Valid
2    Invalid: wMAPE too high
3                      Valid
4                      Valid
..                       ...
119                    Valid
120                    Valid
121  Invalid: wMAPE too high
122                    Valid
123  Invalid: wMAPE too high

[124 rows x 4 columns]

=== Group X - Summary (Valid series: wMAPE < 25%) ===

           Group  Total Series  Valid Series  Invalid Series Overall wMAPE
0  X (CV < 0.34)           124            75              49        19.54%

## Code Block 2: Forecast Model cho Nhóm Y (0.34 ≤ CV < 0.84 – dữ liệu có seasonality trung bình)

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.holtwinters import ExponentialSmoothing
import warnings
warnings.filterwarnings("ignore")

# Load dữ liệu (nếu chưa load)
df_final = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df_final.index = pd.to_datetime(df_final.index)

# Lọc các cột thuộc nhóm Y (hậu tố _y)
group_y_cols = [col for col in df_final.columns if col != 'Total' and col.endswith('_y')]
forecast_periods = 6

results_y = {}
for col in group_y_cols:
    series = df_final[col]
    if len(series) < forecast_periods + 1:
        continue
    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]
    try:
        # Với dữ liệu có seasonality, dùng mô hình Holt-Winters với seasonal 'add' (giả sử chu kỳ 12 tháng)
        model = ExponentialSmoothing(train, trend='add', seasonal=None, seasonal_periods=12, damped_trend=True).fit()
        forecast = model.forecast(forecast_periods)
    except Exception as e:
        forecast = pd.Series([np.nan] * forecast_periods, index=test.index)
    results_y[col] = {"train": train, "test": test, "forecast": forecast}

# Tính wMAPE cho nhóm Y
total_abs_error = 0
total_actual = 0
for res in results_y.values():
    forecast_arr = res["forecast"].values
    test_arr = res["test"].values
    total_abs_error += np.sum(np.abs(forecast_arr - test_arr))
    total_actual += np.sum(test_arr)
wmape_y = total_abs_error / total_actual if total_actual != 0 else np.nan
print("Group Y - wMAPE: {:.2%}".format(wmape_y))

Group Y - wMAPE: 60.26%

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
import warnings

warnings.filterwarnings("ignore")

# Load dữ liệu
df_final = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df_final.index = pd.to_datetime(df_final.index)

# Lọc các cột thuộc nhóm Y (tên kết thúc bằng _y)
group_y_cols = [col for col in df_final.columns if col != 'Total' and col.endswith('_y')]
forecast_periods = 6
wmape_threshold = 30  # Yêu cầu: wMAPE < 30%

series_results = []
overall_total_abs_error = 0.0
overall_total_actual = 0.0

trend_threshold = 0.05  # Ngưỡng xác định xu hướng

# Các cấu hình ARIMA non-seasonal cần thử
non_seasonal_orders = [(1,1,0), (0,1,1), (1,1,1), (2,1,1)]
# Các cấu hình SARIMA cần thử (non-seasonal_order, seasonal_order)
seasonal_orders = [((1,1,0), (1,0,1,12)), ((0,1,1), (1,0,1,12))]

for col in group_y_cols:
    series = df_final[col].dropna()
    if len(series) < forecast_periods + 1:
        continue

    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]
    test_arr = np.array(test)

    # Tính xu hướng: so sánh giá trị đầu và cuối của train
    initial = train.iloc[0]
    final = train.iloc[-1]
    trend_ratio = abs(final - initial) / (abs(initial) + 1e-8)

    candidate_models = []

    # Thử các mô hình ES
    if trend_ratio > trend_threshold:
        try:
            model_add = ExponentialSmoothing(train, trend='add', seasonal=None, damped_trend=True).fit()
            forecast_add = model_add.forecast(forecast_periods)
            candidate_models.append(("Holt's Add", model_add, np.array(forecast_add)))
        except:
            pass
        if (train > 0).all():
            try:
                model_mult = ExponentialSmoothing(train, trend='mul', seasonal=None, damped_trend=True).fit()
                forecast_mult = model_mult.forecast(forecast_periods)
                candidate_models.append(("Holt's Mul", model_mult, np.array(forecast_mult)))
            except:
                pass
    else:
        try:
            model_simple = ExponentialSmoothing(train, trend=None, seasonal=None).fit()
            forecast_simple = model_simple.forecast(forecast_periods)
            candidate_models.append(("Simple ES", model_simple, np.array(forecast_simple)))
        except:
            pass

    # Chọn mô hình ES tốt nhất dựa trên tổng lỗi
    best_model_name = None
    best_error = np.inf
    best_forecast = None
    for name, model, forecast_arr in candidate_models:
        if np.sum(test_arr) == 0:
            continue
        error = np.sum(np.abs(forecast_arr - test_arr))
        if error < best_error:
            best_error = error
            best_forecast = forecast_arr
            best_model_name = name
    current_wmape = best_error / np.sum(test_arr) * 100 if np.sum(test_arr) > 0 else np.inf

    # Nếu wMAPE từ ES >= threshold, thử ARIMA grid search
    if current_wmape >= wmape_threshold:
        # Thử ARIMA non-seasonal
        for order in non_seasonal_orders:
            try:
                model_arima = ARIMA(train, order=order).fit()
                forecast_arima = model_arima.forecast(forecast_periods)
                forecast_arima = np.array(forecast_arima)
                error_arima = np.sum(np.abs(forecast_arima - test_arr))
                wmape_arima = error_arima / np.sum(test_arr) * 100
                if wmape_arima < current_wmape:
                    best_model_name = f"ARIMA{order}"
                    best_error = error_arima
                    best_forecast = forecast_arima
                    current_wmape = wmape_arima
            except:
                continue

        # Thử SARIMA nếu độ dài train đủ (> seasonal_period)
        seasonal_period = 12
        if len(train) > seasonal_period:
            for non_seasonal_order, seasonal_order in seasonal_orders:
                try:
                    model_sarima = SARIMAX(train, order=non_seasonal_order, seasonal_order=seasonal_order).fit(disp=False)
                    forecast_sarima = model_sarima.forecast(forecast_periods)
                    forecast_sarima = np.array(forecast_sarima)
                    error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                    wmape_sarima = error_sarima / np.sum(test_arr) * 100
                    if wmape_sarima < current_wmape:
                        best_model_name = f"SARIMA{non_seasonal_order, seasonal_order}"
                        best_error = error_sarima
                        best_forecast = forecast_sarima
                        current_wmape = wmape_sarima
                except:
                    continue

    if np.sum(test_arr) == 0:
        continue

    status = "Valid" if current_wmape < wmape_threshold else "Invalid: wMAPE too high"

    if status == "Valid":
        overall_total_abs_error += best_error
        overall_total_actual += np.sum(test_arr)

    series_results.append({
        "Series": col,
        "Model": best_model_name,
        "wMAPE": current_wmape,
        "Status": status
    })

overall_wmape = overall_total_abs_error / overall_total_actual * 100 if overall_total_actual != 0 else np.nan

df_results = pd.DataFrame(series_results)
df_results_valid = df_results[df_results["Status"] == "Valid"]

# Hiển thị số lượng series hợp lệ
# Tạo summary cho nhóm Y
summary_y = {
    "Group": "Y (0.34 ≤ CV < 0.84)",
    "Total Series": len(group_y_cols),
    "Valid Series": df_results_valid.shape[0],
    "Invalid Series": df_results[df_results["Status"] != "Valid"].shape[0],
    "Overall wMAPE": f"{overall_wmape:.2f}%" if pd.notnull(overall_wmape) else "NaN"
}
df_summary_y = pd.DataFrame([summary_y])

# In kết quả từng series trong nhóm Y
print("=== Group Y - Individual Series Results (With Extended ARIMA/SARIMA Grid Search) ===")
print(df_results[["Series", "Model", "wMAPE", "Status"]])

# In summary của nhóm Y
print("\n=== Group Y - Summary (Valid series: wMAPE < 30%) ===")
print(df_summary_y)

=== Group Y - Individual Series Results (With Extended ARIMA/SARIMA Grid Search) ===
           Series                             Model       wMAPE  \
0    A2000094_a_y                        Holt's Add   28.099245
1    A2000110_a_y                    ARIMA(1, 1, 1)   21.195140
2    A2000125_a_y  SARIMA((1, 1, 0), (1, 0, 1, 12))   40.347075
3    A2000130_a_y  SARIMA((0, 1, 1), (1, 0, 1, 12))   32.925142
4    A2000133_a_y                        Holt's Mul   27.730483
..            ...                               ...         ...
437  A8010373_b_y  SARIMA((0, 1, 1), (1, 0, 1, 12))   39.096179
438  A8010375_c_y  SARIMA((1, 1, 0), (1, 0, 1, 12))   46.003174
439      B010_a_y                    ARIMA(2, 1, 1)   39.832553
440      T800_a_y                    ARIMA(2, 1, 1)   82.293595
441  T800-124_a_y                        Holt's Mul  157.838934

                      Status
0                      Valid
1                      Valid
2    Invalid: wMAPE too high
3    Invalid: wMAPE too high
4                      Valid
..                       ...
437  Invalid: wMAPE too high
438  Invalid: wMAPE too high
439  Invalid: wMAPE too high
440  Invalid: wMAPE too high
441  Invalid: wMAPE too high

[442 rows x 4 columns]

=== Group Y - Summary (Valid series: wMAPE < 30%) ===
                  Group  Total Series  Valid Series  Invalid Series  \
0  Y (0.34 ≤ CV < 0.84)           442            91             351

  Overall wMAPE
0        23.60%

### Fine-tuning 1st time

In [ ]:
import numpy as np
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from pandas.tseries.holiday import USFederalHolidayCalendar
import warnings

warnings.filterwarnings("ignore")

df_final = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df_final.index = pd.to_datetime(df_final.index)



if df_final is not None:
    # Lọc các cột thuộc nhóm Y (hậu tố _y)
    group_y_cols = [col for col in df_final.columns if col != 'Total' and col.endswith('_y')]
    forecast_periods = 6
    wmape_threshold = 30  # Mục tiêu: cải thiện series có WMAPE < 30%

    # **Thêm holiday feature**
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=df_final.index.min(), end=df_final.index.max())
    df_final["Holiday"] = df_final.index.isin(holidays).astype(int)

    fine_tuned_results = []

    print(f"🔄 Bắt đầu Fine-Tuning {len(group_y_cols)} series nhóm Y với holiday feature...")

    for col in group_y_cols:
        series = df_final[col].dropna()
        if len(series) < forecast_periods + 1:
            continue

        train = series.iloc[:-forecast_periods]
        test = series.iloc[-forecast_periods:]
        test_arr = np.array(test)

        train_holiday = df_final["Holiday"].iloc[:-forecast_periods]
        test_holiday = df_final["Holiday"].iloc[-forecast_periods:]

        # 🔹 Fine-tune Holt-Winters với nhiều thông số
        best_wmape = np.inf
        best_model = None
        best_forecast = None
        best_params = None

        hw_configs = [
            ("add", "add"), ("add", "mul"), ("mul", "add"), ("mul", "mul")
        ]

        for trend, seasonal in hw_configs:
            try:
                model_hw = ExponentialSmoothing(
                    train, trend=trend, seasonal=seasonal,
                    seasonal_periods=12, damped_trend=True
                ).fit()
                forecast_hw = model_hw.forecast(forecast_periods)
                error_hw = np.sum(np.abs(forecast_hw - test_arr))
                wmape_hw = error_hw / np.sum(test_arr) * 100 if np.sum(test_arr) > 0 else np.inf

                if wmape_hw < best_wmape:
                    best_wmape = wmape_hw
                    best_model = model_hw
                    best_forecast = forecast_hw
                    best_params = f"Holt-Winters({trend}, {seasonal})"
            except:
                continue

        # 🔹 Fine-tune ARIMA nếu Holt-Winters chưa tốt
        if best_wmape >= wmape_threshold:
            arima_orders = [(1,1,0), (0,1,1), (1,1,1), (2,1,1)]
            for order in arima_orders:
                try:
                    model_arima = ARIMA(train, order=order).fit()
                    forecast_arima = model_arima.forecast(forecast_periods)
                    error_arima = np.sum(np.abs(forecast_arima - test_arr))
                    wmape_arima = error_arima / np.sum(test_arr) * 100

                    if wmape_arima < best_wmape:
                        best_wmape = wmape_arima
                        best_model = model_arima
                        best_forecast = forecast_arima
                        best_params = f"ARIMA{order}"
                except:
                    continue

        # 🔹 Fine-tune SARIMA nếu ARIMA chưa tốt
        if best_wmape >= wmape_threshold:
            sarima_orders = [((1,1,0), (1,0,1,12)), ((0,1,1), (1,0,1,12))]
            for non_seasonal, seasonal in sarima_orders:
                try:
                    model_sarima = SARIMAX(train, order=non_seasonal, seasonal_order=seasonal).fit(disp=False)
                    forecast_sarima = model_sarima.forecast(forecast_periods)
                    error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                    wmape_sarima = error_sarima / np.sum(test_arr) * 100

                    if wmape_sarima < best_wmape:
                        best_wmape = wmape_sarima
                        best_model = model_sarima
                        best_forecast = forecast_sarima
                        best_params = f"SARIMA{non_seasonal, seasonal}"
                except:
                    continue

        # 🔹 Lưu kết quả fine-tuning
        fine_tuned_results.append({
            "Series": col,
            "Best Model": best_params,
            "New WMAPE": best_wmape,
            "Status": "Improved" if best_wmape < wmape_threshold else "Not Improved"
        })

    # **Hiển thị kết quả fine-tuning**
    df_fine_tuned = pd.DataFrame(fine_tuned_results)
    print("\n=== Fine-Tuning Results (All Y-Series with Holiday Feature & Optimized Models) ===")
    print(df_fine_tuned.to_string(index=False))

    # Hiển thị số lượng series cải thiện được
    num_improved = df_fine_tuned[df_fine_tuned["Status"] == "Improved"].shape[0]
    print(f"\n✅ Số series được cải thiện sau fine-tuning: {num_improved}/{len(group_y_cols)}")

🔄 Bắt đầu Fine-Tuning 442 series nhóm Y với holiday feature...

=== Fine-Tuning Results (All Y-Series with Holiday Feature & Optimized Models) ===
       Series                       Best Model  New WMAPE       Status
 A2000094_a_y           Holt-Winters(add, mul)  28.792905     Improved
 A2000110_a_y                   ARIMA(1, 1, 1)  21.195140     Improved
 A2000125_a_y           Holt-Winters(add, add)  34.577791 Not Improved
 A2000130_a_y           Holt-Winters(add, add)  23.559750     Improved
 A2000133_a_y           Holt-Winters(mul, add)  26.528556     Improved
 A2000135_a_y SARIMA((1, 1, 0), (1, 0, 1, 12))  49.357693 Not Improved
 A2000136_a_y                   ARIMA(1, 1, 1)  85.328354 Not Improved
 A2000249_a_y                   ARIMA(0, 1, 1)  27.628362     Improved
 A2000329_a_y           Holt-Winters(mul, mul)  41.730152 Not Improved
 A2000346_a_y                   ARIMA(1, 1, 0)  64.366619 Not Improved
 A2000348_a_y           Holt-Winters(add, mul)  18.791719     Improved
 A2000355_a_y           Holt-Winters(mul, mul)  30.083275 Not Improved
 A2000370_a_y           Holt-Winters(add, mul)  33.292729 Not Improved
 A2000388_a_y           Holt-Winters(mul, add)  53.482288 Not Improved
 A2000407_a_y SARIMA((0, 1, 1), (1, 0, 1, 12))  61.714118 Not Improved
 A2000409_b_y           Holt-Winters(add, mul) 116.538619 Not Improved
 A2000410_a_y           Holt-Winters(add, mul)  63.955869 Not Improved
 A2000416_a_y           Holt-Winters(add, mul)  31.224337 Not Improved
 A2000427_a_y           Holt-Winters(add, add)  19.677173     Improved
 A2000442_a_y                   ARIMA(1, 1, 0)  38.560000 Not Improved
 A2000455_a_y           Holt-Winters(add, add)  25.237664     Improved
 A2000460_a_y           Holt-Winters(add, mul)  25.790572     Improved
 A2000461_a_y SARIMA((1, 1, 0), (1, 0, 1, 12))  33.298352 Not Improved
 A2000463_a_y                   ARIMA(1, 1, 0)  26.387422     Improved
 A2000484_b_y SARIMA((1, 1, 0), (1, 0, 1, 12))  34.488272 Not Improved
 A2000485_a_y           Holt-Winters(add, mul)  32.085598 Not Improved
 A2000486_a_y           Holt-Winters(add, add)  14.480379     Improved
 A2000488_a_y                   ARIMA(1, 1, 1)  30.593919 Not Improved
 A2000489_a_y                   ARIMA(1, 1, 0)  15.592385     Improved
 A2000490_b_y                   ARIMA(1, 1, 0)  50.457800 Not Improved
 A2000491_b_y SARIMA((1, 1, 0), (1, 0, 1, 12))  42.335208 Not Improved
 A2000494_b_y           Holt-Winters(add, mul)  52.924251 Not Improved
 A2000495_b_y                   ARIMA(2, 1, 1)  68.085008 Not Improved
 A2000497_b_y                   ARIMA(1, 1, 0)  38.649334 Not Improved
 A2000498_b_y                   ARIMA(1, 1, 0)  17.710467     Improved
 A2000501_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  24.440516     Improved
 A2000502_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  26.429070     Improved
 A2000506_b_y SARIMA((1, 1, 0), (1, 0, 1, 12)) 104.686813 Not Improved
 A2000507_b_y                   ARIMA(1, 1, 0)  22.386421     Improved
 A2000508_b_y                   ARIMA(1, 1, 0)  23.225896     Improved
 A2000509_a_y           Holt-Winters(add, add)  35.730811 Not Improved
 A2000510_a_y           Holt-Winters(add, mul)  40.248301 Not Improved
 A2000511_a_y                   ARIMA(0, 1, 1)  29.404762     Improved
 A2000512_a_y                   ARIMA(0, 1, 1)  35.366377 Not Improved
 A2000513_a_y           Holt-Winters(add, add)  17.870716     Improved
 A2000514_a_y           Holt-Winters(add, add)  27.924029     Improved
 A2000515_a_y                   ARIMA(1, 1, 0)  40.365400 Not Improved
 A2000516_a_y SARIMA((0, 1, 1), (1, 0, 1, 12))  38.839387 Not Improved
 A2000517_a_y                   ARIMA(1, 1, 0)  42.688766 Not Improved
 A2000518_a_y                   ARIMA(1, 1, 0)  35.733811 Not Improved
 A2000519_a_y                   ARIMA(1, 1, 0)  32.064349 Not Improved
 A2000527_b_y SARIMA((1, 1, 0), (1, 0, 1, 12))  66.880140 Not Improved
 A2000528_c_y                   ARIMA(2, 1, 1) 220.692678 Not Improved
 A2000529_c_y           Holt-Winters(add, mul)  87.969437 Not Improved
 A2000534_c_y           Holt-Winters(mul, add) 107.736892 Not Improved
 A2000535_c_y           Holt-Winters(add, mul)  66.421208 Not Improved
 A2000539_a_y                   ARIMA(0, 1, 1)  42.903764 Not Improved
 A2000540_a_y           Holt-Winters(add, add)  50.193021 Not Improved
 A2000548_b_y           Holt-Winters(add, mul)  37.659584 Not Improved
 A2000550_c_y                   ARIMA(1, 1, 0)  59.186225 Not Improved
 A2000553_a_y                   ARIMA(1, 1, 0)  35.744419 Not Improved
 A2000554_a_y                   ARIMA(1, 1, 0)  30.260013 Not Improved
 A2000555_b_y                   ARIMA(1, 1, 0) 410.374878 Not Improved
 A2000561_a_y                   ARIMA(1, 1, 0)  69.057218 Not Improved
 A2000562_a_y                   ARIMA(1, 1, 0)  41.539764 Not Improved
 A2000566_b_y                   ARIMA(1, 1, 0)  38.892378 Not Improved
 A2000567_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  36.539909 Not Improved
 A2000568_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  41.062805 Not Improved
 A2000572_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  56.006396 Not Improved
 A2000575_b_y SARIMA((0, 1, 1), (1, 0, 1, 12))  21.244563     Improved
 A2000576_b_y SARIMA((0, 1, 1), (1, 0, 1, 12))  52.078171 Not Improved
 A2000584_c_y                   ARIMA(1, 1, 1)  39.474970 Not Improved
 A2000591_b_y                   ARIMA(1, 1, 1)  28.374095     Improved
 A2000594_a_y                   ARIMA(1, 1, 1)  29.358066     Improved
 A2000595_c_y                   ARIMA(0, 1, 1)  53.892092 Not Improved
 A2000596_b_y                   ARIMA(1, 1, 0)  42.303847 Not Improved
 A2000609_b_y                   ARIMA(1, 1, 1) 117.252708 Not Improved
 A2000610_b_y                   ARIMA(2, 1, 1) 109.040768 Not Improved
 A2000611_b_y                   ARIMA(2, 1, 1)  61.878010 Not Improved
 A2000614_c_y                   ARIMA(2, 1, 1)  35.402977 Not Improved
 A2000617_b_y                   ARIMA(0, 1, 1)  88.360232 Not Improved
 A2000618_b_y SARIMA((1, 1, 0), (1, 0, 1, 12))  71.296554 Not Improved
 A2000623_b_y           Holt-Winters(add, add)  28.348856     Improved
 A2000628_a_y           Holt-Winters(add, add)  48.485362 Not Improved
 A2000629_a_y                   ARIMA(2, 1, 1)  41.176320 Not Improved
 A2000630_b_y           Holt-Winters(add, add)  26.643672     Improved
 A2000631_b_y                   ARIMA(1, 1, 1)  41.744991 Not Improved
 A2000632_b_y                   ARIMA(0, 1, 1)  22.184642     Improved
 A2000635_b_y           Holt-Winters(add, add)  43.974209 Not Improved
 A2000636_b_y SARIMA((0, 1, 1), (1, 0, 1, 12))  41.158247 Not Improved
 A2000646_c_y                   ARIMA(2, 1, 1)  28.416317     Improved
 A2000647_c_y                   ARIMA(2, 1, 1)  27.267494     Improved
 A2000648_c_y                   ARIMA(0, 1, 1)  26.405868     Improved
 A2000649_a_y           Holt-Winters(add, add)  40.120211 Not Improved
 A2000650_a_y                   ARIMA(1, 1, 1)  44.891537 Not Improved
 A2000652_b_y                   ARIMA(2, 1, 1)  37.945597 Not Improved
 A2000653_c_y           Holt-Winters(add, add)  18.829660     Improved
 A2000655_c_y                   ARIMA(0, 1, 1)  40.350877 Not Improved
 A2000657_c_y                   ARIMA(0, 1, 1)  59.443745 Not Improved
 A2000658_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  60.460963 Not Improved
 A2000660_c_y                   ARIMA(1, 1, 1)  50.721111 Not Improved
 A2000661_c_y                   ARIMA(2, 1, 1)  56.806655 Not Improved
 A2000663_c_y                   ARIMA(1, 1, 0)  51.300282 Not Improved
 A2000664_c_y                   ARIMA(2, 1, 1)  51.105875 Not Improved
 A2000670_c_y                   ARIMA(1, 1, 0)  41.396408 Not Improved
 A2000673_c_y                   ARIMA(1, 1, 1)  54.046957 Not Improved
 A2000674_c_y                   ARIMA(1, 1, 1)  53.139119 Not Improved
 A2000679_c_y           Holt-Winters(add, add)  51.284309 Not Improved
 A2000683_c_y                   ARIMA(1, 1, 1)  65.504564 Not Improved
 A2000690_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  77.496676 Not Improved
 A2000691_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  73.551528 Not Improved
 A2000692_c_y                   ARIMA(0, 1, 1)  50.249658 Not Improved
 A2000693_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  36.557241 Not Improved
 A2000695_c_y                   ARIMA(0, 1, 1)  47.058630 Not Improved
 A2000701_c_y                   ARIMA(1, 1, 0)  39.309247 Not Improved
 A2000702_c_y                   ARIMA(1, 1, 0)  41.654164 Not Improved
 A2000703_c_y                   ARIMA(1, 1, 0)  44.290262 Not Improved
 A2000704_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  41.538677 Not Improved
 A2000705_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  41.695592 Not Improved
 A2900003_c_y                   ARIMA(2, 1, 1) 126.385727 Not Improved
 A2900004_c_y                   ARIMA(2, 1, 1)  93.304640 Not Improved
 A2900005_c_y                   ARIMA(1, 1, 0)  31.696085 Not Improved
 A2900006_c_y                   ARIMA(1, 1, 0)  25.539522     Improved
 A2900008_b_y                   ARIMA(1, 1, 1)  21.100104     Improved
 A2900010_c_y                   ARIMA(1, 1, 0)  42.540839 Not Improved
 A2900011_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  45.783340 Not Improved
 A2900012_b_y           Holt-Winters(add, add)  27.604929     Improved
 A2900013_b_y           Holt-Winters(add, add)  61.468232 Not Improved
 A2900017_b_y                   ARIMA(2, 1, 1)  43.508568 Not Improved
 A2900021_c_y                   ARIMA(2, 1, 1) 100.622335 Not Improved
 A2900022_c_y                   ARIMA(2, 1, 1)  38.401774 Not Improved
 A2900023_c_y                   ARIMA(2, 1, 1)  18.916242     Improved
 A2C00204_c_y                   ARIMA(1, 1, 0)  53.830956 Not Improved
 A3000002_a_y           Holt-Winters(add, add)  10.504252     Improved
 A3000030_a_y                   ARIMA(1, 1, 0) 117.564567 Not Improved
 A3000051_a_y           Holt-Winters(mul, mul)  25.265799     Improved
 A3000053_a_y           Holt-Winters(add, add)  22.078931     Improved
 A3000054_b_y                   ARIMA(2, 1, 1)  42.018525 Not Improved
 A3000063_a_y SARIMA((0, 1, 1), (1, 0, 1, 12))  77.047278 Not Improved
 A3000081_a_y SARIMA((1, 1, 0), (1, 0, 1, 12))  27.601933     Improved
 A3000103_c_y                   ARIMA(1, 1, 1)  29.646562     Improved
 A3000106_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  26.150790     Improved
 A3000135_a_y                   ARIMA(2, 1, 1) 265.452247 Not Improved
 A3000140_a_y SARIMA((1, 1, 0), (1, 0, 1, 12))  83.629841 Not Improved
 A3000174_a_y SARIMA((0, 1, 1), (1, 0, 1, 12)) 109.049568 Not Improved
 A3000196_a_y           Holt-Winters(add, mul)  19.528823     Improved
 A3000208_b_y                   ARIMA(2, 1, 1)  10.021865     Improved
 A3000213_a_y                   ARIMA(2, 1, 1)  34.101048 Not Improved
 A3000241_a_y                   ARIMA(2, 1, 1)  93.955356 Not Improved
 A3000259_a_y           Holt-Winters(add, add)  55.389853 Not Improved
 A3000261_b_y                   ARIMA(1, 1, 0)  56.762649 Not Improved
 A3000278_b_y SARIMA((0, 1, 1), (1, 0, 1, 12))  79.632247 Not Improved
 A3000281_a_y           Holt-Winters(add, mul)  22.062464     Improved
 A3000282_b_y                   ARIMA(1, 1, 0)  27.667990     Improved
 A3000284_b_y           Holt-Winters(add, add)  28.417012     Improved
 A3000308_a_y                   ARIMA(2, 1, 1)  70.145154 Not Improved
 A3000325_a_y           Holt-Winters(add, add)  23.472334     Improved
 A3000326_a_y           Holt-Winters(mul, add)   0.000000     Improved
 A3000330_b_y                   ARIMA(0, 1, 1)  31.807133 Not Improved
 A3000335_b_y                   ARIMA(1, 1, 0)  39.381671 Not Improved
 A3000336_a_y SARIMA((1, 1, 0), (1, 0, 1, 12))  47.332836 Not Improved
 A3000337_a_y                   ARIMA(2, 1, 1)  67.032609 Not Improved
 A3000338_a_y                   ARIMA(1, 1, 0) 295.834582 Not Improved
 A3000339_a_y                   ARIMA(1, 1, 1)  35.196045 Not Improved
 A3000343_a_y           Holt-Winters(add, mul) 184.301363 Not Improved
A3000366C_c_y                   ARIMA(0, 1, 1) 102.964278 Not Improved
 A3000604_a_y SARIMA((1, 1, 0), (1, 0, 1, 12))  58.634206 Not Improved
 A3000608_c_y                   ARIMA(1, 1, 1)  22.690477     Improved
 A3000609_c_y           Holt-Winters(add, mul)  57.181065 Not Improved
 A3000610_c_y           Holt-Winters(add, mul)  78.874094 Not Improved
 A3000617_c_y           Holt-Winters(add, add)  65.547819 Not Improved
 A3000619_c_y           Holt-Winters(add, mul)  44.717806 Not Improved
 A3000623_c_y           Holt-Winters(add, add)  40.546895 Not Improved
 A3000629_a_y                   ARIMA(0, 1, 1)  51.845250 Not Improved
 A3000631_b_y                   ARIMA(1, 1, 1)  80.008656 Not Improved
 A3000632_c_y                   ARIMA(1, 1, 0)  27.645836     Improved
 A3000638_a_y                   ARIMA(2, 1, 1)  26.703265     Improved
 A3000644_a_y           Holt-Winters(add, add)  21.904735     Improved
 A3000646_a_y                   ARIMA(1, 1, 1)  24.495948     Improved
 A3000647_c_y                   ARIMA(2, 1, 1)  82.743719 Not Improved
 A3000649_c_y           Holt-Winters(add, add)  14.238717     Improved
 A3000650_c_y                   ARIMA(2, 1, 1)  20.228778     Improved
 A3000656_c_y                   ARIMA(2, 1, 1)  44.330989 Not Improved
 A3000658_b_y                   ARIMA(2, 1, 1)  29.176130     Improved
 A3000661_c_y           Holt-Winters(add, add)  32.963481 Not Improved
 A3000662_a_y           Holt-Winters(add, add)  32.654747 Not Improved
 A3000668_a_y                   ARIMA(2, 1, 1)  38.569398 Not Improved
 A3000670_a_y                   ARIMA(2, 1, 1)  31.916105 Not Improved
 A3000673_c_y                   ARIMA(2, 1, 1)  57.648863 Not Improved
 A3000678_a_y                   ARIMA(2, 1, 1)  26.382882     Improved
 A3000682_c_y                   ARIMA(2, 1, 1)  48.172913 Not Improved
 A3000683_a_y           Holt-Winters(add, add)  41.612960 Not Improved
 A3000693_c_y                   ARIMA(2, 1, 1)  38.578527 Not Improved
 A3000699_c_y                   ARIMA(0, 1, 1)  45.454545 Not Improved
 A3000726_c_y                   ARIMA(1, 1, 0)  37.277177 Not Improved
 A4000001_a_y           Holt-Winters(add, add) 193.252891 Not Improved
 A4000032_a_y                   ARIMA(1, 1, 0) 181.929106 Not Improved
 A4000039_a_y           Holt-Winters(mul, mul)  37.324934 Not Improved
 A4000047_a_y           Holt-Winters(mul, mul)  87.243171 Not Improved
 A4000049_a_y                   ARIMA(0, 1, 1)  18.546591     Improved
 A4000077_a_y           Holt-Winters(add, mul)  63.372933 Not Improved
 A4000081_a_y                   ARIMA(2, 1, 1)  63.975231 Not Improved
 A4000089_a_y SARIMA((0, 1, 1), (1, 0, 1, 12))  70.749091 Not Improved
 A4000091_a_y SARIMA((1, 1, 0), (1, 0, 1, 12))  41.019212 Not Improved
 A4000096_a_y           Holt-Winters(add, mul)  79.856198 Not Improved
 A4000099_c_y                   ARIMA(2, 1, 1)  36.034685 Not Improved
 A4000178_a_y           Holt-Winters(add, mul) 217.390972 Not Improved
 A4000189_a_y                   ARIMA(1, 1, 0) 126.269833 Not Improved
 A4000209_a_y                   ARIMA(1, 1, 1)  39.233310 Not Improved
 A4000250_a_y SARIMA((0, 1, 1), (1, 0, 1, 12)) 174.019049 Not Improved
 A4000260_a_y                   ARIMA(1, 1, 0) 248.252629 Not Improved
 A4000263_a_y                   ARIMA(2, 1, 1) 113.012322 Not Improved
 A4000267_a_y           Holt-Winters(mul, add)   0.000000     Improved
 A4000298_b_y           Holt-Winters(mul, mul)  56.066472 Not Improved
 A4000308_a_y           Holt-Winters(mul, add)  16.840786     Improved
 A4000309_a_y                   ARIMA(2, 1, 1)  83.556474 Not Improved
 A4000311_a_y           Holt-Winters(mul, add)  42.113533 Not Improved
 A4000323_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  49.057792 Not Improved
 A4000334_c_y                   ARIMA(0, 1, 1)  30.840771 Not Improved
 A4000335_c_y                   ARIMA(1, 1, 1)  36.232741 Not Improved
 A4000337_c_y           Holt-Winters(add, mul)  71.219169 Not Improved
 A4000338_c_y                   ARIMA(0, 1, 1)  30.805113 Not Improved
 A4000353_c_y                   ARIMA(2, 1, 1)  22.574799     Improved
 A4000371_b_y                   ARIMA(2, 1, 1)  96.151129 Not Improved
 A4000379_c_y           Holt-Winters(add, mul)  79.788041 Not Improved
 A4000382_c_y                   ARIMA(0, 1, 1)  42.235926 Not Improved
 A4000383_c_y           Holt-Winters(mul, add)   0.000000     Improved
 A4000389_c_y                   ARIMA(0, 1, 1)  27.972874     Improved
 A4000392_c_y                   ARIMA(1, 1, 0)  31.224279 Not Improved
 A4000393_c_y                   ARIMA(1, 1, 0)  31.374874 Not Improved
 A4000394_c_y                   ARIMA(1, 1, 0)  41.935484 Not Improved
 A4000396_c_y                   ARIMA(2, 1, 1)  59.397000 Not Improved
 A4000399_c_y                   ARIMA(2, 1, 1)  33.493356 Not Improved
 A4000400_a_y                   ARIMA(1, 1, 0)  16.903236     Improved
 A4000411_a_y           Holt-Winters(add, mul)  65.432318 Not Improved
 A4000430_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  48.897546 Not Improved
 A4000441_a_y                   ARIMA(0, 1, 1)  39.753972 Not Improved
 A4000451_b_y                   ARIMA(0, 1, 1)  58.119658 Not Improved
 A4000453_b_y SARIMA((1, 1, 0), (1, 0, 1, 12))  54.740836 Not Improved
 A4000461_b_y                   ARIMA(0, 1, 1)  29.632274     Improved
 A4000462_a_y           Holt-Winters(mul, mul)  53.110934 Not Improved
 A4000463_b_y SARIMA((1, 1, 0), (1, 0, 1, 12))  70.049145 Not Improved
 A4000473_b_y                   ARIMA(1, 1, 0)  57.023958 Not Improved
 A4000502_c_y                   ARIMA(1, 1, 0)  37.442414 Not Improved
 A4000506_c_y SARIMA((0, 1, 1), (1, 0, 1, 12))  70.438302 Not Improved
 A4000509_a_y                   ARIMA(1, 1, 0)  49.983767 Not Improved
 A4000511_a_y           Holt-Winters(add, mul)  57.101352 Not Improved
 A4000512_c_y                   ARIMA(1, 1, 0)  27.476167     Improved
 A4000514_a_y           Holt-Winters(mul, mul)  51.896974 Not Improved
 A4000516_c_y           Holt-Winters(add, mul) 227.171270 Not Improved
 A4000523_c_y           Holt-Winters(mul, mul)  40.420279 Not Improved
 A4000527_b_y           Holt-Winters(add, mul)  86.963315 Not Improved
 A4000529_a_y                   ARIMA(1, 1, 1) 373.425012 Not Improved
 A4000530_b_y                   ARIMA(2, 1, 1)  97.069543 Not Improved
 A4000531_c_y           Holt-Winters(add, add)  57.887565 Not Improved
 A4000532_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  30.223858 Not Improved
 A4000534_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  35.782279 Not Improved
 A4000535_c_y                   ARIMA(1, 1, 1)  56.577490 Not Improved
 A4000540_a_y SARIMA((0, 1, 1), (1, 0, 1, 12))  53.700771 Not Improved
 A4000543_b_y                   ARIMA(2, 1, 1)  53.311500 Not Improved
 A4000548_c_y SARIMA((1, 1, 0), (1, 0, 1, 12))  31.647380 Not Improved
 A4000550_a_y                   ARIMA(1, 1, 0)  35.638501 Not Improved
 A4000559_c_y                   ARIMA(2, 1, 1)  45.493235 Not Improved
 A4000561_c_y                   ARIMA(0, 1, 1)  42.146379 Not Improved
 A4000570_c_y                   ARIMA(0, 1, 1)  26.087779     Improved
 A4000571_a_y           Holt-Winters(add, add)  17.093569     Improved
 A4000573_c_y                   ARIMA(1, 1, 0)  23.488601     Improved
 A4000574_c_y           Holt-Winters(add, add)  27.026515     Improved
 A4000575_b_y           Holt-Winters(add, add)  44.665076 Not Improved
 A4000577_c_y           Holt-Winters(add, add)  37.286770 Not Improved
 A4000578_c_y           Holt-Winters(add, add)  44.368878 Not Improved
 A4000581_c_y           Holt-Winters(add, add)  77.747402 Not Improved
 A4000582_c_y           Holt-Winters(add, add)  56.124470 Not Improved
 A4000583_c_y           Holt-Winters(add, add)  33.205092 Not Improved
 A4000586_b_y           Holt-Winters(add, add)  27.509863     Improved
 A4000589_c_y           Holt-Winters(add, add)  44.930378 Not Improved
 A4000593_c_y                   ARIMA(2, 1, 1)  23.428231     Improved
 A4000594_c_y                   ARIMA(0, 1, 1)  55.599881 Not Improved

### Fine-tuning 2nd time

In [ ]:
# 🔄 Fine-tuning lại các series chưa cải thiện bằng phương pháp nâng cao
print("\n🔄 Bắt đầu Fine-Tuning lại các series chưa đạt WMAPE < 30%...")

# **Lọc ra danh sách các series chưa đạt yêu cầu**
df_not_improved = df_fine_tuned[df_fine_tuned["Status"] == "Not Improved"]
series_to_finetune = df_not_improved["Series"].tolist()

# **Lưu kết quả fine-tuning nâng cao**
fine_tuned_results_v2 = []

for col in series_to_finetune:
    series = df_final[col].dropna()
    if len(series) < forecast_periods + 1:
        continue

    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]
    test_arr = np.array(test)

    train_holiday = df_final["Holiday"].iloc[:-forecast_periods]
    test_holiday = df_final["Holiday"].iloc[-forecast_periods:]

    # **🔹 Bổ sung Moving Average để làm trơn dữ liệu**
    train_smooth = train.rolling(window=3, min_periods=1).mean()

    # **🔹 Thử Holt-Winters với thông số mở rộng hơn**
    best_wmape = np.inf
    best_model = None
    best_forecast = None
    best_params = None

    hw_configs = [
        ("add", "add"), ("add", "mul"), ("mul", "add"), ("mul", "mul")
    ]

    for trend, seasonal in hw_configs:
        try:
            model_hw = ExponentialSmoothing(
                train_smooth, trend=trend, seasonal=seasonal,
                seasonal_periods=12, damped_trend=True
            ).fit()
            forecast_hw = model_hw.forecast(forecast_periods)
            error_hw = np.sum(np.abs(forecast_hw - test_arr))
            wmape_hw = error_hw / np.sum(test_arr) * 100 if np.sum(test_arr) > 0 else np.inf

            if wmape_hw < best_wmape:
                best_wmape = wmape_hw
                best_model = model_hw
                best_forecast = forecast_hw
                best_params = f"Holt-Winters({trend}, {seasonal})"
        except:
            continue

    # **🔹 Thử lại ARIMA/SARIMA nếu Holt-Winters chưa tốt**
    if best_wmape >= wmape_threshold:
        arima_orders = [(2,1,2), (1,1,2), (2,1,1), (3,1,2)]
        for order in arima_orders:
            try:
                model_arima = ARIMA(train, order=order).fit()
                forecast_arima = model_arima.forecast(forecast_periods)
                error_arima = np.sum(np.abs(forecast_arima - test_arr))
                wmape_arima = error_arima / np.sum(test_arr) * 100

                if wmape_arima < best_wmape:
                    best_wmape = wmape_arima
                    best_model = model_arima
                    best_forecast = forecast_arima
                    best_params = f"ARIMA{order}"
            except:
                continue

    # **🔹 Thử SARIMA nếu ARIMA chưa tốt**
    if best_wmape >= wmape_threshold:
        sarima_orders = [((2,1,1), (1,0,1,12)), ((1,1,2), (1,0,1,12))]
        for non_seasonal, seasonal in sarima_orders:
            try:
                model_sarima = SARIMAX(train, order=non_seasonal, seasonal_order=seasonal).fit(disp=False)
                forecast_sarima = model_sarima.forecast(forecast_periods)
                error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                wmape_sarima = error_sarima / np.sum(test_arr) * 100

                if wmape_sarima < best_wmape:
                    best_wmape = wmape_sarima
                    best_model = model_sarima
                    best_forecast = forecast_sarima
                    best_params = f"SARIMA{non_seasonal, seasonal}"
            except:
                continue

    # **🔹 Lưu kết quả fine-tuning nâng cao**
    fine_tuned_results_v2.append({
        "Series": col,
        "Best Model": best_params,
        "New WMAPE": best_wmape,
        "Status": "Improved" if best_wmape < wmape_threshold else "Not Improved"
    })

# **Hiển thị kết quả fine-tuning nâng cao**
df_fine_tuned_v2 = pd.DataFrame(fine_tuned_results_v2)
print("\n=== 🔥 Fine-Tuning Lần 2: Cải Thiện Các Series Chưa Đạt ===")
print(df_fine_tuned_v2.to_string(index=False))

# **Tính số lượng series được cải thiện sau fine-tuning lần 2**
num_improved_v2 = df_fine_tuned_v2[df_fine_tuned_v2["Status"] == "Improved"].shape[0]
print(f"\n✅ Số series được cải thiện sau Fine-Tuning lần 2: {num_improved_v2}/{len(series_to_finetune)}")

🔄 Bắt đầu Fine-Tuning lại các series chưa đạt WMAPE < 30%...

=== 🔥 Fine-Tuning Lần 2: Cải Thiện Các Series Chưa Đạt ===
       Series                       Best Model  New WMAPE       Status
 A2000125_a_y           Holt-Winters(mul, add)   0.000000     Improved
 A2000135_a_y           Holt-Winters(add, add)  77.930792 Not Improved
 A2000136_a_y           Holt-Winters(mul, add)  60.792446 Not Improved
 A2000329_a_y           Holt-Winters(add, add)  37.387203 Not Improved
 A2000346_a_y                   ARIMA(2, 1, 2)  64.042950 Not Improved
 A2000355_a_y           Holt-Winters(mul, mul)  55.882914 Not Improved
 A2000370_a_y           Holt-Winters(mul, mul)  46.922697 Not Improved
 A2000388_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  62.098984 Not Improved
 A2000407_a_y           Holt-Winters(mul, add)   0.000000     Improved
 A2000409_b_y           Holt-Winters(add, mul)  95.228778 Not Improved
 A2000410_a_y           Holt-Winters(add, add)  64.774062 Not Improved
 A2000416_a_y           Holt-Winters(add, mul)  40.981255 Not Improved
 A2000442_a_y                   ARIMA(2, 1, 1)  51.626350 Not Improved
 A2000461_a_y           Holt-Winters(mul, add)  33.712375 Not Improved
 A2000484_b_y SARIMA((1, 1, 2), (1, 0, 1, 12))  52.466776 Not Improved
 A2000485_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  36.940824 Not Improved
 A2000488_a_y                   ARIMA(1, 1, 2)  30.559614 Not Improved
 A2000490_b_y                   ARIMA(3, 1, 2) 134.895559 Not Improved
 A2000491_b_y SARIMA((1, 1, 2), (1, 0, 1, 12))  91.606280 Not Improved
 A2000494_b_y           Holt-Winters(add, mul)  51.782129 Not Improved
 A2000495_b_y           Holt-Winters(mul, add)  52.490604 Not Improved
 A2000497_b_y           Holt-Winters(mul, add)  30.508349 Not Improved
 A2000506_b_y                   ARIMA(3, 1, 2) 119.552400 Not Improved
 A2000509_a_y           Holt-Winters(add, add)  37.278253 Not Improved
 A2000510_a_y           Holt-Winters(mul, add)  33.921421 Not Improved
 A2000512_a_y                   ARIMA(1, 1, 2)  49.295938 Not Improved
 A2000515_a_y           Holt-Winters(mul, mul)  42.608908 Not Improved
 A2000516_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  38.741288 Not Improved
 A2000517_a_y           Holt-Winters(mul, mul)  38.861589 Not Improved
 A2000518_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  38.243230 Not Improved
 A2000519_a_y           Holt-Winters(add, mul)  35.119778 Not Improved
 A2000527_b_y           Holt-Winters(add, mul)  60.007743 Not Improved
 A2000528_c_y           Holt-Winters(mul, add)   0.000000     Improved
 A2000529_c_y                   ARIMA(3, 1, 2)  92.527535 Not Improved
 A2000534_c_y           Holt-Winters(mul, mul) 153.392550 Not Improved
 A2000535_c_y           Holt-Winters(mul, mul)  99.467676 Not Improved
 A2000539_a_y                   ARIMA(3, 1, 2)  40.129679 Not Improved
 A2000540_a_y                   ARIMA(2, 1, 1)  56.657569 Not Improved
 A2000548_b_y           Holt-Winters(add, mul) 102.097551 Not Improved
 A2000550_c_y           Holt-Winters(add, mul)  78.396228 Not Improved
 A2000553_a_y           Holt-Winters(mul, mul)  25.098359     Improved
 A2000554_a_y           Holt-Winters(add, add)  34.533446 Not Improved
 A2000555_b_y                   ARIMA(2, 1, 2) 290.358314 Not Improved
 A2000561_a_y                   ARIMA(1, 1, 2)  77.521749 Not Improved
 A2000562_a_y                   ARIMA(2, 1, 2)  37.075872 Not Improved
 A2000566_b_y           Holt-Winters(add, add)  38.091588 Not Improved
 A2000567_c_y           Holt-Winters(add, add)  30.139891 Not Improved
 A2000568_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  49.941419 Not Improved
 A2000572_c_y                   ARIMA(3, 1, 2)  43.090167 Not Improved
 A2000576_b_y SARIMA((1, 1, 2), (1, 0, 1, 12))  54.028301 Not Improved
 A2000584_c_y                   ARIMA(3, 1, 2)  39.619572 Not Improved
 A2000595_c_y                   ARIMA(2, 1, 1)  54.383446 Not Improved
 A2000596_b_y                   ARIMA(2, 1, 2)  42.427441 Not Improved
 A2000609_b_y           Holt-Winters(add, add) 128.790300 Not Improved
 A2000610_b_y           Holt-Winters(add, add)  95.556854 Not Improved
 A2000611_b_y           Holt-Winters(add, add)  42.710427 Not Improved
 A2000614_c_y                   ARIMA(2, 1, 1)  35.402977 Not Improved
 A2000617_b_y           Holt-Winters(add, add)  77.614997 Not Improved
 A2000618_b_y           Holt-Winters(add, add)  52.171125 Not Improved
 A2000628_a_y           Holt-Winters(add, add)  43.726064 Not Improved
 A2000629_a_y           Holt-Winters(add, add)  39.169928 Not Improved
 A2000631_b_y           Holt-Winters(add, add)  27.081678     Improved
 A2000635_b_y           Holt-Winters(add, add)  41.187334 Not Improved
 A2000636_b_y           Holt-Winters(add, add)  36.330106 Not Improved
 A2000649_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  41.560861 Not Improved
 A2000650_a_y                   ARIMA(3, 1, 2)  40.572562 Not Improved
 A2000652_b_y                   ARIMA(2, 1, 1)  37.945597 Not Improved
 A2000655_c_y           Holt-Winters(add, add)  45.362317 Not Improved
 A2000657_c_y                   ARIMA(3, 1, 2)  56.543844 Not Improved
 A2000658_c_y           Holt-Winters(add, add)  56.535483 Not Improved
 A2000660_c_y                   ARIMA(3, 1, 2)  47.313240 Not Improved
 A2000661_c_y                   ARIMA(2, 1, 1)  56.806655 Not Improved
 A2000663_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  50.030879 Not Improved
 A2000664_c_y                   ARIMA(2, 1, 1)  51.105875 Not Improved
 A2000670_c_y                   ARIMA(2, 1, 2)  39.840404 Not Improved
 A2000673_c_y                   ARIMA(3, 1, 2)  48.788780 Not Improved
 A2000674_c_y                   ARIMA(3, 1, 2)  46.132017 Not Improved
 A2000679_c_y                   ARIMA(3, 1, 2)  51.912454 Not Improved
 A2000683_c_y                   ARIMA(3, 1, 2)  62.665663 Not Improved
 A2000690_c_y           Holt-Winters(add, add)  74.149470 Not Improved
 A2000691_c_y                   ARIMA(2, 1, 2)  65.860286 Not Improved
 A2000692_c_y                   ARIMA(3, 1, 2)  48.231839 Not Improved
 A2000693_c_y                   ARIMA(3, 1, 2)  35.189306 Not Improved
 A2000695_c_y                   ARIMA(3, 1, 2)  42.381739 Not Improved
 A2000701_c_y                   ARIMA(2, 1, 2)  44.354343 Not Improved
 A2000702_c_y                   ARIMA(2, 1, 2)  42.297102 Not Improved
 A2000703_c_y                   ARIMA(3, 1, 2)  55.437693 Not Improved
 A2000704_c_y                   ARIMA(2, 1, 2)  46.624666 Not Improved
 A2000705_c_y                   ARIMA(3, 1, 2)  58.734304 Not Improved
 A2900003_c_y                   ARIMA(3, 1, 2)  95.517916 Not Improved
 A2900004_c_y           Holt-Winters(add, add)  75.112474 Not Improved
 A2900005_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  33.265207 Not Improved
 A2900010_c_y                   ARIMA(2, 1, 1)  43.552542 Not Improved
 A2900011_c_y                   ARIMA(3, 1, 2)  46.446016 Not Improved
 A2900013_b_y           Holt-Winters(add, add)  67.228114 Not Improved
 A2900017_b_y                   ARIMA(2, 1, 2)  38.558003 Not Improved
 A2900021_c_y                   ARIMA(2, 1, 2)  91.621085 Not Improved
 A2900022_c_y           Holt-Winters(add, add)  22.760223     Improved
 A2C00204_c_y                   ARIMA(2, 1, 1)  93.042187 Not Improved
 A3000030_a_y                   ARIMA(2, 1, 1) 124.056856 Not Improved
 A3000054_b_y           Holt-Winters(add, mul)  37.474168 Not Improved
 A3000063_a_y           Holt-Winters(add, add)  79.053237 Not Improved
 A3000135_a_y                   ARIMA(2, 1, 2) 261.822063 Not Improved
 A3000140_a_y           Holt-Winters(add, mul)  95.693768 Not Improved
 A3000174_a_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 117.052700 Not Improved
 A3000213_a_y                   ARIMA(2, 1, 1)  34.101048 Not Improved
 A3000241_a_y           Holt-Winters(add, add)  36.790822 Not Improved
 A3000259_a_y           Holt-Winters(mul, mul)  62.576761 Not Improved
 A3000261_b_y           Holt-Winters(add, mul)  35.202561 Not Improved
 A3000278_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  79.939427 Not Improved
 A3000308_a_y                   ARIMA(2, 1, 1)  70.145154 Not Improved
 A3000330_b_y                   ARIMA(2, 1, 1)  36.367223 Not Improved
 A3000335_b_y           Holt-Winters(mul, mul)  42.661936 Not Improved
 A3000336_a_y           Holt-Winters(add, mul)  30.898476 Not Improved
 A3000337_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  65.806111 Not Improved
 A3000338_a_y           Holt-Winters(add, mul) 241.966579 Not Improved
 A3000339_a_y                   ARIMA(3, 1, 2)  30.192974 Not Improved
 A3000343_a_y                   ARIMA(2, 1, 2) 264.853085 Not Improved
A3000366C_c_y                   ARIMA(1, 1, 2)  98.353453 Not Improved
 A3000604_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  55.566534 Not Improved
 A3000609_c_y           Holt-Winters(add, mul)  46.919896 Not Improved
 A3000610_c_y           Holt-Winters(add, add)  63.644596 Not Improved
 A3000617_c_y           Holt-Winters(add, add)  36.570703 Not Improved
 A3000619_c_y                   ARIMA(2, 1, 2)  53.834018 Not Improved
 A3000623_c_y           Holt-Winters(mul, add)  47.863297 Not Improved
 A3000629_a_y                   ARIMA(3, 1, 2)  40.546614 Not Improved
 A3000631_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  79.789409 Not Improved
 A3000647_c_y                   ARIMA(2, 1, 1)  82.743719 Not Improved
 A3000656_c_y           Holt-Winters(add, add)  20.860715     Improved
 A3000661_c_y                   ARIMA(1, 1, 2)  31.039495 Not Improved
 A3000662_a_y                   ARIMA(3, 1, 2)  23.647624     Improved
 A3000668_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  38.229450 Not Improved
 A3000670_a_y                   ARIMA(2, 1, 1)  31.916105 Not Improved
 A3000673_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  57.636251 Not Improved
 A3000682_c_y                   ARIMA(2, 1, 1)  48.172913 Not Improved
 A3000683_a_y                   ARIMA(2, 1, 2)  41.182997 Not Improved
 A3000693_c_y                   ARIMA(2, 1, 1)  38.578527 Not Improved
 A3000699_c_y                   ARIMA(3, 1, 2)  45.586067 Not Improved
 A3000726_c_y           Holt-Winters(add, add)  56.702888 Not Improved
 A4000001_a_y           Holt-Winters(add, add) 144.070795 Not Improved
 A4000032_a_y                   ARIMA(2, 1, 2) 109.161016 Not Improved
 A4000039_a_y                   ARIMA(2, 1, 1)  52.986581 Not Improved
 A4000047_a_y           Holt-Winters(add, mul)  63.335369 Not Improved
 A4000077_a_y           Holt-Winters(mul, mul) 104.032462 Not Improved
 A4000081_a_y                   ARIMA(2, 1, 1)  63.975231 Not Improved
 A4000089_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  67.955687 Not Improved
 A4000091_a_y           Holt-Winters(add, mul)  35.986307 Not Improved
 A4000096_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  88.438968 Not Improved
 A4000099_c_y                   ARIMA(2, 1, 1)  36.034685 Not Improved
 A4000178_a_y           Holt-Winters(add, add) 206.946006 Not Improved
 A4000189_a_y                   ARIMA(1, 1, 2) 260.387424 Not Improved
 A4000209_a_y                   ARIMA(2, 1, 1)  39.623461 Not Improved
 A4000250_a_y SARIMA((1, 1, 2), (1, 0, 1, 12)) 140.618115 Not Improved
 A4000260_a_y           Holt-Winters(add, mul)  72.949543 Not Improved
 A4000263_a_y                   ARIMA(3, 1, 2) 112.357974 Not Improved
 A4000298_b_y           Holt-Winters(add, mul)  47.024832 Not Improved
 A4000309_a_y                   ARIMA(2, 1, 2)  49.146192 Not Improved
 A4000311_a_y           Holt-Winters(add, mul)  44.466618 Not Improved
 A4000323_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  49.450482 Not Improved
 A4000334_c_y                   ARIMA(3, 1, 2)  21.456651     Improved
 A4000335_c_y           Holt-Winters(add, add)  32.645512 Not Improved
 A4000337_c_y           Holt-Winters(add, mul)  73.889811 Not Improved
 A4000338_c_y                   ARIMA(2, 1, 2)  18.384762     Improved
 A4000371_b_y                   ARIMA(2, 1, 1)  96.151129 Not Improved
 A4000379_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  99.007272 Not Improved
 A4000382_c_y           Holt-Winters(add, mul)  32.220545 Not Improved
 A4000392_c_y           Holt-Winters(mul, add)  33.396764 Not Improved
 A4000393_c_y                   ARIMA(3, 1, 2)  27.434423     Improved
 A4000394_c_y                   ARIMA(2, 1, 2)  42.142338 Not Improved
 A4000396_c_y                   ARIMA(2, 1, 1)  59.397000 Not Improved
 A4000399_c_y           Holt-Winters(mul, mul)  31.121922 Not Improved
 A4000411_a_y           Holt-Winters(mul, mul)  75.800627 Not Improved
 A4000430_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  43.758140 Not Improved
 A4000441_a_y           Holt-Winters(add, add)  37.051143 Not Improved
 A4000451_b_y                   ARIMA(3, 1, 2)  57.363515 Not Improved
 A4000453_b_y                   ARIMA(1, 1, 2)  56.620627 Not Improved
 A4000462_a_y                   ARIMA(1, 1, 2)  51.438875 Not Improved
 A4000463_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  75.886957 Not Improved
 A4000473_b_y                   ARIMA(2, 1, 1)  66.648758 Not Improved
 A4000502_c_y                   ARIMA(3, 1, 2)  39.752018 Not Improved
 A4000506_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  61.554985 Not Improved
 A4000509_a_y           Holt-Winters(mul, mul)  42.423665 Not Improved
 A4000511_a_y           Holt-Winters(add, add)  48.814958 Not Improved
 A4000514_a_y                   ARIMA(2, 1, 1)  53.564168 Not Improved
 A4000516_c_y           Holt-Winters(mul, mul) 278.259660 Not Improved
 A4000523_c_y                   ARIMA(2, 1, 1)  62.870383 Not Improved
 A4000527_b_y           Holt-Winters(mul, add) 118.893366 Not Improved
 A4000529_a_y           Holt-Winters(add, mul) 356.331824 Not Improved
 A4000530_b_y           Holt-Winters(mul, add)  67.650520 Not Improved
 A4000531_c_y                   ARIMA(3, 1, 2)  62.983597 Not Improved
 A4000532_c_y                   ARIMA(2, 1, 1)  36.142283 Not Improved
 A4000534_c_y           Holt-Winters(add, add)  74.230187 Not Improved
 A4000535_c_y           Holt-Winters(add, add)  72.058587 Not Improved
 A4000540_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  49.061248 Not Improved
 A4000543_b_y                   ARIMA(3, 1, 2)  51.376122 Not Improved
 A4000548_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  31.094186 Not Improved
 A4000550_a_y                   ARIMA(1, 1, 2)  71.515807 Not Improved
 A4000559_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  39.997633 Not Improved
 A4000561_c_y                   ARIMA(2, 1, 1)  43.678962 Not Improved
 A4000575_b_y           Holt-Winters(add, add)  45.690947 Not Improved
 A4000577_c_y           Holt-Winters(add, add)  27.970672     Improved
 A4000578_c_y           Holt-Winters(add, add)  32.814779 Not Improved
 A4000581_c_y           Holt-Winters(add, add)  79.717126 Not Improved
 A4000582_c_y           Holt-Winters(add, add)  51.915294 Not Improved
 A4000583_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  31.633251 Not Improved
 A4000589_c_y                   ARIMA(3, 1, 2)  46.993737 Not Improved
 A4000594_c_y           Holt-Winters(add, add)  77.995179 Not Improved
 A4000600_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  42.380720 Not Improved
 A4000604_c_y                   ARIMA(3, 1, 2)  43.562634 Not Improved
 A4000607_a_y                   ARIMA(3, 1, 2)  44.103769 Not Improved
 A4000609_c_y                   ARIMA(3, 1, 2)  33.742501 Not Improved
 A4000612_c_y SARIMA((1, 1, 2), (1, 0, 1, 12)) 145.211315 Not Improved
 A4000616_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  70.026124 Not Improved
 A4000617_c_y                   ARIMA(2, 1, 2) 115.285874 Not Improved
 A4000618_b_y           Holt-Winters(add, add)  58.376356 Not Improved
 A4000619_c_y                   ARIMA(2, 1, 1)  98.160795 Not Improved
 A4000622_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  54.156288 Not Improved
 A4000623_a_y           Holt-Winters(add, add)  46.574296 Not Improved
 A4000624_c_y                   ARIMA(2, 1, 1)  52.542646 Not Improved
 A4000628_c_y                   ARIMA(2, 1, 1) 170.675853 Not Improved
 A4000633_b_y                   ARIMA(2, 1, 1)  77.575978 Not Improved
 A4000636_b_y                   ARIMA(1, 1, 2)  54.952475 Not Improved
 A4000641_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  36.068545 Not Improved
 A4000644_c_y                   ARIMA(2, 1, 2)  67.569520 Not Improved
 A4000653_c_y                   ARIMA(3, 1, 2)  71.091026 Not Improved
 A4000654_c_y                   ARIMA(3, 1, 2)  59.815796 Not Improved
 A4000659_c_y                   ARIMA(3, 1, 2)  67.829731 Not Improved
 A4000668_c_y                   ARIMA(2, 1, 1)  58.143404 Not Improved
A52000163_c_y           Holt-Winters(add, add)  43.278288 Not Improved
A52000228_c_y           Holt-Winters(add, add)  49.708058 Not Improved
A52000330_c_y           Holt-Winters(add, add) 105.444859 Not Improved
A52000424_c_y                   ARIMA(3, 1, 2)  66.155881 Not Improved
A52000516_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  47.584449 Not Improved
A52000517_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  56.959653 Not Improved
A58000407_c_y                   ARIMA(3, 1, 2)  63.574682 Not Improved
A58000451_c_y           Holt-Winters(add, add)  71.791602 Not Improved
A58000453_c_y                   ARIMA(1, 1, 2)  55.693863 Not Improved
 A8000189_a_y SARIMA((1, 1, 2), (1, 0, 1, 12)) 215.449058 Not Improved
 A8000261_a_y                   ARIMA(1, 1, 2)  54.554494 Not Improved
 A8000297_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  39.547064 Not Improved
 A8000316_c_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 216.839904 Not Improved
 A8000318_a_y           Holt-Winters(mul, add)  60.225109 Not Improved
 A8000327_a_y           Holt-Winters(add, add)  51.450543 Not Improved
 A8000332_a_y                   ARIMA(1, 1, 2)  49.171847 Not Improved
 A8000340_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  36.153014 Not Improved
 A8000350_a_y                   ARIMA(1, 1, 2)  50.407127 Not Improved
 A8000354_a_y                   ARIMA(3, 1, 2)  71.414774 Not Improved
 A8000361_b_y                   ARIMA(1, 1, 2)  65.334290 Not Improved
 A8000363_b_y           Holt-Winters(add, add)  69.825437 Not Improved
 A8000368_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  30.109840 Not Improved
 A8000369_b_y           Holt-Winters(add, add)  18.565683     Improved
 A8000378_b_y           Holt-Winters(add, add)  49.602291 Not Improved
 A8000388_b_y                   ARIMA(2, 1, 2)  30.929379 Not Improved
 A8000390_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  30.674310 Not Improved
 A8000391_b_y                   ARIMA(2, 1, 1)  58.399376 Not Improved
 A8000393_c_y                   ARIMA(2, 1, 1)  76.124050 Not Improved
 A8000394_b_y                   ARIMA(3, 1, 2)  31.883433 Not Improved
 A8000395_c_y                   ARIMA(3, 1, 2)  48.762675 Not Improved
 A8000399_c_y                   ARIMA(2, 1, 2)  51.424848 Not Improved
 A8000401_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  42.655265 Not Improved
 A8000402_c_y                   ARIMA(2, 1, 1)  51.303482 Not Improved
 A8000406_c_y                   ARIMA(2, 1, 1)  68.132199 Not Improved
 A8000407_c_y           Holt-Winters(add, add)  52.258870 Not Improved
 A8000409_c_y                   ARIMA(3, 1, 2)  36.966018 Not Improved
 A8000410_c_y                   ARIMA(3, 1, 2)  57.027787 Not Improved
 A8000411_c_y                   ARIMA(3, 1, 2)  56.897479 Not Improved
 A8000413_c_y                   ARIMA(3, 1, 2)  45.254841 Not Improved
 A8000414_c_y                   ARIMA(3, 1, 2)  46.506134 Not Improved
 A8000415_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  59.520405 Not Improved
 A8000417_c_y                   ARIMA(1, 1, 2)  48.641896 Not Improved
 A8000418_b_y                   ARIMA(3, 1, 2)  57.151588 Not Improved
 A8000419_c_y                   ARIMA(3, 1, 2)  47.982041 Not Improved
 A8000423_c_y                   ARIMA(3, 1, 2)  49.959025 Not Improved
 A8000424_b_y                   ARIMA(2, 1, 2)  35.683171 Not Improved
 A8000425_c_y           Holt-Winters(add, add)  42.252584 Not Improved
 A8000431_c_y           Holt-Winters(add, add)  33.323330 Not Improved
 A8010054_a_y           Holt-Winters(mul, add)  45.267089 Not Improved
 A8010061_a_y           Holt-Winters(add, add)  51.794594 Not Improved

### Fine-tuning 3rd time

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

# 🔄 Fine-tuning lần 3 với các phương pháp nâng cao (Không dùng Prophet)
print("\n🔄 Bắt đầu Fine-Tuning lần 3 cho các series chưa đạt WMAPE < 30%...")

# **Lọc ra danh sách các series chưa đạt yêu cầu từ lần 2**
df_not_improved_v2 = df_fine_tuned_v2[df_fine_tuned_v2["Status"] == "Not Improved"]
series_to_finetune_v3 = df_not_improved_v2["Series"].tolist()

# **Lưu kết quả fine-tuning nâng cao lần 3**
fine_tuned_results_v3 = []

for col in series_to_finetune_v3:
    series = df_final[col].dropna()
    if len(series) < forecast_periods + 1:
        continue

    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]
    test_arr = np.array(test)

    # **🔹 Sử dụng Differencing để loại bỏ xu hướng**
    train_diff = train.diff().dropna()

    # **🔹 Holt-Winters với period dài hơn**
    best_wmape = np.inf
    best_model = None
    best_forecast = None
    best_params = None

    hw_configs = [12, 18, 24]  # Thử nhiều seasonal period hơn
    for period in hw_configs:
        try:
            model_hw = ExponentialSmoothing(
                train, trend='add', seasonal='add',
                seasonal_periods=period, damped_trend=True
            ).fit()
            forecast_hw = model_hw.forecast(forecast_periods)
            error_hw = np.sum(np.abs(forecast_hw - test_arr))
            wmape_hw = error_hw / np.sum(test_arr) * 100 if np.sum(test_arr) > 0 else np.inf

            if wmape_hw < best_wmape:
                best_wmape = wmape_hw
                best_model = model_hw
                best_forecast = forecast_hw
                best_params = f"Holt-Winters({period})"
        except:
            continue

    # **🔹 Thử ARIMA mở rộng nếu Holt-Winters chưa tốt**
    if best_wmape >= wmape_threshold:
        arima_orders = [(2,1,2), (1,1,2), (2,1,1), (3,1,2)]
        for order in arima_orders:
            try:
                model_arima = ARIMA(train, order=order).fit()
                forecast_arima = model_arima.forecast(forecast_periods)
                error_arima = np.sum(np.abs(forecast_arima - test_arr))
                wmape_arima = error_arima / np.sum(test_arr) * 100

                if wmape_arima < best_wmape:
                    best_wmape = wmape_arima
                    best_model = model_arima
                    best_forecast = forecast_arima
                    best_params = f"ARIMA{order}"
            except:
                continue

    # **🔹 Thử SARIMA nếu ARIMA chưa tốt**
    if best_wmape >= wmape_threshold:
        sarima_orders = [((2,1,1), (1,0,1,12)), ((1,1,2), (1,0,1,12))]
        for non_seasonal, seasonal in sarima_orders:
            try:
                model_sarima = SARIMAX(train, order=non_seasonal, seasonal_order=seasonal).fit(disp=False)
                forecast_sarima = model_sarima.forecast(forecast_periods)
                error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                wmape_sarima = error_sarima / np.sum(test_arr) * 100

                if wmape_sarima < best_wmape:
                    best_wmape = wmape_sarima
                    best_model = model_sarima
                    best_forecast = forecast_sarima
                    best_params = f"SARIMA{non_seasonal, seasonal}"
            except:
                continue

    # **🔹 Thử XGBoost Regressor nếu SARIMA chưa tốt**
    if best_wmape >= wmape_threshold:
        try:
            # Chuẩn bị dữ liệu cho XGBoost
            x_train = np.arange(len(train)).reshape(-1, 1)
            y_train = train.values
            x_test = np.arange(len(train), len(train) + forecast_periods).reshape(-1, 1)

            model_xgb = GradientBoostingRegressor()
            model_xgb.fit(x_train, y_train)
            forecast_xgb = model_xgb.predict(x_test)

            error_xgb = np.sum(np.abs(forecast_xgb - test_arr))
            wmape_xgb = error_xgb / np.sum(test_arr) * 100

            if wmape_xgb < best_wmape:
                best_wmape = wmape_xgb
                best_model = model_xgb
                best_forecast = forecast_xgb
                best_params = "XGBoost Regressor"
        except:
            pass

    # **🔹 Lưu kết quả fine-tuning lần 3**
    fine_tuned_results_v3.append({
        "Series": col,
        "Best Model": best_params,
        "New WMAPE": best_wmape,
        "Status": "Improved" if best_wmape < wmape_threshold else "Not Improved"
    })

# **Hiển thị kết quả fine-tuning lần 3**
df_fine_tuned_v3 = pd.DataFrame(fine_tuned_results_v3)
print("\n=== 🔥 Fine-Tuning Lần 3: Cải Thiện Các Series Chưa Đạt ===")
print(df_fine_tuned_v3.to_string(index=False))

# **Tính số lượng series được cải thiện sau fine-tuning lần 3**
num_improved_v3 = df_fine_tuned_v3[df_fine_tuned_v3["Status"] == "Improved"].shape[0]
print(f"\n✅ Số series được cải thiện sau Fine-Tuning lần 3: {num_improved_v3}/{len(series_to_finetune_v3)}")

🔄 Bắt đầu Fine-Tuning lần 3 cho các series chưa đạt WMAPE < 30%...

=== 🔥 Fine-Tuning Lần 3: Cải Thiện Các Series Chưa Đạt ===
       Series                       Best Model  New WMAPE       Status
 A2000135_a_y                XGBoost Regressor  71.735342 Not Improved
 A2000136_a_y                   ARIMA(1, 1, 2)  87.220188 Not Improved
 A2000329_a_y                   ARIMA(3, 1, 2)  43.843712 Not Improved
 A2000346_a_y                XGBoost Regressor  60.789367 Not Improved
 A2000355_a_y                 Holt-Winters(12)  48.044960 Not Improved
 A2000370_a_y                 Holt-Winters(12)  40.815270 Not Improved
 A2000388_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  62.098984 Not Improved
 A2000409_b_y                XGBoost Regressor 218.355563 Not Improved
 A2000410_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  71.899733 Not Improved
 A2000416_a_y                 Holt-Winters(12)  42.178256 Not Improved
 A2000442_a_y                XGBoost Regressor  38.560000 Not Improved
 A2000461_a_y                XGBoost Regressor  35.982910 Not Improved
 A2000484_b_y                XGBoost Regressor  43.084954 Not Improved
 A2000485_a_y                 Holt-Winters(12)  36.756753 Not Improved
 A2000488_a_y                   ARIMA(1, 1, 2)  30.559614 Not Improved
 A2000490_b_y                XGBoost Regressor  49.152542 Not Improved
 A2000491_b_y                XGBoost Regressor  46.839863 Not Improved
 A2000494_b_y                   ARIMA(3, 1, 2)  55.811839 Not Improved
 A2000495_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  59.657191 Not Improved
 A2000497_b_y                XGBoost Regressor  59.026177 Not Improved
 A2000506_b_y                   ARIMA(3, 1, 2) 119.552400 Not Improved
 A2000509_a_y                 Holt-Winters(12)  35.730811 Not Improved
 A2000510_a_y                 Holt-Winters(12)  52.850079 Not Improved
 A2000512_a_y                XGBoost Regressor  29.844413     Improved
 A2000515_a_y                XGBoost Regressor  40.566038 Not Improved
 A2000516_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  38.741288 Not Improved
 A2000517_a_y                XGBoost Regressor  43.871245 Not Improved
 A2000518_a_y                XGBoost Regressor  32.244898 Not Improved
 A2000519_a_y                XGBoost Regressor  35.287880 Not Improved
 A2000527_b_y                XGBoost Regressor 118.360517 Not Improved
 A2000529_c_y                   ARIMA(3, 1, 2)  92.527535 Not Improved
 A2000534_c_y                 Holt-Winters(12) 159.565707 Not Improved
 A2000535_c_y                   ARIMA(2, 1, 1) 146.805206 Not Improved
 A2000539_a_y                XGBoost Regressor  36.048957 Not Improved
 A2000540_a_y                XGBoost Regressor  33.533818 Not Improved
 A2000548_b_y                 Holt-Winters(12) 168.685444 Not Improved
 A2000550_c_y                XGBoost Regressor  67.925719 Not Improved
 A2000554_a_y                XGBoost Regressor  56.248245 Not Improved
 A2000555_b_y                   ARIMA(2, 1, 2) 290.358314 Not Improved
 A2000561_a_y                   ARIMA(1, 1, 2)  77.521749 Not Improved
 A2000562_a_y                   ARIMA(2, 1, 2)  37.075872 Not Improved
 A2000566_b_y                XGBoost Regressor  40.561753 Not Improved
 A2000567_c_y                XGBoost Regressor  39.495798 Not Improved
 A2000568_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  49.941419 Not Improved
 A2000572_c_y                   ARIMA(3, 1, 2)  43.090167 Not Improved
 A2000576_b_y                XGBoost Regressor  32.307692 Not Improved
 A2000584_c_y                   ARIMA(3, 1, 2)  39.619572 Not Improved
 A2000595_c_y                   ARIMA(2, 1, 1)  54.383446 Not Improved
 A2000596_b_y                XGBoost Regressor  42.307692 Not Improved
 A2000609_b_y                XGBoost Regressor 126.005003 Not Improved
 A2000610_b_y                   ARIMA(2, 1, 2) 106.033605 Not Improved
 A2000611_b_y                   ARIMA(2, 1, 1)  61.878010 Not Improved
 A2000614_c_y                   ARIMA(2, 1, 1)  35.402977 Not Improved
 A2000617_b_y                   ARIMA(1, 1, 2)  89.120361 Not Improved
 A2000618_b_y                XGBoost Regressor  66.528679 Not Improved
 A2000628_a_y                 Holt-Winters(12)  48.485362 Not Improved
 A2000629_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  40.961593 Not Improved
 A2000635_b_y                 Holt-Winters(12)  43.974209 Not Improved
 A2000636_b_y                   ARIMA(1, 1, 2)  43.987049 Not Improved
 A2000649_a_y                 Holt-Winters(12)  40.120211 Not Improved
 A2000650_a_y                   ARIMA(3, 1, 2)  40.572562 Not Improved
 A2000652_b_y                   ARIMA(2, 1, 1)  37.945597 Not Improved
 A2000655_c_y                XGBoost Regressor  49.663586 Not Improved
 A2000657_c_y                   ARIMA(3, 1, 2)  56.543844 Not Improved
 A2000658_c_y                   ARIMA(1, 1, 2)  59.985167 Not Improved
 A2000660_c_y                XGBoost Regressor  47.142159 Not Improved
 A2000661_c_y                   ARIMA(2, 1, 1)  56.806655 Not Improved
 A2000663_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  50.030879 Not Improved
 A2000664_c_y                   ARIMA(2, 1, 1)  51.105875 Not Improved
 A2000670_c_y                XGBoost Regressor  35.627913 Not Improved
 A2000673_c_y                XGBoost Regressor  46.665233 Not Improved
 A2000674_c_y                XGBoost Regressor  44.556234 Not Improved
 A2000679_c_y                 Holt-Winters(12)  51.284309 Not Improved
 A2000683_c_y                XGBoost Regressor  61.221949 Not Improved
 A2000690_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  78.039975 Not Improved
 A2000691_c_y                   ARIMA(2, 1, 2)  65.860286 Not Improved
 A2000692_c_y                   ARIMA(3, 1, 2)  48.231839 Not Improved
 A2000693_c_y                   ARIMA(3, 1, 2)  35.189306 Not Improved
 A2000695_c_y                   ARIMA(3, 1, 2)  42.381739 Not Improved
 A2000701_c_y                XGBoost Regressor  32.530947 Not Improved
 A2000702_c_y                XGBoost Regressor  33.755572 Not Improved
 A2000703_c_y                XGBoost Regressor  28.611611     Improved
 A2000704_c_y                XGBoost Regressor  29.315695     Improved
 A2000705_c_y                XGBoost Regressor  34.138973 Not Improved
 A2900003_c_y                   ARIMA(3, 1, 2)  95.517916 Not Improved
 A2900004_c_y                   ARIMA(3, 1, 2)  88.929477 Not Improved
 A2900005_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  33.265207 Not Improved
 A2900010_c_y                XGBoost Regressor  42.690058 Not Improved
 A2900011_c_y                XGBoost Regressor  46.241897 Not Improved
 A2900013_b_y                 Holt-Winters(12)  61.468232 Not Improved
 A2900017_b_y                   ARIMA(2, 1, 2)  38.558003 Not Improved
 A2900021_c_y                   ARIMA(2, 1, 2)  91.621085 Not Improved
 A2C00204_c_y                XGBoost Regressor  54.439254 Not Improved
 A3000030_a_y                XGBoost Regressor 120.464898 Not Improved
 A3000054_b_y                   ARIMA(2, 1, 2)  41.058811 Not Improved
 A3000063_a_y                 Holt-Winters(12)  92.234396 Not Improved
 A3000135_a_y                   ARIMA(2, 1, 2) 261.822063 Not Improved
 A3000140_a_y                XGBoost Regressor  92.923723 Not Improved
 A3000174_a_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 117.052700 Not Improved
 A3000213_a_y                   ARIMA(2, 1, 1)  34.101048 Not Improved
 A3000241_a_y                   ARIMA(3, 1, 2)  71.317346 Not Improved
 A3000259_a_y                 Holt-Winters(12)  55.389853 Not Improved
 A3000261_b_y                XGBoost Regressor  56.691518 Not Improved
 A3000278_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  79.939427 Not Improved
 A3000308_a_y                   ARIMA(2, 1, 1)  70.145154 Not Improved
 A3000330_b_y                XGBoost Regressor  31.970951 Not Improved
 A3000335_b_y                XGBoost Regressor  37.024221 Not Improved
 A3000336_a_y                   ARIMA(2, 1, 1)  52.551227 Not Improved
 A3000337_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  65.806111 Not Improved
 A3000338_a_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 327.869077 Not Improved
 A3000339_a_y                   ARIMA(3, 1, 2)  30.192974 Not Improved
 A3000343_a_y                   ARIMA(2, 1, 2) 264.853085 Not Improved
A3000366C_c_y                   ARIMA(1, 1, 2)  98.353453 Not Improved
 A3000604_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  55.566534 Not Improved
 A3000609_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  72.977949 Not Improved
 A3000610_c_y                 Holt-Winters(12)  80.810123 Not Improved
 A3000617_c_y                 Holt-Winters(12)  65.547819 Not Improved
 A3000619_c_y                   ARIMA(2, 1, 2)  53.834018 Not Improved
 A3000623_c_y                 Holt-Winters(12)  40.546895 Not Improved
 A3000629_a_y                   ARIMA(3, 1, 2)  40.546614 Not Improved
 A3000631_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  79.789409 Not Improved
 A3000647_c_y                   ARIMA(2, 1, 1)  82.743719 Not Improved
 A3000661_c_y                   ARIMA(1, 1, 2)  31.039495 Not Improved
 A3000668_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  38.229450 Not Improved
 A3000670_a_y                   ARIMA(2, 1, 1)  31.916105 Not Improved
 A3000673_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  57.636251 Not Improved
 A3000682_c_y                   ARIMA(2, 1, 1)  48.172913 Not Improved
 A3000683_a_y                   ARIMA(2, 1, 2)  41.182997 Not Improved
 A3000693_c_y                   ARIMA(2, 1, 1)  38.578527 Not Improved
 A3000699_c_y                   ARIMA(3, 1, 2)  45.586067 Not Improved
 A3000726_c_y                XGBoost Regressor  37.272727 Not Improved
 A4000001_a_y                 Holt-Winters(12) 193.252891 Not Improved
 A4000032_a_y                   ARIMA(2, 1, 2) 109.161016 Not Improved
 A4000039_a_y                 Holt-Winters(12)  46.108923 Not Improved
 A4000047_a_y                XGBoost Regressor 162.128356 Not Improved
 A4000077_a_y                 Holt-Winters(12)  65.335838 Not Improved
 A4000081_a_y                   ARIMA(2, 1, 1)  63.975231 Not Improved
 A4000089_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  67.955687 Not Improved
 A4000091_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  47.315054 Not Improved
 A4000096_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  88.438968 Not Improved
 A4000099_c_y                   ARIMA(2, 1, 1)  36.034685 Not Improved
 A4000178_a_y                XGBoost Regressor 215.566371 Not Improved
 A4000189_a_y                XGBoost Regressor 135.432972 Not Improved
 A4000209_a_y                   ARIMA(2, 1, 1)  39.623461 Not Improved
 A4000250_a_y SARIMA((1, 1, 2), (1, 0, 1, 12)) 140.618115 Not Improved
 A4000260_a_y                   ARIMA(3, 1, 2) 172.000823 Not Improved
 A4000263_a_y                   ARIMA(3, 1, 2) 112.357974 Not Improved
 A4000298_b_y                XGBoost Regressor  96.153846 Not Improved
 A4000309_a_y                   ARIMA(2, 1, 2)  49.146192 Not Improved
 A4000311_a_y                 Holt-Winters(12)  43.692117 Not Improved
 A4000323_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  49.450482 Not Improved
 A4000335_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  35.312411 Not Improved
 A4000337_c_y                XGBoost Regressor 184.890371 Not Improved
 A4000371_b_y                   ARIMA(2, 1, 1)  96.151129 Not Improved
 A4000379_c_y                 Holt-Winters(12)  81.348200 Not Improved
 A4000382_c_y                   ARIMA(3, 1, 2)  37.753315 Not Improved
 A4000392_c_y                XGBoost Regressor  31.092437 Not Improved
 A4000394_c_y                   ARIMA(2, 1, 2)  42.142338 Not Improved
 A4000396_c_y                   ARIMA(2, 1, 1)  59.397000 Not Improved
 A4000399_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  32.758995 Not Improved
 A4000411_a_y                 Holt-Winters(12)  83.935508 Not Improved
 A4000430_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  43.758140 Not Improved
 A4000441_a_y                   ARIMA(1, 1, 2)  39.355967 Not Improved
 A4000451_b_y                   ARIMA(3, 1, 2)  57.363515 Not Improved
 A4000453_b_y                XGBoost Regressor  48.985085 Not Improved
 A4000462_a_y                   ARIMA(1, 1, 2)  51.438875 Not Improved
 A4000463_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  75.886957 Not Improved
 A4000473_b_y                   ARIMA(2, 1, 1)  66.648758 Not Improved
 A4000502_c_y                XGBoost Regressor  39.316478 Not Improved
 A4000506_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  61.554985 Not Improved
 A4000509_a_y                XGBoost Regressor  54.409665 Not Improved
 A4000511_a_y                 Holt-Winters(12)  86.551206 Not Improved
 A4000514_a_y                   ARIMA(2, 1, 1)  53.564168 Not Improved
 A4000516_c_y                 Holt-Winters(12) 242.743781 Not Improved
 A4000523_c_y                   ARIMA(2, 1, 1)  62.870383 Not Improved
 A4000527_b_y                XGBoost Regressor 113.416626 Not Improved
 A4000529_a_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 360.269412 Not Improved
 A4000530_b_y                   ARIMA(2, 1, 1)  97.069543 Not Improved
 A4000531_c_y                 Holt-Winters(12)  57.887565 Not Improved
 A4000532_c_y                   ARIMA(2, 1, 1)  36.142283 Not Improved
 A4000534_c_y                XGBoost Regressor  50.447791 Not Improved
 A4000535_c_y                XGBoost Regressor  56.435644 Not Improved
 A4000540_a_y                XGBoost Regressor  40.857089 Not Improved
 A4000543_b_y                   ARIMA(3, 1, 2)  51.376122 Not Improved
 A4000548_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  31.094186 Not Improved
 A4000550_a_y                XGBoost Regressor  35.625998 Not Improved
 A4000559_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  39.997633 Not Improved
 A4000561_c_y                   ARIMA(2, 1, 1)  43.678962 Not Improved
 A4000575_b_y                 Holt-Winters(12)  44.665076 Not Improved
 A4000578_c_y                 Holt-Winters(12)  44.368878 Not Improved
 A4000581_c_y                 Holt-Winters(12)  77.747402 Not Improved
 A4000582_c_y                 Holt-Winters(12)  56.124470 Not Improved
 A4000583_c_y                XGBoost Regressor  27.657205     Improved
 A4000589_c_y                 Holt-Winters(12)  44.930378 Not Improved
 A4000594_c_y                XGBoost Regressor  50.531002 Not Improved
 A4000600_c_y                 Holt-Winters(12)  39.190254 Not Improved
 A4000604_c_y                   ARIMA(3, 1, 2)  43.562634 Not Improved
 A4000607_a_y                 Holt-Winters(12)  43.308126 Not Improved
 A4000609_c_y                   ARIMA(3, 1, 2)  33.742501 Not Improved
 A4000612_c_y                XGBoost Regressor 112.807687 Not Improved
 A4000616_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  70.026124 Not Improved
 A4000617_c_y                   ARIMA(2, 1, 2) 115.285874 Not Improved
 A4000618_b_y                   ARIMA(3, 1, 2)  91.004825 Not Improved
 A4000619_c_y                XGBoost Regressor  54.578936 Not Improved
 A4000622_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  54.156288 Not Improved
 A4000623_a_y                XGBoost Regressor  46.366510 Not Improved
 A4000624_c_y                   ARIMA(2, 1, 1)  52.542646 Not Improved
 A4000628_c_y                   ARIMA(2, 1, 1) 170.675853 Not Improved
 A4000633_b_y                   ARIMA(2, 1, 1)  77.575978 Not Improved
 A4000636_b_y                XGBoost Regressor  50.702775 Not Improved
 A4000641_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  36.068545 Not Improved
 A4000644_c_y                   ARIMA(2, 1, 2)  67.569520 Not Improved
 A4000653_c_y                XGBoost Regressor  68.053411 Not Improved
 A4000654_c_y                 Holt-Winters(12)  56.212125 Not Improved
 A4000659_c_y                 Holt-Winters(12)  53.220988 Not Improved
 A4000668_c_y                XGBoost Regressor  53.239437 Not Improved
A52000163_c_y                XGBoost Regressor  50.271032 Not Improved
A52000228_c_y                XGBoost Regressor  51.428571 Not Improved
A52000330_c_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 148.913484 Not Improved
A52000424_c_y                   ARIMA(3, 1, 2)  66.155881 Not Improved
A52000516_c_y                XGBoost Regressor  38.775510 Not Improved
A52000517_c_y                XGBoost Regressor  49.152542 Not Improved
A58000407_c_y                   ARIMA(3, 1, 2)  63.574682 Not Improved
A58000451_c_y                   ARIMA(2, 1, 1)  80.898840 Not Improved
A58000453_c_y                   ARIMA(1, 1, 2)  55.693863 Not Improved
 A8000189_a_y                 Holt-Winters(12) 196.862793 Not Improved
 A8000261_a_y                   ARIMA(1, 1, 2)  54.554494 Not Improved
 A8000297_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  39.547064 Not Improved
 A8000316_c_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 216.839904 Not Improved
 A8000318_a_y                   ARIMA(2, 1, 1)  86.423902 Not Improved
 A8000327_a_y                 Holt-Winters(12)  60.600850 Not Improved
 A8000332_a_y                   ARIMA(1, 1, 2)  49.171847 Not Improved
 A8000340_a_y                 Holt-Winters(12)  34.988756 Not Improved
 A8000350_a_y                   ARIMA(1, 1, 2)  50.407127 Not Improved
 A8000354_a_y                   ARIMA(3, 1, 2)  71.414774 Not Improved
 A8000361_b_y                   ARIMA(1, 1, 2)  65.334290 Not Improved
 A8000363_b_y                   ARIMA(3, 1, 2)  71.004355 Not Improved
 A8000368_a_y SARIMA((2, 1, 1), (1, 0, 1, 12))  30.109840 Not Improved
 A8000378_b_y                   ARIMA(2, 1, 1)  51.714697 Not Improved
 A8000388_b_y                   ARIMA(2, 1, 2)  30.929379 Not Improved
 A8000390_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  30.674310 Not Improved
 A8000391_b_y                XGBoost Regressor  57.898253 Not Improved
 A8000393_c_y                   ARIMA(2, 1, 1)  76.124050 Not Improved
 A8000394_b_y                   ARIMA(3, 1, 2)  31.883433 Not Improved
 A8000395_c_y                   ARIMA(3, 1, 2)  48.762675 Not Improved
 A8000399_c_y                   ARIMA(2, 1, 2)  51.424848 Not Improved
 A8000401_c_y SARIMA((2, 1, 1), (1, 0, 1, 12))  42.655265 Not Improved
 A8000402_c_y                   ARIMA(2, 1, 1)  51.303482 Not Improved
 A8000406_c_y                 Holt-Winters(12)  53.882470 Not Improved
 A8000407_c_y                 Holt-Winters(12)  58.773717 Not Improved
 A8000409_c_y                XGBoost Regressor  26.419361     Improved
 A8000410_c_y                XGBoost Regressor  53.451256 Not Improved
 A8000411_c_y                XGBoost Regressor  46.785638 Not Improved
 A8000413_c_y                   ARIMA(3, 1, 2)  45.254841 Not Improved
 A8000414_c_y                   ARIMA(3, 1, 2)  46.506134 Not Improved
 A8000415_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  59.520405 Not Improved
 A8000417_c_y                   ARIMA(1, 1, 2)  48.641896 Not Improved
 A8000418_b_y                XGBoost Regressor  47.734597 Not Improved
 A8000419_c_y                   ARIMA(3, 1, 2)  47.982041 Not Improved
 A8000423_c_y                 Holt-Winters(12)  34.961112 Not Improved
 A8000424_b_y                XGBoost Regressor  26.615547     Improved
 A8000425_c_y SARIMA((1, 1, 2), (1, 0, 1, 12))  43.999242 Not Improved
 A8000431_c_y                XGBoost Regressor  66.038542 Not Improved
 A8010054_a_y                 Holt-Winters(12)  31.510663 Not Improved
 A8010061_a_y                XGBoost Regressor  37.440758 Not Improved
 A8010076_a_y                 Holt-Winters(12)  33.271858 Not Improved
 A8010089_a_y SARIMA((1, 1, 2), (1, 0, 1, 12))  38.958694 Not Improved
 A8010096_b_y SARIMA((2, 1, 1), (1, 0, 1, 12))  47.607204 Not Improved
 A8010110_a_y                XGBoost Regressor  37.878946 Not Improved
 A8010112_a_y                 Holt-Winters(12)  33.534513 Not Improved
 A8010113_a_y                   ARIMA(1, 1, 2)  90.531413 Not Improved
 A8010124_a_y                XGBoost Regressor  35.461286 Not Improved
 A8010127_b_y                   ARIMA(1, 1, 2) 150.490816 Not Improved
 A8010153_a_y                   ARIMA(1, 1, 2)  33.759184 Not Improved
 A8010154_a_y                   ARIMA(1, 1, 2)  45.906298 Not Improved
 A8010171_a_y                XGBoost Regressor  37.559757 Not Improved
 A8010189_b_y SARIMA((2, 1, 1), (1, 0, 1, 12)) 117.633701 Not Improved
 A8010197_a_y                 Holt-Winters(12)  37.639977 Not Improved

### Fine-tuning 4th time

In [ ]:
# Kiểm tra xem thư viện Prophet có sẵn không
try:
    from prophet import Prophet
    prophet_available = True
except ImportError:
    prophet_available = False

# Kiểm tra xem TensorFlow/Keras có sẵn không (để chạy LSTM)
try:
    import tensorflow as tf
    from tensorflow.keras.models import Sequential
    from tensorflow.keras.layers import LSTM, Dense, Dropout
    from sklearn.preprocessing import MinMaxScaler
    lstm_available = True
except ImportError:
    lstm_available = False

# Báo cáo lại kết quả kiểm tra
if prophet_available and lstm_available:
    print("✅ Cả Prophet và LSTM đều khả dụng! Sẽ chạy cả hai mô hình.")
elif prophet_available:
    print("✅ Prophet khả dụng! Sẽ chỉ chạy Prophet.")
elif lstm_available:
    print("✅ LSTM khả dụng! Sẽ chỉ chạy LSTM.")
else:
    print("⚠️ Cả Prophet và LSTM đều không khả dụng! Không thể tiếp tục fine-tuning với mô hình này.")

✅ Cả Prophet và LSTM đều khả dụng! Sẽ chạy cả hai mô hình.

In [ ]:
import numpy as np
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from pmdarima import auto_arima
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler

# Load dữ liệu
df_final = pd.read_csv("Series_Hierarchical.csv", index_col=0, parse_dates=True)

# Kiểm tra nếu df_fine_tuned_v3 có tồn tại
if 'df_fine_tuned_v3' not in locals() or df_fine_tuned_v3 is None:
    df_fine_tuned_v3 = pd.DataFrame(columns=["Series", "Best Model", "New WMAPE", "Status"])

# Kiểm tra cột "Status"
if "Status" not in df_fine_tuned_v3.columns:
    df_fine_tuned_v3["Status"] = "Not Improved"

# Lọc các series chưa đạt yêu cầu
df_not_improved = df_fine_tuned_v3[df_fine_tuned_v3["Status"] == "Not Improved"]
series_to_finetune = df_not_improved["Series"].tolist()

fine_tuned_results_v4 = []

for col in series_to_finetune:
    series = df_final[col].dropna()

    # **Kiểm tra nếu dữ liệu quá ít (< 6 tháng) thì bỏ qua**
    if len(series) < 6:
        print(f"⚠️ Series {col} có quá ít dữ liệu, bỏ qua!")
        continue

    train = series.iloc[:-6]
    test = series.iloc[-6:]

    best_wmape = np.inf
    best_model = None
    best_forecast = None

    # **1️⃣ Auto ARIMA**
    try:
        model_arima = auto_arima(train, seasonal=False, stepwise=True, suppress_warnings=True)
        forecast_arima = model_arima.predict(n_periods=6)
        wmape_arima = sum(abs(forecast_arima - test)) / sum(test) * 100

        if wmape_arima < best_wmape:
            best_wmape = wmape_arima
            best_model = "Auto ARIMA"
            best_forecast = forecast_arima
    except:
        pass

    # **2️⃣ Holt-Winters**
    try:
        model_hw = ExponentialSmoothing(train, trend='add', seasonal=None, damped_trend=True).fit()
        forecast_hw = model_hw.forecast(6)
        wmape_hw = sum(abs(forecast_hw - test)) / sum(test) * 100

        if wmape_hw < best_wmape:
            best_wmape = wmape_hw
            best_model = "Holt-Winters"
            best_forecast = forecast_hw
    except:
        pass

    # **3️⃣ Random Forest Regressor**
    try:
        scaler = MinMaxScaler(feature_range=(0, 1))
        train_scaled = scaler.fit_transform(train.values.reshape(-1, 1))

        X_train = np.arange(len(train_scaled)).reshape(-1, 1)
        y_train = train_scaled.flatten()
        X_test = np.arange(len(train_scaled), len(train_scaled) + 6).reshape(-1, 1)

        model_rf = RandomForestRegressor(n_estimators=50)
        model_rf.fit(X_train, y_train)
        forecast_rf = model_rf.predict(X_test)
        forecast_rf = scaler.inverse_transform(forecast_rf.reshape(-1, 1)).flatten()

        wmape_rf = sum(abs(forecast_rf - test)) / sum(test) * 100

        if wmape_rf < best_wmape:
            best_wmape = wmape_rf
            best_model = "Random Forest"
            best_forecast = forecast_rf
    except:
        pass

    # **4️⃣ Kết hợp Holt-Winters + XGBoost**
    try:
        from xgboost import XGBRegressor

        model_hw = ExponentialSmoothing(train, trend='add', seasonal=None, damped_trend=True).fit()
        residuals = train - model_hw.fittedvalues

        X_train = np.arange(len(residuals)).reshape(-1, 1)
        y_train = residuals.values
        X_test = np.arange(len(residuals), len(residuals) + 6).reshape(-1, 1)

        model_xgb = XGBRegressor()
        model_xgb.fit(X_train, y_train)
        forecast_xgb = model_xgb.predict(X_test) + model_hw.forecast(6)

        wmape_xgb = sum(abs(forecast_xgb - test)) / sum(test) * 100

        if wmape_xgb < best_wmape:
            best_wmape = wmape_xgb
            best_model = "Holt-Winters + XGBoost"
            best_forecast = forecast_xgb
    except:
        pass

    # **Lưu kết quả**
    fine_tuned_results_v4.append({
        "Series": col,
        "Best Model": best_model,
        "New WMAPE": best_wmape,
        "Status": "Improved" if best_wmape < 30 else "Not Improved"
    })

# **Nếu không có series nào được train**
if len(fine_tuned_results_v4) == 0:
    print("⚠️ Không có series nào đủ dữ liệu để train Auto ARIMA, Holt-Winters, Random Forest hoặc XGBoost.")
else:
    # **Hiển thị kết quả Fine-Tuning**
    df_fine_tuned_v4 = pd.DataFrame(fine_tuned_results_v4)
    print("\n=== 🔥 Fine-Tuning Lần 4 (Auto ARIMA + Holt-Winters + Random Forest + XGBoost) ===")
    print(df_fine_tuned_v4.to_string(index=False))

    # **Số series được cải thiện**
    num_improved_v4 = df_fine_tuned_v4[df_fine_tuned_v4["Status"] == "Improved"].shape[0]
    print(f"\n✅ Số series được cải thiện: {num_improved_v4}/{len(series_to_finetune)}")

=== 🔥 Fine-Tuning Lần 4 (Auto ARIMA + Holt-Winters + Random Forest + XGBoost) ===
       Series    Best Model  New WMAPE       Status
 A2000135_a_y Random Forest  53.490909 Not Improved
 A2000136_a_y Random Forest 100.310178 Not Improved
 A2000329_a_y Random Forest  55.628866 Not Improved
 A2000346_a_y Random Forest  62.388824 Not Improved
 A2000355_a_y Random Forest 113.664286 Not Improved
 A2000370_a_y Random Forest  54.823529 Not Improved
 A2000388_a_y Random Forest  74.354680 Not Improved
 A2000409_b_y Random Forest 224.266667 Not Improved
 A2000410_a_y Random Forest 108.528302 Not Improved
 A2000416_a_y Random Forest  46.656700 Not Improved
 A2000442_a_y Random Forest  38.560000 Not Improved
 A2000461_a_y Random Forest  35.305660 Not Improved
 A2000484_b_y Random Forest  46.014388 Not Improved
 A2000485_a_y Random Forest  37.423313 Not Improved
 A2000488_a_y Random Forest  41.676471 Not Improved
 A2000490_b_y Random Forest  49.152542 Not Improved
 A2000491_b_y Random Forest  51.302564 Not Improved
 A2000494_b_y Random Forest  86.318584 Not Improved
 A2000495_b_y Random Forest 111.696552 Not Improved
 A2000497_b_y Random Forest  37.399103 Not Improved
 A2000506_b_y Random Forest 126.342541 Not Improved
 A2000509_a_y Random Forest  56.360902 Not Improved
 A2000510_a_y Random Forest  54.645161 Not Improved
 A2000515_a_y Random Forest  40.566038 Not Improved
 A2000516_a_y Random Forest  41.043084 Not Improved
 A2000517_a_y Random Forest  42.857143 Not Improved
 A2000518_a_y Random Forest  35.281633 Not Improved
 A2000519_a_y Random Forest  33.764103 Not Improved
 A2000527_b_y Random Forest 103.351351 Not Improved
 A2000529_c_y Random Forest  94.584615 Not Improved
 A2000534_c_y Random Forest 227.680000 Not Improved
 A2000535_c_y Random Forest 133.842105 Not Improved
 A2000539_a_y Random Forest  36.015355 Not Improved
 A2000540_a_y Random Forest  56.871194 Not Improved
 A2000548_b_y Random Forest 174.989474 Not Improved
 A2000550_c_y Random Forest  65.166667 Not Improved
 A2000554_a_y Random Forest  35.765396 Not Improved
 A2000555_b_y Random Forest 430.571429 Not Improved
 A2000561_a_y Random Forest  69.310174 Not Improved
 A2000562_a_y Random Forest  44.105541 Not Improved
 A2000566_b_y Random Forest  43.392000 Not Improved
 A2000567_c_y Random Forest  39.495798 Not Improved
 A2000568_c_y Random Forest  49.387755 Not Improved
 A2000572_c_y Random Forest  68.307692 Not Improved
 A2000576_b_y Random Forest  71.230769 Not Improved
 A2000584_c_y Random Forest  43.977465 Not Improved
 A2000595_c_y Random Forest  60.202532 Not Improved
 A2000596_b_y Random Forest  42.307692 Not Improved
 A2000609_b_y Random Forest 125.705882 Not Improved
 A2000610_b_y Random Forest 112.866071 Not Improved
 A2000611_b_y Random Forest  48.382253 Not Improved
 A2000614_c_y Random Forest  37.244635 Not Improved
 A2000617_b_y Random Forest  96.534562 Not Improved
 A2000618_b_y Random Forest  87.815126 Not Improved
 A2000628_a_y Random Forest  39.227231 Not Improved
 A2000629_a_y Random Forest  39.866953 Not Improved
 A2000635_b_y Random Forest  52.114613 Not Improved
 A2000636_b_y Random Forest  48.545710 Not Improved
 A2000649_a_y Random Forest  42.199903 Not Improved
 A2000650_a_y Random Forest  43.378205 Not Improved
 A2000652_b_y Random Forest  43.114563 Not Improved
 A2000655_c_y Random Forest  40.350877 Not Improved
 A2000657_c_y Random Forest  59.276836 Not Improved
 A2000658_c_y Random Forest  64.800000 Not Improved
 A2000660_c_y Random Forest  52.492754 Not Improved
 A2000661_c_y Random Forest  71.805825 Not Improved
 A2000663_c_y Random Forest  51.868852 Not Improved
 A2000664_c_y Random Forest  50.923434 Not Improved
 A2000670_c_y Random Forest  43.302211 Not Improved
 A2000673_c_y Random Forest  54.676692 Not Improved
 A2000674_c_y Random Forest  47.562500 Not Improved
 A2000679_c_y Random Forest  52.554622 Not Improved
 A2000683_c_y Random Forest  63.046683 Not Improved
 A2000690_c_y Random Forest  78.486747 Not Improved
 A2000691_c_y Random Forest  79.073569 Not Improved
 A2000692_c_y Random Forest  51.195652 Not Improved
 A2000693_c_y Random Forest  37.641694 Not Improved
 A2000695_c_y Random Forest  51.485714 Not Improved
 A2000701_c_y Random Forest  39.686747 Not Improved
 A2000702_c_y Random Forest  45.287066 Not Improved
 A2000705_c_y Random Forest  40.882175 Not Improved
 A2900003_c_y Random Forest 129.613445 Not Improved
 A2900004_c_y Random Forest 101.031359 Not Improved
 A2900005_c_y Random Forest  31.944444 Not Improved
 A2900010_c_y Random Forest  42.690058 Not Improved
 A2900011_c_y Random Forest  45.785877 Not Improved
 A2900013_b_y Random Forest  77.621381 Not Improved
 A2900017_b_y Random Forest  46.137834 Not Improved
 A2900021_c_y Random Forest 123.983673 Not Improved
 A2C00204_c_y Random Forest  56.423077 Not Improved
 A3000030_a_y Random Forest 114.567474 Not Improved
 A3000054_b_y Random Forest  62.139535 Not Improved
 A3000063_a_y Random Forest 109.106383 Not Improved
 A3000135_a_y Random Forest 287.642857 Not Improved
 A3000140_a_y Random Forest 100.591133 Not Improved
 A3000174_a_y Random Forest 163.382114 Not Improved
 A3000213_a_y Random Forest  42.666667 Not Improved
 A3000241_a_y Random Forest  80.288030 Not Improved
 A3000259_a_y Random Forest  86.244660 Not Improved
 A3000261_b_y Random Forest  65.012048 Not Improved
 A3000278_b_y Random Forest 104.553846 Not Improved
 A3000308_a_y Random Forest  82.635183 Not Improved
 A3000330_b_y Random Forest  28.173913     Improved
 A3000335_b_y Random Forest  37.453287 Not Improved
 A3000336_a_y Random Forest  49.384127 Not Improved
 A3000337_a_y Random Forest  73.115942 Not Improved
 A3000338_a_y Random Forest 329.818182 Not Improved
 A3000339_a_y Random Forest  37.309293 Not Improved
 A3000343_a_y Random Forest 265.735294 Not Improved
A3000366C_c_y Random Forest 154.022472 Not Improved
 A3000604_a_y Random Forest  71.870229 Not Improved
 A3000609_c_y Random Forest 134.584071 Not Improved
 A3000610_c_y Random Forest  86.526316 Not Improved
 A3000617_c_y Random Forest 190.117647 Not Improved
 A3000619_c_y Random Forest  51.547826 Not Improved
 A3000623_c_y Random Forest  67.423423 Not Improved
 A3000629_a_y Random Forest  57.915152 Not Improved
 A3000631_b_y Random Forest  85.496403 Not Improved
 A3000647_c_y Random Forest  97.653495 Not Improved
 A3000661_c_y Random Forest  52.475096 Not Improved
 A3000668_a_y Random Forest  38.985099 Not Improved
 A3000670_a_y Random Forest  35.876923 Not Improved
 A3000673_c_y Random Forest  63.229630 Not Improved
 A3000682_c_y Random Forest 105.640625 Not Improved
 A3000683_a_y Random Forest  45.368072 Not Improved
 A3000693_c_y Random Forest  58.469565 Not Improved
 A3000699_c_y Random Forest  52.777429 Not Improved
 A3000726_c_y Random Forest  37.272727 Not Improved
 A4000001_a_y Random Forest 269.793103 Not Improved
 A4000032_a_y Random Forest 186.923767 Not Improved
 A4000039_a_y Random Forest  49.671766 Not Improved
 A4000047_a_y Random Forest 222.777778 Not Improved
 A4000077_a_y Random Forest 133.076233 Not Improved
 A4000081_a_y Random Forest  73.728814 Not Improved
 A4000089_a_y Random Forest  94.269807 Not Improved
 A4000091_a_y Random Forest  53.230769 Not Improved
 A4000096_a_y Random Forest 114.744884 Not Improved
 A4000099_c_y Random Forest  41.547325 Not Improved
 A4000178_a_y Random Forest 223.956204 Not Improved
 A4000189_a_y Random Forest 131.752212 Not Improved
 A4000209_a_y Random Forest  39.385516 Not Improved
 A4000250_a_y Random Forest 189.516588 Not Improved
 A4000260_a_y Random Forest 249.276596 Not Improved
 A4000263_a_y Random Forest 125.317269 Not Improved
 A4000298_b_y Random Forest 112.461538 Not Improved
 A4000309_a_y Random Forest  83.901840 Not Improved
 A4000311_a_y Random Forest  49.671053 Not Improved
 A4000323_c_y Random Forest  72.682927 Not Improved
 A4000335_c_y Random Forest  38.300885 Not Improved
 A4000337_c_y Random Forest 219.448276 Not Improved
 A4000371_b_y Random Forest 101.277311 Not Improved
 A4000379_c_y Random Forest  98.369427 Not Improved
 A4000382_c_y Random Forest  42.816327 Not Improved
 A4000392_c_y Random Forest  31.092437 Not Improved
 A4000394_c_y Random Forest  42.279570 Not Improved
 A4000396_c_y Random Forest  65.189189 Not Improved
 A4000399_c_y Random Forest  39.798319 Not Improved
 A4000411_a_y Random Forest  98.105263 Not Improved
 A4000430_c_y Random Forest 105.050000 Not Improved
 A4000441_a_y Random Forest  41.582938 Not Improved
 A4000451_b_y Random Forest  58.119658 Not Improved
 A4000453_b_y Random Forest  57.052632 Not Improved
 A4000462_a_y Random Forest  61.068077 Not Improved
 A4000463_b_y Random Forest  80.881356 Not Improved
 A4000473_b_y Random Forest  57.270588 Not Improved
 A4000502_c_y Random Forest  38.135593 Not Improved
 A4000506_c_y Random Forest 153.440000 Not Improved
 A4000509_a_y Random Forest  45.683453 Not Improved
 A4000511_a_y Random Forest 102.177215 Not Improved
 A4000514_a_y Random Forest  65.363636 Not Improved
 A4000516_c_y Random Forest 239.000000 Not Improved
 A4000523_c_y Random Forest 101.490909 Not Improved
 A4000527_b_y Random Forest 118.684564 Not Improved
 A4000529_a_y Random Forest 428.721805 Not Improved
 A4000530_b_y Random Forest 130.228571 Not Improved
 A4000531_c_y Random Forest  64.137931 Not Improved
 A4000532_c_y Random Forest  39.683453 Not Improved
 A4000534_c_y Random Forest  49.638554 Not Improved
 A4000535_c_y Random Forest  56.435644 Not Improved
 A4000540_a_y Random Forest  50.695825 Not Improved
 A4000543_b_y Random Forest  56.848138 Not Improved
 A4000548_c_y Random Forest  53.517241 Not Improved
 A4000550_a_y Random Forest  34.406756 Not Improved
 A4000559_c_y Random Forest  53.538462 Not Improved
 A4000561_c_y Random Forest  41.558442 Not Improved
 A4000575_b_y Random Forest  52.741427 Not Improved
 A4000578_c_y Random Forest  53.662745 Not Improved
 A4000581_c_y Random Forest  85.424084 Not Improved
 A4000582_c_y Random Forest  73.927273 Not Improved
 A4000589_c_y Random Forest  53.690444 Not Improved
 A4000594_c_y Random Forest  42.958580 Not Improved
 A4000600_c_y Random Forest  45.600000 Not Improved
 A4000604_c_y Random Forest  89.352941 Not Improved
 A4000607_a_y Random Forest  46.081955 Not Improved
 A4000609_c_y Random Forest  43.873016 Not Improved
 A4000612_c_y Random Forest  74.532110 Not Improved
 A4000616_c_y Random Forest 123.108504 Not Improved
 A4000617_c_y Random Forest 120.484848 Not Improved
 A4000618_b_y Random Forest  63.966881 Not Improved
 A4000619_c_y Random Forest  49.408333 Not Improved
 A4000622_c_y Random Forest  65.104558 Not Improved
 A4000623_a_y Random Forest  42.284295 Not Improved
 A4000624_c_y Random Forest  62.692124 Not Improved
 A4000628_c_y Random Forest 210.823529 Not Improved
 A4000633_b_y Random Forest 107.630402 Not Improved
 A4000636_b_y Random Forest  61.817757 Not Improved
 A4000641_a_y Random Forest  36.696682 Not Improved
 A4000644_c_y Random Forest  75.419355 Not Improved
 A4000653_c_y Random Forest  70.660832 Not Improved
 A4000654_c_y Random Forest  59.060403 Not Improved
 A4000659_c_y Random Forest  68.119241 Not Improved
 A4000668_c_y Random Forest  56.619718 Not Improved
A52000163_c_y Random Forest  61.191489 Not Improved
A52000228_c_y Random Forest  57.542857 Not Improved
A52000330_c_y Random Forest  73.408451 Not Improved
A52000424_c_y Random Forest  62.500000 Not Improved
A52000516_c_y Random Forest  44.979592 Not Improved
A52000517_c_y Random Forest  57.966102 Not Improved
A58000407_c_y Random Forest  62.113208 Not Improved
A58000451_c_y Random Forest  64.428571 Not Improved
A58000453_c_y Random Forest  64.883117 Not Improved
 A8000189_a_y Random Forest 309.000000 Not Improved
 A8000261_a_y Random Forest  65.721212 Not Improved
 A8000297_a_y Random Forest  48.529595 Not Improved
 A8000316_c_y Random Forest 232.081633 Not Improved
 A8000318_a_y Random Forest  98.333333 Not Improved
 A8000327_a_y Random Forest  61.699482 Not Improved
 A8000332_a_y Random Forest  50.609231 Not Improved
 A8000340_a_y Random Forest  40.908665 Not Improved
 A8000350_a_y Random Forest  45.862233 Not Improved
 A8000354_a_y Random Forest  99.371429 Not Improved
 A8000361_b_y Random Forest  88.882759 Not Improved
 A8000363_b_y Random Forest  73.069597 Not Improved
 A8000368_a_y Random Forest  53.134752 Not Improved
 A8000378_b_y Random Forest  54.442040 Not Improved
 A8000388_b_y Random Forest  47.350649 Not Improved
 A8000390_b_y Random Forest  30.790945 Not Improved
 A8000391_b_y Random Forest  57.623639 Not Improved
 A8000393_c_y Random Forest  58.702479 Not Improved
 A8000394_b_y Random Forest  42.535211 Not Improved
 A8000395_c_y Random Forest 100.859060 Not Improved
 A8000399_c_y Random Forest  51.397260 Not Improved
 A8000401_c_y Random Forest  43.436190 Not Improved
 A8000402_c_y Random Forest  62.511848 Not Improved
 A8000406_c_y Random Forest  61.352577 Not Improved
 A8000407_c_y Random Forest  62.502203 Not Improved
 A8000410_c_y Random Forest  58.862069 Not Improved
 A8000411_c_y Random Forest  54.201183 Not Improved
 A8000413_c_y Random Forest  51.262712 Not Improved
 A8000414_c_y Random Forest  48.785358 Not Improved
 A8000415_c_y Random Forest  61.215470 Not Improved
 A8000417_c_y Random Forest  48.434389 Not Improved
 A8000418_b_y Random Forest  49.438878 Not Improved
 A8000419_c_y Random Forest  53.194805 Not Improved
 A8000423_c_y Random Forest  50.696689 Not Improved
 A8000425_c_y Random Forest  43.732591 Not Improved
 A8000431_c_y Random Forest  62.098113 Not Improved
 A8010054_a_y Random Forest  47.895765 Not Improved
 A8010061_a_y Random Forest  47.279621 Not Improved
 A8010076_a_y Random Forest  38.254144 Not Improved
 A8010089_a_y Random Forest  40.677116 Not Improved
 A8010096_b_y Random Forest  68.631579 Not Improved
 A8010110_a_y Random Forest  38.693333 Not Improved
 A8010112_a_y Random Forest  37.989256 Not Improved
 A8010113_a_y Random Forest 110.247423 Not Improved
 A8010124_a_y Random Forest  47.387560 Not Improved
 A8010127_b_y Random Forest 153.770492 Not Improved
 A8010153_a_y Random Forest  37.553355 Not Improved
 A8010154_a_y Random Forest 195.836735 Not Improved
 A8010171_a_y Random Forest  48.576508 Not Improved
 A8010189_b_y Random Forest 153.315068 Not Improved
 A8010197_a_y Random Forest  39.682540 Not Improved
 A8010205_a_y Random Forest 394.739130 Not Improved
 A8010218_c_y Random Forest  35.483871 Not Improved
 A8010219_a_y Random Forest  45.914530 Not Improved
 A8010220_c_y Random Forest  45.207547 Not Improved
 A8010221_b_y Random Forest  70.000000 Not Improved
 A8010223_b_y Random Forest  40.173913 Not Improved
 A8010232_a_y Random Forest  72.989691 Not Improved
 A8010237_a_y Random Forest  43.151174 Not Improved
 A8010238_b_y Random Forest 177.270588 Not Improved
 A8010259_c_y Random Forest  68.176991 Not Improved
 A8010263_b_y Random Forest  44.155844 Not Improved
 A8010267_c_y Random Forest 171.238095 Not Improved
 A8010274_c_y Random Forest  35.185185 Not Improved
 A8010275_c_y Random Forest  80.717949 Not Improved
 A8010277_c_y Random Forest  35.466667 Not Improved
 A8010280_a_y Random Forest  85.813953 Not Improved
 A8010284_a_y Random Forest  47.111111 Not Improved
 A8010286_c_y Random Forest  56.405797 Not Improved
 A8010288_a_y Random Forest  55.507779 Not Improved
 A8010292_c_y Random Forest 146.758621 Not Improved
 A8010293_c_y Random Forest 173.750000 Not Improved
 A8010297_c_y Random Forest 220.888889 Not Improved
 A8010298_c_y Random Forest 214.000000 Not Improved
 A8010300_b_y Random Forest  35.407008 Not Improved
 A8010301_a_y Random Forest  51.507064 Not Improved
 A8010305_b_y Random Forest  69.536122 Not Improved
 A8010306_b_y Random Forest  49.911330 Not Improved
 A8010311_b_y Random Forest  38.417266 Not Improved
 A8010312_c_y Random Forest  80.300000 Not Improved
 A8010313_c_y Random Forest 112.606061 Not Improved
 A8010314_c_y Random Forest  78.247423 Not Improved
 A8010318_c_y Random Forest  41.619048 Not Improved
 A8010319_a_y Random Forest  40.043189 Not Improved
 A8010320_b_y Random Forest  34.815385 Not Improved
 A8010323_b_y Random Forest  59.154472 Not Improved
 A8010326_c_y Random Forest  54.413223 Not Improved
 A8010335_c_y Random Forest  54.601942 Not Improved
 A8010367_a_y Random Forest 123.079365 Not Improved
 A8010368_b_y Random Forest 186.607735 Not Improved
 A8010369_b_y Random Forest 112.608696 Not Improved
 A8010370_b_y Random Forest  98.107527 Not Improved
 A8010375_c_y Random Forest  61.327354 Not Improved
     T800_a_y Random Forest  85.632829 Not Improved
 T800-124_a_y Random Forest 178.884758 Not Improved

✅ Số series được cải thiện: 1/316

In [ ]:
!pip install pmdarima

Collecting pmdarima
  Downloading pmdarima-2.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (1.4.2)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (3.0.12)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (2.2.2)
Requirement already satisfied: scikit-learn>=0.22 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (1.6.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (1.14.1)
Requirement already satisfied: statsmodels>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (0.14.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (2.3.0)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (75.1.0)
Requirement already satisfied: packaging>=17.1 in /usr/local/lib/python3.11/dist-packages (from pmdarima) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.19->pmdarima) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.19->pmdarima) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.19->pmdarima) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.22->pmdarima) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.11/dist-packages (from statsmodels>=0.13.2->pmdarima) (1.0.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=0.19->pmdarima) (1.17.0)
Downloading pmdarima-2.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 39.6 MB/s eta 0:00:00
Installing collected packages: pmdarima
Successfully installed pmdarima-2.0.4

### Fine-tuning 5th time

In [ ]:
import numpy as np
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import GridSearchCV

# Load dữ liệu
df_final = pd.read_csv("Series_Hierarchical.csv", index_col=0, parse_dates=True)

# Kiểm tra nếu df_fine_tuned_v4 có tồn tại
if 'df_fine_tuned_v4' not in locals() or df_fine_tuned_v4 is None:
    df_fine_tuned_v4 = pd.DataFrame(columns=["Series", "Best Model", "New WMAPE", "Status"])

# Kiểm tra cột "Status"
if "Status" not in df_fine_tuned_v4.columns:
    df_fine_tuned_v4["Status"] = "Not Improved"

# Lọc các series chưa đạt yêu cầu
df_not_improved = df_fine_tuned_v4[df_fine_tuned_v4["Status"] == "Not Improved"]
series_to_finetune = df_not_improved["Series"].tolist()

fine_tuned_results_v5 = []

for col in series_to_finetune:
    series = df_final[col].dropna()

    # **Kiểm tra nếu dữ liệu quá ít (< 6 tháng) thì bỏ qua**
    if len(series) < 6:
        print(f"⚠️ Series {col} có quá ít dữ liệu, bỏ qua!")
        continue

    train = series.iloc[:-6]
    test = series.iloc[-6:]

    best_wmape = np.inf
    best_model = None
    best_forecast = None

    # **1️⃣ Holt-Winters (Tối ưu lại)**
    for trend in ['add', 'mul']:
        for seasonal in ['add', 'mul']:
            try:
                model_hw = ExponentialSmoothing(train, trend=trend, seasonal=seasonal, seasonal_periods=6, damped_trend=True).fit()
                forecast_hw = model_hw.forecast(6)
                wmape_hw = sum(abs(forecast_hw - test)) / sum(test) * 100

                if wmape_hw < best_wmape:
                    best_wmape = wmape_hw
                    best_model = f"Holt-Winters ({trend}, {seasonal})"
                    best_forecast = forecast_hw
            except:
                pass

    # **2️⃣ ARIMA với nhiều tham số**
    arima_params = [(1,1,0), (0,1,1), (1,1,1), (2,1,1), (2,1,2)]
    for params in arima_params:
        try:
            model_arima = ARIMA(train, order=params).fit()
            forecast_arima = model_arima.forecast(6)
            wmape_arima = sum(abs(forecast_arima - test)) / sum(test) * 100

            if wmape_arima < best_wmape:
                best_wmape = wmape_arima
                best_model = f"ARIMA {params}"
                best_forecast = forecast_arima
        except:
            pass

    # **3️⃣ Random Forest (Grid Search Tuning)**
    try:
        scaler = MinMaxScaler(feature_range=(0, 1))
        train_scaled = scaler.fit_transform(train.values.reshape(-1, 1))

        X_train = np.arange(len(train_scaled)).reshape(-1, 1)
        y_train = train_scaled.flatten()
        X_test = np.arange(len(train_scaled), len(train_scaled) + 6).reshape(-1, 1)

        param_grid_rf = {
            'n_estimators': [50, 100, 200],
            'max_depth': [5, 10, None],
            'min_samples_split': [2, 5, 10]
        }

        model_rf = RandomForestRegressor()
        grid_search_rf = GridSearchCV(model_rf, param_grid_rf, cv=3, n_jobs=-1)
        grid_search_rf.fit(X_train, y_train)

        best_rf = grid_search_rf.best_estimator_
        forecast_rf = best_rf.predict(X_test)
        forecast_rf = scaler.inverse_transform(forecast_rf.reshape(-1, 1)).flatten()

        wmape_rf = sum(abs(forecast_rf - test)) / sum(test) * 100

        if wmape_rf < best_wmape:
            best_wmape = wmape_rf
            best_model = f"Random Forest (Tuned)"
            best_forecast = forecast_rf
    except:
        pass

    # **4️⃣ XGBoost (Grid Search Tuning)**
    try:
        param_grid_xgb = {
            'n_estimators': [50, 100, 200],
            'learning_rate': [0.01, 0.1, 0.2],
            'max_depth': [3, 5, 7]
        }

        model_xgb = XGBRegressor()
        grid_search_xgb = GridSearchCV(model_xgb, param_grid_xgb, cv=3, n_jobs=-1)
        grid_search_xgb.fit(X_train, y_train)

        best_xgb = grid_search_xgb.best_estimator_
        forecast_xgb = best_xgb.predict(X_test)
        forecast_xgb = scaler.inverse_transform(forecast_xgb.reshape(-1, 1)).flatten()

        wmape_xgb = sum(abs(forecast_xgb - test)) / sum(test) * 100

        if wmape_xgb < best_wmape:
            best_wmape = wmape_xgb
            best_model = f"XGBoost (Tuned)"
            best_forecast = forecast_xgb
    except:
        pass

    # **Lưu kết quả**
    fine_tuned_results_v5.append({
        "Series": col,
        "Best Model": best_model,
        "New WMAPE": best_wmape,
        "Status": "Improved" if best_wmape < 30 else "Not Improved"
    })

# **Hiển thị kết quả Fine-Tuning Lần 5**
df_fine_tuned_v5 = pd.DataFrame(fine_tuned_results_v5)
print("\n=== 🔥 Fine-Tuning Lần 5 (Holt-Winters + ARIMA + RF + XGBoost) ===")
print(df_fine_tuned_v5.to_string(index=False))

# **Số series được cải thiện**
num_improved_v5 = df_fine_tuned_v5[df_fine_tuned_v5["Status"] == "Improved"].shape[0]
print(f"\n✅ Số series được cải thiện: {num_improved_v5}/{len(series_to_finetune)}")

=== 🔥 Fine-Tuning Lần 5 (Holt-Winters + ARIMA + RF + XGBoost) ===
       Series            Best Model  New WMAPE       Status
 A2000135_a_y       XGBoost (Tuned)  94.923651 Not Improved
 A2000136_a_y Random Forest (Tuned) 107.525207 Not Improved
 A2000329_a_y Random Forest (Tuned)  55.059794 Not Improved
 A2000346_a_y Random Forest (Tuned)  67.907900 Not Improved
 A2000355_a_y Random Forest (Tuned) 104.299395 Not Improved
 A2000370_a_y Random Forest (Tuned)  56.688644 Not Improved
 A2000388_a_y Random Forest (Tuned)  73.187173 Not Improved
 A2000409_b_y       XGBoost (Tuned) 218.805021 Not Improved
 A2000410_a_y       XGBoost (Tuned)  96.638510 Not Improved
 A2000416_a_y Random Forest (Tuned)  49.000831 Not Improved
 A2000442_a_y       XGBoost (Tuned)  46.234580 Not Improved
 A2000461_a_y Random Forest (Tuned)  34.158491 Not Improved
 A2000484_b_y Random Forest (Tuned)  41.280576 Not Improved
 A2000485_a_y Random Forest (Tuned)  37.423313 Not Improved
 A2000488_a_y       XGBoost (Tuned)  34.746628 Not Improved
 A2000490_b_y       XGBoost (Tuned)  93.370560 Not Improved
 A2000491_b_y Random Forest (Tuned)  85.289599 Not Improved
 A2000494_b_y       XGBoost (Tuned)  67.725622 Not Improved
 A2000495_b_y Random Forest (Tuned) 118.979310 Not Improved
 A2000497_b_y       XGBoost (Tuned)  30.704577 Not Improved
 A2000506_b_y       XGBoost (Tuned) 126.028501 Not Improved
 A2000509_a_y Random Forest (Tuned)  58.299284 Not Improved
 A2000510_a_y Random Forest (Tuned)  52.120704 Not Improved
 A2000515_a_y Random Forest (Tuned)  40.566038 Not Improved
 A2000516_a_y Random Forest (Tuned)  41.043084 Not Improved
 A2000517_a_y Random Forest (Tuned)  42.857143 Not Improved
 A2000518_a_y Random Forest (Tuned)  34.381885 Not Improved
 A2000519_a_y Random Forest (Tuned)  38.394779 Not Improved
 A2000527_b_y Random Forest (Tuned) 121.749717 Not Improved
 A2000529_c_y Random Forest (Tuned)  95.563177 Not Improved
 A2000534_c_y       XGBoost (Tuned) 207.662567 Not Improved
 A2000535_c_y       XGBoost (Tuned) 165.649143 Not Improved
 A2000539_a_y       XGBoost (Tuned)  34.795217 Not Improved
 A2000540_a_y       XGBoost (Tuned)  40.365107 Not Improved
 A2000548_b_y Random Forest (Tuned) 119.247669 Not Improved
 A2000550_c_y Random Forest (Tuned)  69.277778 Not Improved
 A2000554_a_y Random Forest (Tuned)  35.581839 Not Improved
 A2000555_b_y Random Forest (Tuned) 418.285714 Not Improved
 A2000561_a_y       XGBoost (Tuned)  63.921650 Not Improved
 A2000562_a_y       XGBoost (Tuned)  29.948518     Improved
 A2000566_b_y Random Forest (Tuned)  47.296000 Not Improved
 A2000567_c_y Random Forest (Tuned)  39.495798 Not Improved
 A2000568_c_y Random Forest (Tuned)  51.918367 Not Improved
 A2000572_c_y Random Forest (Tuned)  68.676923 Not Improved
 A2000576_b_y       XGBoost (Tuned)  42.500053 Not Improved
 A2000584_c_y Random Forest (Tuned)  24.507042     Improved
 A2000595_c_y       XGBoost (Tuned)  41.772152 Not Improved
 A2000596_b_y       XGBoost (Tuned)  42.307692 Not Improved
 A2000609_b_y       XGBoost (Tuned) 126.365428 Not Improved
 A2000610_b_y Random Forest (Tuned)  87.033716 Not Improved
 A2000611_b_y Random Forest (Tuned)  43.620586 Not Improved
 A2000614_c_y Random Forest (Tuned)  35.193133 Not Improved
 A2000617_b_y Random Forest (Tuned) 119.627789 Not Improved
 A2000618_b_y       XGBoost (Tuned)  68.513906 Not Improved
 A2000628_a_y Random Forest (Tuned)  45.825692 Not Improved
 A2000629_a_y Random Forest (Tuned)  34.773259 Not Improved
 A2000635_b_y Random Forest (Tuned)  47.049853 Not Improved
 A2000636_b_y Random Forest (Tuned)  49.902918 Not Improved
 A2000649_a_y       XGBoost (Tuned)  40.608402 Not Improved
 A2000650_a_y       XGBoost (Tuned)  46.879732 Not Improved
 A2000652_b_y Random Forest (Tuned)  42.811682 Not Improved
 A2000655_c_y Random Forest (Tuned)  49.005848 Not Improved
 A2000657_c_y Random Forest (Tuned)  60.723164 Not Improved
 A2000658_c_y Random Forest (Tuned)  60.126984 Not Improved
 A2000660_c_y Random Forest (Tuned)  45.797101 Not Improved
 A2000661_c_y Random Forest (Tuned)  70.977346 Not Improved
 A2000663_c_y Random Forest (Tuned)  50.651054 Not Improved
 A2000664_c_y Random Forest (Tuned)  52.519722 Not Improved
 A2000670_c_y Random Forest (Tuned)  45.513514 Not Improved
 A2000673_c_y       XGBoost (Tuned)  50.565155 Not Improved
 A2000674_c_y       XGBoost (Tuned)  48.183486 Not Improved
 A2000679_c_y Random Forest (Tuned)  57.070028 Not Improved
 A2000683_c_y Random Forest (Tuned)  57.081916 Not Improved
 A2000690_c_y Random Forest (Tuned)  79.103614 Not Improved
 A2000691_c_y Random Forest (Tuned)  77.585831 Not Improved
 A2000692_c_y Random Forest (Tuned)  50.336957 Not Improved
 A2000693_c_y Random Forest (Tuned)  38.071661 Not Improved
 A2000695_c_y Random Forest (Tuned)  45.742857 Not Improved
 A2000701_c_y Random Forest (Tuned)  45.421687 Not Improved
 A2000702_c_y Random Forest (Tuned)  31.668626 Not Improved
 A2000705_c_y Random Forest (Tuned)  50.356495 Not Improved
 A2900003_c_y Random Forest (Tuned) 105.209344 Not Improved
 A2900004_c_y Random Forest (Tuned)  76.214258 Not Improved
 A2900005_c_y Random Forest (Tuned)  31.944444 Not Improved
 A2900010_c_y Random Forest (Tuned)  42.690058 Not Improved
 A2900011_c_y Random Forest (Tuned)  45.785877 Not Improved
 A2900013_b_y       XGBoost (Tuned)  74.491437 Not Improved
 A2900017_b_y       XGBoost (Tuned)  49.744936 Not Improved
 A2900021_c_y Random Forest (Tuned)  62.428577 Not Improved
 A2C00204_c_y Random Forest (Tuned)  53.961538 Not Improved
 A3000030_a_y       XGBoost (Tuned) 120.143460 Not Improved
 A3000054_b_y Random Forest (Tuned)  59.465310 Not Improved
 A3000063_a_y Random Forest (Tuned)  83.079068 Not Improved
 A3000135_a_y Random Forest (Tuned) 282.242720 Not Improved
 A3000140_a_y Random Forest (Tuned) 114.260884 Not Improved
 A3000174_a_y Random Forest (Tuned) 150.689383 Not Improved
 A3000213_a_y Random Forest (Tuned)  96.878130 Not Improved
 A3000241_a_y Random Forest (Tuned)  69.146254 Not Improved
 A3000259_a_y Random Forest (Tuned)  87.211650 Not Improved
 A3000261_b_y Random Forest (Tuned)  65.686747 Not Improved
 A3000278_b_y Random Forest (Tuned) 100.061538 Not Improved
 A3000308_a_y Random Forest (Tuned)  78.772137 Not Improved
 A3000335_b_y Random Forest (Tuned)  37.024221 Not Improved
 A3000336_a_y       XGBoost (Tuned)  59.534844 Not Improved
 A3000337_a_y Random Forest (Tuned)  64.066629 Not Improved
 A3000338_a_y Random Forest (Tuned) 309.468730 Not Improved
 A3000339_a_y Random Forest (Tuned)  36.813591 Not Improved
 A3000343_a_y       XGBoost (Tuned) 270.914291 Not Improved
A3000366C_c_y       XGBoost (Tuned)  36.799562 Not Improved
 A3000604_a_y       XGBoost (Tuned)  72.501688 Not Improved
 A3000609_c_y       XGBoost (Tuned) 116.923003 Not Improved
 A3000610_c_y       XGBoost (Tuned)  84.713665 Not Improved
 A3000617_c_y       XGBoost (Tuned) 160.049753 Not Improved
 A3000619_c_y Random Forest (Tuned)  52.465135 Not Improved
 A3000623_c_y Random Forest (Tuned)  69.471471 Not Improved
 A3000629_a_y Random Forest (Tuned)  62.317056 Not Improved
 A3000631_b_y Random Forest (Tuned)  88.470045 Not Improved
 A3000647_c_y Random Forest (Tuned)  82.475202 Not Improved
 A3000661_c_y Random Forest (Tuned)  29.885057     Improved
 A3000668_a_y Random Forest (Tuned)  38.493377 Not Improved
 A3000670_a_y Random Forest (Tuned)  33.045217 Not Improved
 A3000673_c_y Random Forest (Tuned)  66.538639 Not Improved
 A3000682_c_y Random Forest (Tuned) 105.229608 Not Improved
 A3000683_a_y Random Forest (Tuned)  41.792059 Not Improved
 A3000693_c_y Random Forest (Tuned)  54.191304 Not Improved
 A3000699_c_y Random Forest (Tuned)  48.539185 Not Improved
 A3000726_c_y Random Forest (Tuned)  37.272727 Not Improved
 A4000001_a_y Random Forest (Tuned) 276.114012 Not Improved
 A4000032_a_y Random Forest (Tuned) 185.417040 Not Improved
 A4000039_a_y Random Forest (Tuned)  48.634195 Not Improved
 A4000047_a_y       XGBoost (Tuned) 200.374667 Not Improved
 A4000077_a_y Random Forest (Tuned) 120.342685 Not Improved
 A4000081_a_y Random Forest (Tuned)  81.627119 Not Improved
 A4000089_a_y Random Forest (Tuned)  89.036403 Not Improved
 A4000091_a_y Random Forest (Tuned)  52.233100 Not Improved
 A4000096_a_y Random Forest (Tuned) 106.575640 Not Improved
 A4000099_c_y Random Forest (Tuned)  42.814815 Not Improved
 A4000178_a_y Random Forest (Tuned) 231.839449 Not Improved
 A4000189_a_y Random Forest (Tuned) 187.519361 Not Improved
 A4000209_a_y Random Forest (Tuned)  39.283102 Not Improved
 A4000250_a_y       XGBoost (Tuned) 193.935362 Not Improved
 A4000260_a_y Random Forest (Tuned) 257.956383 Not Improved
 A4000263_a_y       XGBoost (Tuned) 116.897791 Not Improved
 A4000298_b_y Random Forest (Tuned) 123.500000 Not Improved
 A4000309_a_y Random Forest (Tuned) 103.595620 Not Improved
 A4000311_a_y Random Forest (Tuned)  49.671053 Not Improved
 A4000323_c_y Random Forest (Tuned)  78.154644 Not Improved
 A4000335_c_y Random Forest (Tuned)  38.230088 Not Improved
 A4000337_c_y Random Forest (Tuned) 252.241379 Not Improved
 A4000371_b_y Random Forest (Tuned) 112.336174 Not Improved
 A4000379_c_y       XGBoost (Tuned)  94.163431 Not Improved
 A4000382_c_y Random Forest (Tuned)  40.816327 Not Improved
 A4000392_c_y Random Forest (Tuned)  31.092437 Not Improved
 A4000394_c_y Random Forest (Tuned)  42.709677 Not Improved
 A4000396_c_y       XGBoost (Tuned)  63.406977 Not Improved
 A4000399_c_y       XGBoost (Tuned)  36.226104 Not Improved
 A4000411_a_y Random Forest (Tuned)  87.275158 Not Improved
 A4000430_c_y Random Forest (Tuned)  83.927381 Not Improved
 A4000441_a_y       XGBoost (Tuned)  40.629467 Not Improved
 A4000451_b_y Random Forest (Tuned)  58.119658 Not Improved
 A4000453_b_y Random Forest (Tuned)  57.026729 Not Improved
 A4000462_a_y Random Forest (Tuned)  54.642083 Not Improved
 A4000463_b_y Random Forest (Tuned)  83.364535 Not Improved
 A4000473_b_y Random Forest (Tuned)  57.458824 Not Improved
 A4000502_c_y Random Forest (Tuned)  38.135593 Not Improved
 A4000506_c_y       XGBoost (Tuned) 122.158600 Not Improved
 A4000509_a_y Random Forest (Tuned)  66.140664 Not Improved
 A4000511_a_y Random Forest (Tuned)  98.790115 Not Improved
 A4000514_a_y       XGBoost (Tuned)  75.238846 Not Improved
 A4000516_c_y Random Forest (Tuned) 247.345250 Not Improved
 A4000523_c_y Random Forest (Tuned)  88.238571 Not Improved
 A4000527_b_y Random Forest (Tuned) 123.386385 Not Improved
 A4000529_a_y       XGBoost (Tuned) 384.618188 Not Improved
 A4000530_b_y Random Forest (Tuned)  83.868624 Not Improved
 A4000531_c_y Random Forest (Tuned)  69.931034 Not Improved
 A4000532_c_y       XGBoost (Tuned)  38.039212 Not Improved
 A4000534_c_y Random Forest (Tuned)  48.004016 Not Improved
 A4000535_c_y Random Forest (Tuned)  56.435644 Not Improved
 A4000540_a_y       XGBoost (Tuned)  40.406450 Not Improved
 A4000543_b_y       XGBoost (Tuned)  53.008596 Not Improved
 A4000548_c_y       XGBoost (Tuned)  33.014942 Not Improved
 A4000550_a_y       XGBoost (Tuned)  44.055537 Not Improved
 A4000559_c_y       XGBoost (Tuned)  61.228151 Not Improved
 A4000561_c_y       XGBoost (Tuned)  48.418833 Not Improved
 A4000575_b_y Random Forest (Tuned)  42.414239 Not Improved
 A4000578_c_y Random Forest (Tuned)  48.592375 Not Improved
 A4000581_c_y Random Forest (Tuned)  85.329843 Not Improved
 A4000582_c_y Random Forest (Tuned)  70.177273 Not Improved
 A4000589_c_y Random Forest (Tuned)  51.407806 Not Improved
 A4000594_c_y Random Forest (Tuned)  42.958580 Not Improved
 A4000600_c_y Random Forest (Tuned)  45.600000 Not Improved
 A4000604_c_y Random Forest (Tuned)  53.405881 Not Improved
 A4000607_a_y Random Forest (Tuned)  44.787922 Not Improved
 A4000609_c_y Random Forest (Tuned)  45.320635 Not Improved
 A4000612_c_y Random Forest (Tuned)  54.053827 Not Improved
 A4000616_c_y Random Forest (Tuned)  94.481004 Not Improved
 A4000617_c_y Random Forest (Tuned)  91.338950 Not Improved
 A4000618_b_y Random Forest (Tuned)  72.290980 Not Improved
 A4000619_c_y Random Forest (Tuned)  50.466667 Not Improved
 A4000622_c_y Random Forest (Tuned)  57.948591 Not Improved
 A4000623_a_y Random Forest (Tuned)  41.383810 Not Improved
 A4000624_c_y       XGBoost (Tuned)  42.166342 Not Improved
 A4000628_c_y Random Forest (Tuned) 174.299720 Not Improved
 A4000633_b_y Random Forest (Tuned)  78.936870 Not Improved
 A4000636_b_y Random Forest (Tuned)  46.378271 Not Improved
 A4000641_a_y Random Forest (Tuned)  36.434834 Not Improved
 A4000644_c_y Random Forest (Tuned)  71.612903 Not Improved
 A4000653_c_y Random Forest (Tuned)  70.695842 Not Improved
 A4000654_c_y Random Forest (Tuned)  63.140940 Not Improved
 A4000659_c_y Random Forest (Tuned)  67.815718 Not Improved
 A4000668_c_y Random Forest (Tuned)  55.301408 Not Improved
A52000163_c_y Random Forest (Tuned)  37.478170 Not Improved
A52000228_c_y       XGBoost (Tuned)  51.428571 Not Improved
A52000330_c_y Random Forest (Tuned)  80.992193 Not Improved
A52000424_c_y       XGBoost (Tuned)  68.328838 Not Improved
A52000516_c_y Random Forest (Tuned)  41.551020 Not Improved
A52000517_c_y Random Forest (Tuned)  49.152542 Not Improved
A58000407_c_y       XGBoost (Tuned)  62.133958 Not Improved
A58000451_c_y Random Forest (Tuned)  64.285714 Not Improved
A58000453_c_y Random Forest (Tuned)  61.923679 Not Improved
 A8000189_a_y Random Forest (Tuned) 321.011054 Not Improved
 A8000261_a_y Random Forest (Tuned)  63.395267 Not Improved
 A8000297_a_y Random Forest (Tuned)  48.500709 Not Improved
 A8000316_c_y Random Forest (Tuned) 241.704205 Not Improved
 A8000318_a_y Random Forest (Tuned) 102.904809 Not Improved
 A8000327_a_y       XGBoost (Tuned)  51.363013 Not Improved
 A8000332_a_y       XGBoost (Tuned)  54.885085 Not Improved
 A8000340_a_y       XGBoost (Tuned)  38.652689 Not Improved
 A8000350_a_y       XGBoost (Tuned)  32.918130 Not Improved
 A8000354_a_y       XGBoost (Tuned)  63.276781 Not Improved
 A8000361_b_y Random Forest (Tuned)  91.489655 Not Improved
 A8000363_b_y       XGBoost (Tuned)  67.765568 Not Improved
 A8000368_a_y       XGBoost (Tuned)  32.763758 Not Improved
 A8000378_b_y Random Forest (Tuned)  50.231839 Not Improved
 A8000388_b_y       XGBoost (Tuned)  46.560689 Not Improved
 A8000390_b_y       XGBoost (Tuned)  31.310590 Not Improved
 A8000391_b_y Random Forest (Tuned)  29.053825     Improved
 A8000393_c_y       XGBoost (Tuned)  42.220959 Not Improved
 A8000394_b_y       XGBoost (Tuned)  43.954505 Not Improved
 A8000395_c_y       XGBoost (Tuned)  82.395853 Not Improved
 A8000399_c_y       XGBoost (Tuned)  49.559756 Not Improved
 A8000401_c_y Random Forest (Tuned)  42.582857 Not Improved
 A8000402_c_y Random Forest (Tuned)  26.256566     Improved
 A8000406_c_y       XGBoost (Tuned)  58.986022 Not Improved
 A8000407_c_y Random Forest (Tuned)  60.317181 Not Improved
 A8000410_c_y       XGBoost (Tuned)  56.445987 Not Improved
 A8000411_c_y       XGBoost (Tuned)  46.968702 Not Improved
 A8000413_c_y Random Forest (Tuned)  49.762712 Not Improved
 A8000414_c_y Random Forest (Tuned)  53.557404 Not Improved
 A8000415_c_y Random Forest (Tuned)  60.817680 Not Improved
 A8000417_c_y Random Forest (Tuned)  53.140271 Not Improved
 A8000418_b_y Random Forest (Tuned)  54.476954 Not Improved
 A8000419_c_y Random Forest (Tuned)  58.623377 Not Improved
 A8000423_c_y Random Forest (Tuned)  46.585430 Not Improved
 A8000425_c_y Random Forest (Tuned)  43.732591 Not Improved
 A8000431_c_y Random Forest (Tuned)  65.098113 Not Improved
 A8010054_a_y Random Forest (Tuned)  44.670643 Not Improved
 A8010061_a_y       XGBoost (Tuned)  64.169449 Not Improved
 A8010076_a_y       XGBoost (Tuned)  40.029428 Not Improved
 A8010089_a_y Random Forest (Tuned)  33.997567 Not Improved
 A8010096_b_y Random Forest (Tuned)  60.447306 Not Improved
 A8010110_a_y       XGBoost (Tuned)  38.019871 Not Improved
 A8010112_a_y       XGBoost (Tuned)  37.989256 Not Improved
 A8010113_a_y Random Forest (Tuned)  92.452112 Not Improved
 A8010124_a_y       XGBoost (Tuned)  34.955287 Not Improved
 A8010127_b_y Random Forest (Tuned) 122.160578 Not Improved
 A8010153_a_y Random Forest (Tuned)  35.940474 Not Improved
 A8010154_a_y Random Forest (Tuned) 189.224490 Not Improved
 A8010171_a_y       XGBoost (Tuned)  44.961937 Not Improved
 A8010189_b_y Random Forest (Tuned) 147.932930 Not Improved
 A8010197_a_y Random Forest (Tuned)  40.174315 Not Improved
 A8010205_a_y       XGBoost (Tuned) 387.537467 Not Improved
 A8010218_c_y Random Forest (Tuned)  35.483871 Not Improved
 A8010219_a_y Random Forest (Tuned)  49.637713 Not Improved
 A8010220_c_y       XGBoost (Tuned)  43.396226 Not Improved
 A8010221_b_y Random Forest (Tuned)  70.074074 Not Improved
 A8010223_b_y Random Forest (Tuned)  40.358696 Not Improved
 A8010232_a_y Random Forest (Tuned)  74.247423 Not Improved
 A8010237_a_y       XGBoost (Tuned)  40.748188 Not Improved
 A8010238_b_y       XGBoost (Tuned) 222.579085 Not Improved
 A8010259_c_y       XGBoost (Tuned)  64.047451 Not Improved
 A8010263_b_y       XGBoost (Tuned)  45.153333 Not Improved
 A8010267_c_y       XGBoost (Tuned) 280.550494 Not Improved
 A8010274_c_y Random Forest (Tuned)  35.185185 Not Improved
 A8010275_c_y Random Forest (Tuned)  74.769231 Not Improved
 A8010277_c_y Random Forest (Tuned)  51.775853 Not Improved
 A8010280_a_y Random Forest (Tuned)  80.093023 Not Improved
 A8010284_a_y Random Forest (Tuned)  46.791837 Not Improved
 A8010286_c_y       XGBoost (Tuned)  48.769528 Not Improved
 A8010288_a_y       XGBoost (Tuned)  52.024839 Not Improved
 A8010292_c_y Random Forest (Tuned) 138.137931 Not Improved
 A8010293_c_y Random Forest (Tuned) 148.389286 Not Improved
 A8010297_c_y Random Forest (Tuned) 197.777778 Not Improved
 A8010298_c_y Random Forest (Tuned) 193.500000 Not Improved
 A8010300_b_y Random Forest (Tuned)  33.692722 Not Improved
 A8010301_a_y Random Forest (Tuned)  52.005945 Not Improved
 A8010305_b_y       XGBoost (Tuned)  62.299251 Not Improved
 A8010306_b_y Random Forest (Tuned)  49.812808 Not Improved
 A8010311_b_y Random Forest (Tuned)  38.417266 Not Improved
 A8010312_c_y       XGBoost (Tuned)  75.187516 Not Improved
 A8010313_c_y       XGBoost (Tuned)  81.050295 Not Improved
 A8010314_c_y       XGBoost (Tuned)  72.164948 Not Improved
 A8010318_c_y       XGBoost (Tuned)  34.727460 Not Improved
 A8010319_a_y Random Forest (Tuned)  38.039867 Not Improved
 A8010320_b_y       XGBoost (Tuned)  33.589744 Not Improved
 A8010323_b_y Random Forest (Tuned)  22.805672     Improved
 A8010326_c_y Random Forest (Tuned)  28.877629     Improved
 A8010335_c_y Random Forest (Tuned)  52.530744 Not Improved
 A8010367_a_y       XGBoost (Tuned)  73.255436 Not Improved
 A8010368_b_y       XGBoost (Tuned) 169.487244 Not Improved
 A8010369_b_y       XGBoost (Tuned) 112.265297 Not Improved
 A8010370_b_y Random Forest (Tuned)  93.003584 Not Improved
 A8010375_c_y       XGBoost (Tuned)  52.843780 Not Improved
     T800_a_y Random Forest (Tuned)  87.626388 Not Improved
 T800-124_a_y Random Forest (Tuned) 190.216099 Not Improved

✅ Số series được cải thiện: 7/315

In [ ]:
!pip install scikit-optimize

## Code Block 3: Forecast Model cho Nhóm Z z (CV ≥ 0.84)

In [ ]:
import pandas as pd
import numpy as np
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
import warnings
warnings.filterwarnings("ignore")

# Load dữ liệu
df_final = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df_final.index = pd.to_datetime(df_final.index)

# Lọc các cột thuộc Group X (tên kết thúc bằng _x)
group_x_cols = [col for col in df_final.columns if col != 'Total' and col.endswith('_z')]
forecast_periods = 6
wmape_threshold = 0.35  # Yêu cầu: wMAPE < 25%

series_results = []
overall_total_abs_error = 0.0
overall_total_actual = 0.0

trend_threshold = 0.05  # Ngưỡng xác định xu hướng

# Các cấu hình ARIMA non-seasonal cần thử
non_seasonal_orders = [(1,1,0), (0,1,1), (1,1,1), (2,1,1)]
# Các cấu hình SARIMA cần thử (non-seasonal_order, seasonal_order)
seasonal_orders = [((1,1,0), (1,0,1,12)), ((0,1,1), (1,0,1,12))]

for col in group_x_cols:
    series = df_final[col]
    if len(series) < forecast_periods + 1:
        series_results.append({
            "Series": col,
            "Model": None,
            "wMAPE": None,
            "Status": "Invalid: Not enough data"
        })
        continue

    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]
    test_arr = np.array(test)

    # Tính xu hướng: so sánh giá trị đầu và cuối của train
    initial = train.iloc[0]
    final = train.iloc[-1]
    trend_ratio = abs(final - initial) / (abs(initial) + 1e-8)

    candidate_models = []

    # Thử các mô hình ES
    if trend_ratio > trend_threshold:
        try:
            model_add = ExponentialSmoothing(train, trend='add', seasonal=None, damped_trend=True).fit()
            forecast_add = model_add.forecast(forecast_periods)
            candidate_models.append(("Holt's Add", model_add, np.array(forecast_add)))
        except Exception as e:
            pass
        if (train > 0).all():
            try:
                model_mult = ExponentialSmoothing(train, trend='mul', seasonal=None, damped_trend=True).fit()
                forecast_mult = model_mult.forecast(forecast_periods)
                candidate_models.append(("Holt's Mul", model_mult, np.array(forecast_mult)))
            except Exception as e:
                pass
    else:
        try:
            model_simple = ExponentialSmoothing(train, trend=None, seasonal=None).fit()
            forecast_simple = model_simple.forecast(forecast_periods)
            candidate_models.append(("Simple ES", model_simple, np.array(forecast_simple)))
        except Exception as e:
            pass

    # Chọn mô hình ES tốt nhất dựa trên tổng lỗi
    best_model_name = None
    best_error = np.inf
    best_forecast = None
    for name, model, forecast_arr in candidate_models:
        if np.sum(test_arr) == 0:
            continue
        error = np.sum(np.abs(forecast_arr - test_arr))
        if error < best_error:
            best_error = error
            best_forecast = forecast_arr
            best_model_name = name
    current_wmape = best_error / np.sum(test_arr) if np.sum(test_arr) > 0 else np.inf

    # Nếu wMAPE từ ES >= threshold, thử ARIMA grid search
    if current_wmape >= wmape_threshold:
        # Thử ARIMA non-seasonal
        for order in non_seasonal_orders:
            try:
                model_arima = ARIMA(train, order=order).fit()
                forecast_arima = model_arima.forecast(forecast_periods)
                forecast_arima = np.array(forecast_arima)
                error_arima = np.sum(np.abs(forecast_arima - test_arr))
                wmape_arima = error_arima / np.sum(test_arr)
                if wmape_arima < current_wmape:
                    best_model_name = f"ARIMA{order}"
                    best_error = error_arima
                    best_forecast = forecast_arima
                    current_wmape = wmape_arima
            except Exception as e:
                continue
        # Thử SARIMA nếu độ dài train đủ (> seasonal_period)
        seasonal_period = 12
        if len(train) > seasonal_period:
            for non_seasonal_order, seasonal_order in seasonal_orders:
                try:
                    model_sarima = SARIMAX(train, order=non_seasonal_order, seasonal_order=seasonal_order).fit(disp=False)
                    forecast_sarima = model_sarima.forecast(forecast_periods)
                    forecast_sarima = np.array(forecast_sarima)
                    error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                    wmape_sarima = error_sarima / np.sum(test_arr)
                    if wmape_sarima < current_wmape:
                        best_model_name = f"SARIMA{non_seasonal_order, seasonal_order}"
                        best_error = error_sarima
                        best_forecast = forecast_sarima
                        current_wmape = wmape_sarima
                except Exception as e:
                    continue

    if np.sum(test_arr) == 0:
        series_results.append({
            "Series": col,
            "Model": best_model_name,
            "wMAPE": None,
            "Status": "Invalid: Test sum zero"
        })
        continue

    status = "Valid" if current_wmape < wmape_threshold else "Invalid: wMAPE too high"

    if status == "Valid":
        overall_total_abs_error += best_error
        overall_total_actual += np.sum(test_arr)

    series_results.append({
        "Series": col,
        "Model": best_model_name,
        "wMAPE": current_wmape,
        "Status": status
    })

overall_wmape = overall_total_abs_error / overall_total_actual if overall_total_actual != 0 else np.nan

df_results = pd.DataFrame(series_results)
df_results["wMAPE (%)"] = df_results["wMAPE"].apply(lambda x: f"{x:.2%}" if pd.notnull(x) else None)

summary = {
    "Group": "X (CV < 0.34)",
    "Total Series": len(group_x_cols),
    "Valid Series": df_results[df_results["Status"]=="Valid"].shape[0],
    "Invalid Series": df_results[df_results["Status"]!="Valid"].shape[0],
    "Overall wMAPE": f"{overall_wmape:.2%}" if pd.notnull(overall_wmape) else "NaN"
}
df_summary = pd.DataFrame([summary])

print("=== Group X - Individual Series Results (With Extended ARIMA/SARIMA Grid Search) ===")
print(df_results[["Series", "Model", "wMAPE (%)", "Status"]])
print("\n=== Group X - Summary (Valid series: wMAPE < 25%) ===")
df_summary

### Fine-tuning 1st time

In [ ]:
import numpy as np
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from pandas.tseries.holiday import USFederalHolidayCalendar
import warnings

warnings.filterwarnings("ignore")

df_final = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df_final.index = pd.to_datetime(df_final.index)



if df_final is not None:
    # Lọc các cột thuộc nhóm z (hậu tố _z)
    group_y_cols = [col for col in df_final.columns if col != 'Total' and col.endswith('_z')]
    forecast_periods = 6
    wmape_threshold = 35  # Mục tiêu: cải thiện series có WMAPE < 35%

    # **Thêm holiday feature**
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=df_final.index.min(), end=df_final.index.max())
    df_final["Holiday"] = df_final.index.isin(holidays).astype(int)

    fine_tuned_results = []

    print(f"🔄 Bắt đầu Fine-Tuning {len(group_y_cols)} series nhóm Y với holiday feature...")

    for col in group_y_cols:
        series = df_final[col].dropna()
        if len(series) < forecast_periods + 1:
            continue

        train = series.iloc[:-forecast_periods]
        test = series.iloc[-forecast_periods:]
        test_arr = np.array(test)

        train_holiday = df_final["Holiday"].iloc[:-forecast_periods]
        test_holiday = df_final["Holiday"].iloc[-forecast_periods:]

        # 🔹 Fine-tune Holt-Winters với nhiều thông số
        best_wmape = np.inf
        best_model = None
        best_forecast = None
        best_params = None

        hw_configs = [
            ("add", "add"), ("add", "mul"), ("mul", "add"), ("mul", "mul")
        ]

        for trend, seasonal in hw_configs:
            try:
                model_hw = ExponentialSmoothing(
                    train, trend=trend, seasonal=seasonal,
                    seasonal_periods=12, damped_trend=True
                ).fit()
                forecast_hw = model_hw.forecast(forecast_periods)
                error_hw = np.sum(np.abs(forecast_hw - test_arr))
                wmape_hw = error_hw / np.sum(test_arr) * 100 if np.sum(test_arr) > 0 else np.inf

                if wmape_hw < best_wmape:
                    best_wmape = wmape_hw
                    best_model = model_hw
                    best_forecast = forecast_hw
                    best_params = f"Holt-Winters({trend}, {seasonal})"
            except:
                continue

        # 🔹 Fine-tune ARIMA nếu Holt-Winters chưa tốt
        if best_wmape >= wmape_threshold:
            arima_orders = [(1,1,0), (0,1,1), (1,1,1), (2,1,1)]
            for order in arima_orders:
                try:
                    model_arima = ARIMA(train, order=order).fit()
                    forecast_arima = model_arima.forecast(forecast_periods)
                    error_arima = np.sum(np.abs(forecast_arima - test_arr))
                    wmape_arima = error_arima / np.sum(test_arr) * 100

                    if wmape_arima < best_wmape:
                        best_wmape = wmape_arima
                        best_model = model_arima
                        best_forecast = forecast_arima
                        best_params = f"ARIMA{order}"
                except:
                    continue

        # 🔹 Fine-tune SARIMA nếu ARIMA chưa tốt
        if best_wmape >= wmape_threshold:
            sarima_orders = [((1,1,0), (1,0,1,12)), ((0,1,1), (1,0,1,12))]
            for non_seasonal, seasonal in sarima_orders:
                try:
                    model_sarima = SARIMAX(train, order=non_seasonal, seasonal_order=seasonal).fit(disp=False)
                    forecast_sarima = model_sarima.forecast(forecast_periods)
                    error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                    wmape_sarima = error_sarima / np.sum(test_arr) * 100

                    if wmape_sarima < best_wmape:
                        best_wmape = wmape_sarima
                        best_model = model_sarima
                        best_forecast = forecast_sarima
                        best_params = f"SARIMA{non_seasonal, seasonal}"
                except:
                    continue

        # 🔹 Lưu kết quả fine-tuning
        fine_tuned_results.append({
            "Series": col,
            "Best Model": best_params,
            "New WMAPE": best_wmape,
            "Status": "Improved" if best_wmape < wmape_threshold else "Not Improved"
        })

    # **Hiển thị kết quả fine-tuning**
    df_fine_tuned = pd.DataFrame(fine_tuned_results)
    print("\n=== Fine-Tuning Results (All Y-Series with Holiday Feature & Optimized Models) ===")
    print(df_fine_tuned.to_string(index=False))

    # Hiển thị số lượng series cải thiện được
    num_improved = df_fine_tuned[df_fine_tuned["Status"] == "Improved"].shape[0]
    print(f"\n✅ Số series được cải thiện sau fine-tuning: {num_improved}/{len(group_y_cols)}")

### Fine-tuning 2nd time

In [ ]:
# 🔄 Fine-tuning lại các series chưa cải thiện bằng phương pháp nâng cao
print("\n🔄 Bắt đầu Fine-Tuning lại các series chưa đạt WMAPE < 35%...")

# **Lọc ra danh sách các series chưa đạt yêu cầu**
df_not_improved = df_fine_tuned[df_fine_tuned["Status"] == "Not Improved"]
series_to_finetune = df_not_improved["Series"].tolist()

# **Lưu kết quả fine-tuning nâng cao**
fine_tuned_results_v2 = []

for col in series_to_finetune:
    series = df_final[col].dropna()
    if len(series) < forecast_periods + 1:
        continue

    train = series.iloc[:-forecast_periods]
    test = series.iloc[-forecast_periods:]
    test_arr = np.array(test)

    train_holiday = df_final["Holiday"].iloc[:-forecast_periods]
    test_holiday = df_final["Holiday"].iloc[-forecast_periods:]

    # **🔹 Bổ sung Moving Average để làm trơn dữ liệu**
    train_smooth = train.rolling(window=3, min_periods=1).mean()

    # **🔹 Thử Holt-Winters với thông số mở rộng hơn**
    best_wmape = np.inf
    best_model = None
    best_forecast = None
    best_params = None

    hw_configs = [
        ("add", "add"), ("add", "mul"), ("mul", "add"), ("mul", "mul")
    ]

    for trend, seasonal in hw_configs:
        try:
            model_hw = ExponentialSmoothing(
                train_smooth, trend=None, seasonal=None,
                seasonal_periods=12, damped_trend=True
            ).fit()
            forecast_hw = model_hw.forecast(forecast_periods)
            error_hw = np.sum(np.abs(forecast_hw - test_arr))
            wmape_hw = error_hw / np.sum(test_arr) * 100 if np.sum(test_arr) > 0 else np.inf

            if wmape_hw < best_wmape:
                best_wmape = wmape_hw
                best_model = model_hw
                best_forecast = forecast_hw
                best_params = f"Holt-Winters({trend}, {seasonal})"
        except:
            continue

    # **🔹 Thử lại ARIMA/SARIMA nếu Holt-Winters chưa tốt**
    if best_wmape >= wmape_threshold:
        arima_orders = [(2,1,2), (1,1,2), (2,1,1), (3,1,2)]
        for order in arima_orders:
            try:
                model_arima = ARIMA(train, order=order).fit()
                forecast_arima = model_arima.forecast(forecast_periods)
                error_arima = np.sum(np.abs(forecast_arima - test_arr))
                wmape_arima = error_arima / np.sum(test_arr) * 100

                if wmape_arima < best_wmape:
                    best_wmape = wmape_arima
                    best_model = model_arima
                    best_forecast = forecast_arima
                    best_params = f"ARIMA{order}"
            except:
                continue

    # **🔹 Thử SARIMA nếu ARIMA chưa tốt**
    if best_wmape >= wmape_threshold:
        sarima_orders = [((2,1,1), (1,0,1,12)), ((1,1,2), (1,0,1,12))]
        for non_seasonal, seasonal in sarima_orders:
            try:
                model_sarima = SARIMAX(train, order=non_seasonal, seasonal_order=seasonal).fit(disp=False)
                forecast_sarima = model_sarima.forecast(forecast_periods)
                error_sarima = np.sum(np.abs(forecast_sarima - test_arr))
                wmape_sarima = error_sarima / np.sum(test_arr) * 100

                if wmape_sarima < best_wmape:
                    best_wmape = wmape_sarima
                    best_model = model_sarima
                    best_forecast = forecast_sarima
                    best_params = f"SARIMA{non_seasonal, seasonal}"
            except:
                continue

    # **🔹 Lưu kết quả fine-tuning nâng cao**
    fine_tuned_results_v2.append({
        "Series": col,
        "Best Model": best_params,
        "New WMAPE": best_wmape,
        "Status": "Improved" if best_wmape < wmape_threshold else "Not Improved"
    })

# **Hiển thị kết quả fine-tuning nâng cao**
df_fine_tuned_v2 = pd.DataFrame(fine_tuned_results_v2)
print("\n=== 🔥 Fine-Tuning Lần 2: Cải Thiện Các Series Chưa Đạt ===")
print(df_fine_tuned_v2.to_string(index=False))

# **Tính số lượng series được cải thiện sau fine-tuning lần 2**
num_improved_v2 = df_fine_tuned_v2[df_fine_tuned_v2["Status"] == "Improved"].shape[0]
print(f"\n✅ Số series được cải thiện sau Fine-Tuning lần 2: {num_improved_v2}/{len(series_to_finetune)}")

# 7.Deploy model on Gradient

In [ ]:
!pip install gradio
!pip uninstall pmdarima
!pip install --no-cache-dir pmdarima
!pip install numpy==1.25
!pip install --upgrade gradio
!python app.py

In [ ]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from datetime import datetime
import plotly.graph_objects as go

# Modeling
from pmdarima import auto_arima
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import Ridge
from xgboost import XGBRegressor

# Deep learning
import tensorflow as tf
tf.random.set_seed(42)
np.random.seed(42)

# Gradio
import gradio as gr

#########################################
# 1. ĐỌC & CHUẨN BỊ DỮ LIỆU
#########################################
df = pd.read_csv('Series_Hierarchical.csv', index_col=0, parse_dates=True)
df.index = pd.to_datetime(df.index)

group_x_cols = [col for col in df.columns if col.endswith('_x')]
group_y_cols = [col for col in df.columns if col.endswith('_y')]
group_z_cols = [col for col in df.columns if col.endswith('_z')]

# Thêm "All" vào dropdown
group_x_options = ["All"] + group_x_cols
group_y_options = ["All"] + group_y_cols
group_z_options = ["All"] + group_z_cols

#########################################
# 2. HÀM TIỆN ÍCH CHUNG
#########################################
def build_future_dates(last_date, periods):
    """Tạo dãy datetime hàng tháng, bắt đầu từ tháng tiếp theo của last_date."""
    return pd.date_range(start=last_date + pd.DateOffset(months=1),
                         periods=periods, freq="M")

def plot_history_and_forecast(history_series, forecast_df, title):
    """Trả về plotly figure hiển thị dữ liệu lịch sử (màu cam) + forecast (màu đen)."""
    fig = go.Figure()
    # Dữ liệu lịch sử (màu cam)
    fig.add_trace(go.Scatter(
        x=history_series.index,
        y=history_series.values,
        mode='lines',
        name="Historical",
        line=dict(color="orange")
    ))
    # Forecast (màu đen, nét đứt)
    fig.add_trace(go.Scatter(
        x=forecast_df["Date"],
        y=forecast_df["Forecast"],
        mode='lines',
        name="Forecast",
        line=dict(dash="dash", color="black")
    ))
    fig.update_layout(
        title=title,
        xaxis_title="Date",
        yaxis_title="Quantity",
        hovermode="x unified",
        margin=dict(l=40, r=20, t=60, b=40)
    )
    return fig

#########################################
# 3. PIPELINE CHO GROUP X (ĐƠN GIẢN)
#########################################
def pipeline_x_forecast(series, months=6):
    """Dự báo future cho 1 series nhóm X."""
    if len(series) < 3:
        return None

    # ARIMA
    try:
        model_arima = auto_arima(series, seasonal=True, m=12, stepwise=True, trace=False)
        forecast_arima = model_arima.predict(n_periods=months)
    except:
        forecast_arima = np.full(months, np.nan)

    # Holt-Winters
    try:
        model_hw = ExponentialSmoothing(series, trend='add', seasonal='add', seasonal_periods=12).fit()
        forecast_hw = model_hw.forecast(months)
    except:
        forecast_hw = np.full(months, np.nan)

    # Ensemble (50-50)
    ensemble_pred = 0.5 * forecast_arima + 0.5 * forecast_hw

    last_date = series.index[-1]
    future_dates = build_future_dates(last_date, months)
    df_forecast = pd.DataFrame({"Date": future_dates, "Forecast": ensemble_pred})
    return df_forecast

def forecast_future_x(col, months):
    """Xử lý logic forecast cho 1 cột hoặc 'All' (cộng dồn) của Group X."""
    if col == "All":
        sum_forecast = None
        base_future_dates = None
        for c in group_x_cols:
            s = df[c].dropna()
            fc = pipeline_x_forecast(s, months)
            if fc is not None:
                if sum_forecast is None:
                    sum_forecast = fc["Forecast"].values
                    base_future_dates = fc["Date"]
                else:
                    sum_forecast += fc["Forecast"].values
        if base_future_dates is None:
            return None
        return pd.DataFrame({"Date": base_future_dates, "Forecast": sum_forecast})
    else:
        s = df[col].dropna()
        fc = pipeline_x_forecast(s, months)
        return fc

def plot_forecast_x(col, months):
    forecast_df = forecast_future_x(col, months)
    if forecast_df is None or forecast_df["Forecast"].isnull().all():
        return go.Figure()

    if col == "All":
        # Lịch sử cộng dồn
        hist = df[group_x_cols].dropna().sum(axis=1)
        fig = plot_history_and_forecast(hist, forecast_df, "Group X - All Series")
        return fig
    else:
        hist = df[col].dropna()
        fig = plot_history_and_forecast(hist, forecast_df, f"Group X - {col}")
        return fig

def gradio_predict_x(col, months):
    months = int(months)
    fc_df = forecast_future_x(col, months)
    if fc_df is None:
        return pd.DataFrame({"Date": [], "Forecast": []}), go.Figure()
    fc_df["Forecast"] = fc_df["Forecast"].round(2)
    fig = plot_forecast_x(col, months)
    return fc_df, fig

#########################################
# 4. PIPELINE CHO GROUP Y (TƯƠNG TỰ)
#########################################
def pipeline_y_forecast(series, months=6):
    if len(series) < 3:
        return None

    # Holt-Winters
    try:
        model_hw = ExponentialSmoothing(series, trend='add', seasonal='add', seasonal_periods=12).fit()
        forecast_hw = model_hw.forecast(months)
    except:
        forecast_hw = np.full(months, np.nan)

    # ARIMA
    try:
        model_arima = auto_arima(series, seasonal=True, m=12, stepwise=True, trace=False)
        forecast_arima = model_arima.predict(n_periods=months)
    except:
        forecast_arima = np.full(months, np.nan)

    # XGB
    try:
        X = np.arange(len(series)).reshape(-1, 1)
        y = series.values
        model_xgb = XGBRegressor(n_estimators=50, learning_rate=0.1)
        model_xgb.fit(X, y)
        future_X = np.arange(len(series), len(series)+months).reshape(-1, 1)
        forecast_xgb = model_xgb.predict(future_X)
    except:
        forecast_xgb = np.full(months, np.nan)

    # Ensemble (trung bình 3)
    arr_hw = np.nan_to_num(forecast_hw)
    arr_arima = np.nan_to_num(forecast_arima)
    arr_xgb = np.nan_to_num(forecast_xgb)
    ensemble_pred = (arr_hw + arr_arima + arr_xgb) / 3

    last_date = series.index[-1]
    future_dates = build_future_dates(last_date, months)
    return pd.DataFrame({"Date": future_dates, "Forecast": ensemble_pred})

def forecast_future_y(col, months):
    if col == "All":
        sum_forecast = None
        base_future_dates = None
        for c in group_y_cols:
            s = df[c].dropna()
            fc = pipeline_y_forecast(s, months)
            if fc is not None:
                if sum_forecast is None:
                    sum_forecast = fc["Forecast"].values
                    base_future_dates = fc["Date"]
                else:
                    sum_forecast += fc["Forecast"].values
        if base_future_dates is None:
            return None
        return pd.DataFrame({"Date": base_future_dates, "Forecast": sum_forecast})
    else:
        s = df[col].dropna()
        return pipeline_y_forecast(s, months)

def plot_forecast_y(col, months):
    forecast_df = forecast_future_y(col, months)
    if forecast_df is None or forecast_df["Forecast"].isnull().all():
        return go.Figure()
    if col == "All":
        hist = df[group_y_cols].dropna().sum(axis=1)
        fig = plot_history_and_forecast(hist, forecast_df, "Group Y - All Series")
        return fig
    else:
        hist = df[col].dropna()
        fig = plot_history_and_forecast(hist, forecast_df, f"Group Y - {col}")
        return fig

def gradio_predict_y(col, months):
    months = int(months)
    fc_df = forecast_future_y(col, months)
    if fc_df is None:
        return pd.DataFrame({"Date": [], "Forecast": []}), go.Figure()
    fc_df["Forecast"] = fc_df["Forecast"].round(2)
    fig = plot_forecast_y(col, months)
    return fc_df, fig

#########################################
# 5. PIPELINE CHO GROUP Z (TƯƠNG TỰ)
#########################################
def pipeline_z_forecast(series, months=6):
    if len(series) < 3:
        return None

    # Model 1: SARIMAX
    try:
        model_sarimax = auto_arima(series, seasonal=True, m=12, stepwise=True, trace=False)
        forecast_sarimax = model_sarimax.predict(n_periods=months)
    except:
        forecast_sarimax = np.full(months, np.nan)

    # Model 2: GradientBoost
    try:
        X = np.arange(len(series)).reshape(-1, 1)
        y = series.values
        model_gbr = GradientBoostingRegressor(n_estimators=100, learning_rate=0.05)
        model_gbr.fit(X, y)
        future_X = np.arange(len(series), len(series)+months).reshape(-1, 1)
        forecast_gbr = model_gbr.predict(future_X)
    except:
        forecast_gbr = np.full(months, np.nan)

    # Model 3: Ridge
    try:
        model_ridge = Ridge(alpha=1.0, random_state=42)
        model_ridge.fit(X, y)
        future_ridge = model_ridge.predict(future_X)
    except:
        future_ridge = np.full(months, np.nan)

    # Model 4: Naive
    naive_val = series.iloc[-1] if len(series) > 0 else 0
    forecast_naive = np.full(months, naive_val)

    # Ensemble median
    forecasts_stack = np.vstack([
        np.nan_to_num(forecast_sarimax),
        np.nan_to_num(forecast_gbr),
        np.nan_to_num(future_ridge),
        np.nan_to_num(forecast_naive)
    ])
    ensemble_pred = np.median(forecasts_stack, axis=0)

    last_date = series.index[-1]
    future_dates = build_future_dates(last_date, months)
    return pd.DataFrame({"Date": future_dates, "Forecast": ensemble_pred})

def forecast_future_z(col, months):
    if col == "All":
        sum_forecast = None
        base_future_dates = None
        for c in group_z_cols:
            s = df[c].dropna()
            fc = pipeline_z_forecast(s, months)
            if fc is not None:
                if sum_forecast is None:
                    sum_forecast = fc["Forecast"].values
                    base_future_dates = fc["Date"]
                else:
                    sum_forecast += fc["Forecast"].values
        if base_future_dates is None:
            return None
        return pd.DataFrame({"Date": base_future_dates, "Forecast": sum_forecast})
    else:
        s = df[col].dropna()
        return pipeline_z_forecast(s, months)

def plot_forecast_z(col, months):
    forecast_df = forecast_future_z(col, months)
    if forecast_df is None or forecast_df["Forecast"].isnull().all():
        return go.Figure()
    if col == "All":
        hist = df[group_z_cols].dropna().sum(axis=1)
        fig = plot_history_and_forecast(hist, forecast_df, "Group Z - All Series")
        return fig
    else:
        hist = df[col].dropna()
        fig = plot_history_and_forecast(hist, forecast_df, f"Group Z - {col}")
        return fig

def gradio_predict_z(col, months):
    months = int(months)
    fc_df = forecast_future_z(col, months)
    if fc_df is None:
        return pd.DataFrame({"Date": [], "Forecast": []}), go.Figure()
    fc_df["Forecast"] = fc_df["Forecast"].round(2)
    fig = plot_forecast_z(col, months)
    return fc_df, fig

#########################################
# 6. GRADIO DEPLOYMENT (3 Tabs: X, Y, Z)
#########################################

# CSS: Chỉ ép màu chữ là đen (và nền trắng) cho các phần tử text,
# KHÔNG động đến stroke/fill của các phần tử svg (Plotly lines).
custom_css = """
/* Ép text đen, nền trắng cho các element văn bản, input, button... */
body, .gradio-container, .gradio-container input,
.gradio-container textarea,
.gradio-container select,
.gradio-container button,
.gradio-container label,
.gradio-container p,
.gradio-container h1,
.gradio-container h2,
.gradio-container h3,
.gradio-container h4,
.gradio-container h5,
.gradio-container h6,
.gradio-container div,
.gradio-container span,
.gradio-container strong,
.gradio-container em {
  background-color: #FFFFFF !important;
  color: #000000 !important;
}

/* Placeholder input cũng màu đen */
::placeholder {
  color: #000000 !important;
}

/* Chiều cao cho plot */
.gradio-plot {
  height: 500px !important;
}
"""

with gr.Blocks(css=custom_css) as demo:
    gr.Markdown("# Multi-Group Series Forecasting Deployment for Accessories Products")

    with gr.Tabs():
        # --- TAB CHO GROUP X ---
        with gr.Tab("Group X"):
            gr.Markdown("**Forecast for columns ending with `_x`**")

            dropdown_x = gr.Dropdown(label="Select Column", choices=group_x_options, value="All")
            forecast_periods_x = gr.Slider(label="Forecast Periods (months)", minimum=1, maximum=36, value=6, step=1)
            btn_x = gr.Button("Forecast")

            with gr.Row():
                out_table_x = gr.Dataframe(label="Forecast Table")
                out_plot_x = gr.Plot(label="Forecast Chart")

            btn_x.click(
                fn=gradio_predict_x,
                inputs=[dropdown_x, forecast_periods_x],
                outputs=[out_table_x, out_plot_x]
            )

        # --- TAB CHO GROUP Y ---
        with gr.Tab("Group Y"):
            gr.Markdown("**Forecast for columns ending with `_y`**")

            dropdown_y = gr.Dropdown(label="Select Column", choices=group_y_options, value="All")
            forecast_periods_y = gr.Slider(label="Forecast Periods (months)", minimum=1, maximum=36, value=6, step=1)
            btn_y = gr.Button("Forecast")

            with gr.Row():
                out_table_y = gr.Dataframe(label="Forecast Table")
                out_plot_y = gr.Plot(label="Forecast Chart")

            btn_y.click(
                fn=gradio_predict_y,
                inputs=[dropdown_y, forecast_periods_y],
                outputs=[out_table_y, out_plot_y]
            )

        # --- TAB CHO GROUP Z ---
        with gr.Tab("Group Z"):
            gr.Markdown("**Forecast for columns ending with `_z`**")

            dropdown_z = gr.Dropdown(label="Select Column", choices=group_z_options, value="All")
            forecast_periods_z = gr.Slider(label="Forecast Periods (months)", minimum=1, maximum=36, value=6, step=1)
            btn_z = gr.Button("Forecast")

            with gr.Row():
                out_table_z = gr.Dataframe(label="Forecast Table")
                out_plot_z = gr.Plot(label="Forecast Chart")

            btn_z.click(
                fn=gradio_predict_z,
                inputs=[dropdown_z, forecast_periods_z],
                outputs=[out_table_z, out_plot_z]
            )

demo.launch(share=True)